// Code generated by github.com/kjkrol/goke/internal/cmd/gen/views; DO NOT EDIT.
package goke

import "github.com/kjkrol/goke/internal/query"

// View0 iterates entities that have no specific components (filter-only), yielding typed slices per chunk.
type View0 = query.View0

// NewView0 creates a View for entities that have no specific components (filter-only), filtered by opts.
func NewView0(
	ecs *ECS,
	opts ...BlueprintOpt,
) *View0 {
	return query.NewView0(&ecs.registry.ViewCatalog, opts...)
}

// View1 iterates entities that have T1, yielding typed slices per chunk.
type View1[T1 any] = query.View1[T1]

// NewView1 creates a View for entities that have T1, filtered by opts.
func NewView1[T1 any](
	ecs *ECS,
	opts ...BlueprintOpt,
) *View1[T1] {
	return query.NewView1[T1](&ecs.registry.ViewCatalog, opts...)
}

// View2 iterates entities that have T1, T2, yielding typed slices per chunk.
type View2[T1 any, T2 any] = query.View2[T1, T2]

// NewView2 creates a View for entities that have T1, T2, filtered by opts.
func NewView2[T1 any, T2 any](
	ecs *ECS,
	opts ...BlueprintOpt,
) *View2[T1, T2] {
	return query.NewView2[T1, T2](&ecs.registry.ViewCatalog, opts...)
}

// View3 iterates entities that have T1, T2, T3, yielding typed slices per chunk.
type View3[T1 any, T2 any, T3 any] = query.View3[T1, T2, T3]

// NewView3 creates a View for entities that have T1, T2, T3, filtered by opts.
func NewView3[T1 any, T2 any, T3 any](
	ecs *ECS,
	opts ...BlueprintOpt,
) *View3[T1, T2, T3] {
	return query.NewView3[T1, T2, T3](&ecs.registry.ViewCatalog, opts...)
}

// View4 iterates entities that have T1, T2, T3, T4, yielding typed slices per chunk.
type View4[T1 any, T2 any, T3 any, T4 any] = query.View4[T1, T2, T3, T4]

// NewView4 creates a View for entities that have T1, T2, T3, T4, filtered by opts.
func NewView4[T1 any, T2 any, T3 any, T4 any](
	ecs *ECS,
	opts ...BlueprintOpt,
) *View4[T1, T2, T3, T4] {
	return query.NewView4[T1, T2, T3, T4](&ecs.registry.ViewCatalog, opts...)
}

// View5 iterates entities that have T1, T2, T3, T4, T5, yielding typed slices per chunk.
type View5[T1 any, T2 any, T3 any, T4 any, T5 any] = query.View5[T1, T2, T3, T4, T5]

// NewView5 creates a View for entities that have T1, T2, T3, T4, T5, filtered by opts.
func NewView5[T1 any, T2 any, T3 any, T4 any, T5 any](
	ecs *ECS,
	opts ...BlueprintOpt,
) *View5[T1, T2, T3, T4, T5] {
	return query.NewView5[T1, T2, T3, T4, T5](&ecs.registry.ViewCatalog, opts...)
}

// View6 iterates entities that have T1, T2, T3, T4, T5, T6, yielding typed slices per chunk.
type View6[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any] = query.View6[T1, T2, T3, T4, T5, T6]

// NewView6 creates a View for entities that have T1, T2, T3, T4, T5, T6, filtered by opts.
func NewView6[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any](
	ecs *ECS,
	opts ...BlueprintOpt,
) *View6[T1, T2, T3, T4, T5, T6] {
	return query.NewView6[T1, T2, T3, T4, T5, T6](&ecs.registry.ViewCatalog, opts...)
}

// View7 iterates entities that have T1, T2, T3, T4, T5, T6, T7, yielding typed slices per chunk.
type View7[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any] = query.View7[T1, T2, T3, T4, T5, T6, T7]

// NewView7 creates a View for entities that have T1, T2, T3, T4, T5, T6, T7, filtered by opts.
func NewView7[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any](
	ecs *ECS,
	opts ...BlueprintOpt,
) *View7[T1, T2, T3, T4, T5, T6, T7] {
	return query.NewView7[T1, T2, T3, T4, T5, T6, T7](&ecs.registry.ViewCatalog, opts...)
}

// View8 iterates entities that have T1, T2, T3, T4, T5, T6, T7, T8, yielding typed slices per chunk.
type View8[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any, T8 any] = query.View8[T1, T2, T3, T4, T5, T6, T7, T8]

// NewView8 creates a View for entities that have T1, T2, T3, T4, T5, T6, T7, T8, filtered by opts.
func NewView8[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any, T8 any](
	ecs *ECS,
	opts ...BlueprintOpt,
) *View8[T1, T2, T3, T4, T5, T6, T7, T8] {
	return query.NewView8[T1, T2, T3, T4, T5, T6, T7, T8](&ecs.registry.ViewCatalog, opts...)
}

// View9 iterates entities that have T1, T2, T3, T4, T5, T6, T7, T8, T9, yielding typed slices per chunk.
type View9[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any, T8 any, T9 any] = query.View9[T1, T2, T3, T4, T5, T6, T7, T8, T9]

// NewView9 creates a View for entities that have T1, T2, T3, T4, T5, T6, T7, T8, T9, filtered by opts.
func NewView9[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any, T8 any, T9 any](
	ecs *ECS,
	opts ...BlueprintOpt,
) *View9[T1, T2, T3, T4, T5, T6, T7, T8, T9] {
	return query.NewView9[T1, T2, T3, T4, T5, T6, T7, T8, T9](&ecs.registry.ViewCatalog, opts...)
}

// View10 iterates entities that have T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, yielding typed slices per chunk.
type View10[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any, T8 any, T9 any, T10 any] = query.View10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]

// NewView10 creates a View for entities that have T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, filtered by opts.
func NewView10[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any, T8 any, T9 any, T10 any](
	ecs *ECS,
	opts ...BlueprintOpt,
) *View10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10] {
	return query.NewView10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10](&ecs.registry.ViewCatalog, opts...)
}
