// Code generated by github.com/kjkrol/goke/internal/cmd/gen/blueprints; DO NOT EDIT.
package goke

import (
	"fmt"
	"iter"
	"reflect"
	"unsafe"

    "github.com/kjkrol/goke/internal/core"
)

// Blueprint1 defines a static template (recipe) for the mass construction
// of entities with a predefined set of 1 stateful components. It allows
// for precise memory layout planning before allocation, which is essential
// for high-performance data access patterns.
//
// For example, a Blueprint1 could be used to define complex actors that
// require exactly 1 distinct data structures to be stored contiguously,
// ensuring optimal data locality and cache efficiency.
type Blueprint1[T1 any] struct {
    itemFactory *core.ItemFactory
}

// NewBlueprint1 initializes a new template for a specific combination of 1 components.
// It accepts optional BlueprintOptions (e.g., Include[Tag]()) to extend the
// template with any number of stateless components (Tags). Tags do not occupy
// space in the data columns but allow for precise population filtering within Views.
//
// By using a static definition, archetype metadata is registered once,
// enabling rapid entity spawning with minimal memory management overhead.
//
// This constructor panics if component registration fails or if there are
// configuration conflicts, ensuring a fail-fast behavior during system initialization.
func NewBlueprint1[T1 any](
    ecs *ECS,
    opts ...BlueprintOption,
) *Blueprint1[T1] {
    registry := ecs.registry
    blueprint := core.NewBlueprint(registry)

    // mustAdd ensures that component registration and blueprint assignment
    // are successful. Panics immediately on failure to support fail-fast startup.
    mustAdd := func(info core.ComponentInfo) {
        if err := blueprint.WithComp(info); err != nil {
            panic(fmt.Sprintf("goke: blueprint1 init failed: %v", err))
        }
    }

    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T1]()))
    
    // Apply dynamic options (Tags, Exclusions) and panic on any configuration error.
    for _, opt := range opts {
        if err := opt(blueprint); err != nil {
            panic(fmt.Sprintf("goke: blueprint1 option failed: %v", err))
        }
    }

    return &Blueprint1[T1]{
        itemFactory: core.NewItemFactory(blueprint),
    }
}

// BatchCreateX instantiates entities in bulk and returns an iterator yielding
// memory-aligned chunks for each component.
//
// Example:
//
//	for page := range blueprint.Create(100) {
//		for i, _ := range page.Entity {
//			batch.Comp1[1].X = 1
//		}
//	}

func (b *Blueprint1[T1]) Create(count int) iter.Seq[struct {
	Entity []Entity
	Comp1 []T1
}] {
	reg := b.itemFactory.Reg
	archReg := reg.ArchetypeRegistry
	arch := &archReg.Archetypes[b.itemFactory.ArchId]
	memo := &arch.Memory
	entityCol := &arch.Columns[core.EntityColumnIndex]
	col1 := arch.GetColumn(b.itemFactory.CompInfos[0].ID)
	remaining := count

	return func(yield func(struct {
		Entity []Entity
		Comp1 []T1
	}) bool) {
		pageIdx := core.PageIdx(len(memo.Pages) - 1)
		page := &memo.Pages[pageIdx]
		available := int(memo.Layout.PageCap) - int(page.Len)

		if available == 0 {
			pagesNeeded := (remaining + int(memo.Layout.PageCap) - 1) / int(memo.Layout.PageCap)
			memo.AddPages(pagesNeeded)
			pageIdx++
			page = &memo.Pages[pageIdx]
			available = int(memo.Layout.PageCap)
		} else {
			pagesNeeded := (remaining - available + int(memo.Layout.PageCap) - 1) / int(memo.Layout.PageCap)
			if pagesNeeded > 0 {
				memo.AddPages(pagesNeeded)
				page = &memo.Pages[pageIdx]
			}
		}

		for remaining > 0 {
			allocatedRows := min(remaining, available)
			startRow := page.Len
			page.Len += core.PageRow(allocatedRows)
			memo.Len += uint32(allocatedRows)

			for i := 0; i < allocatedRows; i++ {
				entity := reg.EntityPool.Next()
				pageRow := startRow + core.PageRow(i)
				destPtr := entityCol.GetPointer(page, pageRow)
				*(*Entity)(destPtr) = entity
				archReg.EntityLinkStore.Update(entity, b.itemFactory.ArchId, pageIdx, pageRow)
			}

			if !yield(
				struct {
					Entity []Entity
					Comp1 []T1
				}{
					Entity: unsafe.Slice((*Entity)(entityCol.GetPointer(page, startRow)), allocatedRows),
					Comp1: unsafe.Slice((*T1)(col1.GetPointer(page, startRow)), allocatedRows),
				}) {
				return
			}

			remaining -= allocatedRows
			if remaining > 0 {
				pageIdx++
				page = &memo.Pages[pageIdx]
				available = int(memo.Layout.PageCap)
			}
		}
	}
}
// Blueprint2 defines a static template (recipe) for the mass construction
// of entities with a predefined set of 2 stateful components. It allows
// for precise memory layout planning before allocation, which is essential
// for high-performance data access patterns.
//
// For example, a Blueprint2 could be used to define complex actors that
// require exactly 2 distinct data structures to be stored contiguously,
// ensuring optimal data locality and cache efficiency.
type Blueprint2[T1 any, T2 any] struct {
    itemFactory *core.ItemFactory
}

// NewBlueprint2 initializes a new template for a specific combination of 2 components.
// It accepts optional BlueprintOptions (e.g., Include[Tag]()) to extend the
// template with any number of stateless components (Tags). Tags do not occupy
// space in the data columns but allow for precise population filtering within Views.
//
// By using a static definition, archetype metadata is registered once,
// enabling rapid entity spawning with minimal memory management overhead.
//
// This constructor panics if component registration fails or if there are
// configuration conflicts, ensuring a fail-fast behavior during system initialization.
func NewBlueprint2[T1 any, T2 any](
    ecs *ECS,
    opts ...BlueprintOption,
) *Blueprint2[T1, T2] {
    registry := ecs.registry
    blueprint := core.NewBlueprint(registry)

    // mustAdd ensures that component registration and blueprint assignment
    // are successful. Panics immediately on failure to support fail-fast startup.
    mustAdd := func(info core.ComponentInfo) {
        if err := blueprint.WithComp(info); err != nil {
            panic(fmt.Sprintf("goke: blueprint2 init failed: %v", err))
        }
    }

    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T1]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T2]()))
    
    // Apply dynamic options (Tags, Exclusions) and panic on any configuration error.
    for _, opt := range opts {
        if err := opt(blueprint); err != nil {
            panic(fmt.Sprintf("goke: blueprint2 option failed: %v", err))
        }
    }

    return &Blueprint2[T1, T2]{
        itemFactory: core.NewItemFactory(blueprint),
    }
}

// BatchCreateX instantiates entities in bulk and returns an iterator yielding
// memory-aligned chunks for each component.
//
// Example:
//
//	for page := range blueprint.Create(100) {
//		for i, _ := range page.Entity {
//			batch.Comp1[1].X = 1
//			batch.Comp1[2].X = 1
//		}
//	}

func (b *Blueprint2[T1, T2]) Create(count int) iter.Seq[struct {
	Entity []Entity
	Comp1 []T1
	Comp2 []T2
}] {
	reg := b.itemFactory.Reg
	archReg := reg.ArchetypeRegistry
	arch := &archReg.Archetypes[b.itemFactory.ArchId]
	memo := &arch.Memory
	entityCol := &arch.Columns[core.EntityColumnIndex]
	col1 := arch.GetColumn(b.itemFactory.CompInfos[0].ID)
	col2 := arch.GetColumn(b.itemFactory.CompInfos[1].ID)
	remaining := count

	return func(yield func(struct {
		Entity []Entity
		Comp1 []T1
		Comp2 []T2
	}) bool) {
		pageIdx := core.PageIdx(len(memo.Pages) - 1)
		page := &memo.Pages[pageIdx]
		available := int(memo.Layout.PageCap) - int(page.Len)

		if available == 0 {
			pagesNeeded := (remaining + int(memo.Layout.PageCap) - 1) / int(memo.Layout.PageCap)
			memo.AddPages(pagesNeeded)
			pageIdx++
			page = &memo.Pages[pageIdx]
			available = int(memo.Layout.PageCap)
		} else {
			pagesNeeded := (remaining - available + int(memo.Layout.PageCap) - 1) / int(memo.Layout.PageCap)
			if pagesNeeded > 0 {
				memo.AddPages(pagesNeeded)
				page = &memo.Pages[pageIdx]
			}
		}

		for remaining > 0 {
			allocatedRows := min(remaining, available)
			startRow := page.Len
			page.Len += core.PageRow(allocatedRows)
			memo.Len += uint32(allocatedRows)

			for i := 0; i < allocatedRows; i++ {
				entity := reg.EntityPool.Next()
				pageRow := startRow + core.PageRow(i)
				destPtr := entityCol.GetPointer(page, pageRow)
				*(*Entity)(destPtr) = entity
				archReg.EntityLinkStore.Update(entity, b.itemFactory.ArchId, pageIdx, pageRow)
			}

			if !yield(
				struct {
					Entity []Entity
					Comp1 []T1
					Comp2 []T2
				}{
					Entity: unsafe.Slice((*Entity)(entityCol.GetPointer(page, startRow)), allocatedRows),
					Comp1: unsafe.Slice((*T1)(col1.GetPointer(page, startRow)), allocatedRows),
					Comp2: unsafe.Slice((*T2)(col2.GetPointer(page, startRow)), allocatedRows),
				}) {
				return
			}

			remaining -= allocatedRows
			if remaining > 0 {
				pageIdx++
				page = &memo.Pages[pageIdx]
				available = int(memo.Layout.PageCap)
			}
		}
	}
}
// Blueprint3 defines a static template (recipe) for the mass construction
// of entities with a predefined set of 3 stateful components. It allows
// for precise memory layout planning before allocation, which is essential
// for high-performance data access patterns.
//
// For example, a Blueprint3 could be used to define complex actors that
// require exactly 3 distinct data structures to be stored contiguously,
// ensuring optimal data locality and cache efficiency.
type Blueprint3[T1 any, T2 any, T3 any] struct {
    itemFactory *core.ItemFactory
}

// NewBlueprint3 initializes a new template for a specific combination of 3 components.
// It accepts optional BlueprintOptions (e.g., Include[Tag]()) to extend the
// template with any number of stateless components (Tags). Tags do not occupy
// space in the data columns but allow for precise population filtering within Views.
//
// By using a static definition, archetype metadata is registered once,
// enabling rapid entity spawning with minimal memory management overhead.
//
// This constructor panics if component registration fails or if there are
// configuration conflicts, ensuring a fail-fast behavior during system initialization.
func NewBlueprint3[T1 any, T2 any, T3 any](
    ecs *ECS,
    opts ...BlueprintOption,
) *Blueprint3[T1, T2, T3] {
    registry := ecs.registry
    blueprint := core.NewBlueprint(registry)

    // mustAdd ensures that component registration and blueprint assignment
    // are successful. Panics immediately on failure to support fail-fast startup.
    mustAdd := func(info core.ComponentInfo) {
        if err := blueprint.WithComp(info); err != nil {
            panic(fmt.Sprintf("goke: blueprint3 init failed: %v", err))
        }
    }

    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T1]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T2]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T3]()))
    
    // Apply dynamic options (Tags, Exclusions) and panic on any configuration error.
    for _, opt := range opts {
        if err := opt(blueprint); err != nil {
            panic(fmt.Sprintf("goke: blueprint3 option failed: %v", err))
        }
    }

    return &Blueprint3[T1, T2, T3]{
        itemFactory: core.NewItemFactory(blueprint),
    }
}

// BatchCreateX instantiates entities in bulk and returns an iterator yielding
// memory-aligned chunks for each component.
//
// Example:
//
//	for page := range blueprint.Create(100) {
//		for i, _ := range page.Entity {
//			batch.Comp1[1].X = 1
//			batch.Comp1[2].X = 1
//			batch.Comp1[3].X = 1
//		}
//	}

func (b *Blueprint3[T1, T2, T3]) Create(count int) iter.Seq[struct {
	Entity []Entity
	Comp1 []T1
	Comp2 []T2
	Comp3 []T3
}] {
	reg := b.itemFactory.Reg
	archReg := reg.ArchetypeRegistry
	arch := &archReg.Archetypes[b.itemFactory.ArchId]
	memo := &arch.Memory
	entityCol := &arch.Columns[core.EntityColumnIndex]
	col1 := arch.GetColumn(b.itemFactory.CompInfos[0].ID)
	col2 := arch.GetColumn(b.itemFactory.CompInfos[1].ID)
	col3 := arch.GetColumn(b.itemFactory.CompInfos[2].ID)
	remaining := count

	return func(yield func(struct {
		Entity []Entity
		Comp1 []T1
		Comp2 []T2
		Comp3 []T3
	}) bool) {
		pageIdx := core.PageIdx(len(memo.Pages) - 1)
		page := &memo.Pages[pageIdx]
		available := int(memo.Layout.PageCap) - int(page.Len)

		if available == 0 {
			pagesNeeded := (remaining + int(memo.Layout.PageCap) - 1) / int(memo.Layout.PageCap)
			memo.AddPages(pagesNeeded)
			pageIdx++
			page = &memo.Pages[pageIdx]
			available = int(memo.Layout.PageCap)
		} else {
			pagesNeeded := (remaining - available + int(memo.Layout.PageCap) - 1) / int(memo.Layout.PageCap)
			if pagesNeeded > 0 {
				memo.AddPages(pagesNeeded)
				page = &memo.Pages[pageIdx]
			}
		}

		for remaining > 0 {
			allocatedRows := min(remaining, available)
			startRow := page.Len
			page.Len += core.PageRow(allocatedRows)
			memo.Len += uint32(allocatedRows)

			for i := 0; i < allocatedRows; i++ {
				entity := reg.EntityPool.Next()
				pageRow := startRow + core.PageRow(i)
				destPtr := entityCol.GetPointer(page, pageRow)
				*(*Entity)(destPtr) = entity
				archReg.EntityLinkStore.Update(entity, b.itemFactory.ArchId, pageIdx, pageRow)
			}

			if !yield(
				struct {
					Entity []Entity
					Comp1 []T1
					Comp2 []T2
					Comp3 []T3
				}{
					Entity: unsafe.Slice((*Entity)(entityCol.GetPointer(page, startRow)), allocatedRows),
					Comp1: unsafe.Slice((*T1)(col1.GetPointer(page, startRow)), allocatedRows),
					Comp2: unsafe.Slice((*T2)(col2.GetPointer(page, startRow)), allocatedRows),
					Comp3: unsafe.Slice((*T3)(col3.GetPointer(page, startRow)), allocatedRows),
				}) {
				return
			}

			remaining -= allocatedRows
			if remaining > 0 {
				pageIdx++
				page = &memo.Pages[pageIdx]
				available = int(memo.Layout.PageCap)
			}
		}
	}
}
// Blueprint4 defines a static template (recipe) for the mass construction
// of entities with a predefined set of 4 stateful components. It allows
// for precise memory layout planning before allocation, which is essential
// for high-performance data access patterns.
//
// For example, a Blueprint4 could be used to define complex actors that
// require exactly 4 distinct data structures to be stored contiguously,
// ensuring optimal data locality and cache efficiency.
type Blueprint4[T1 any, T2 any, T3 any, T4 any] struct {
    itemFactory *core.ItemFactory
}

// NewBlueprint4 initializes a new template for a specific combination of 4 components.
// It accepts optional BlueprintOptions (e.g., Include[Tag]()) to extend the
// template with any number of stateless components (Tags). Tags do not occupy
// space in the data columns but allow for precise population filtering within Views.
//
// By using a static definition, archetype metadata is registered once,
// enabling rapid entity spawning with minimal memory management overhead.
//
// This constructor panics if component registration fails or if there are
// configuration conflicts, ensuring a fail-fast behavior during system initialization.
func NewBlueprint4[T1 any, T2 any, T3 any, T4 any](
    ecs *ECS,
    opts ...BlueprintOption,
) *Blueprint4[T1, T2, T3, T4] {
    registry := ecs.registry
    blueprint := core.NewBlueprint(registry)

    // mustAdd ensures that component registration and blueprint assignment
    // are successful. Panics immediately on failure to support fail-fast startup.
    mustAdd := func(info core.ComponentInfo) {
        if err := blueprint.WithComp(info); err != nil {
            panic(fmt.Sprintf("goke: blueprint4 init failed: %v", err))
        }
    }

    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T1]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T2]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T3]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T4]()))
    
    // Apply dynamic options (Tags, Exclusions) and panic on any configuration error.
    for _, opt := range opts {
        if err := opt(blueprint); err != nil {
            panic(fmt.Sprintf("goke: blueprint4 option failed: %v", err))
        }
    }

    return &Blueprint4[T1, T2, T3, T4]{
        itemFactory: core.NewItemFactory(blueprint),
    }
}

// BatchCreateX instantiates entities in bulk and returns an iterator yielding
// memory-aligned chunks for each component.
//
// Example:
//
//	for page := range blueprint.Create(100) {
//		for i, _ := range page.Entity {
//			batch.Comp1[1].X = 1
//			batch.Comp1[2].X = 1
//			batch.Comp1[3].X = 1
//			batch.Comp1[4].X = 1
//		}
//	}

func (b *Blueprint4[T1, T2, T3, T4]) Create(count int) iter.Seq[struct {
	Entity []Entity
	Comp1 []T1
	Comp2 []T2
	Comp3 []T3
	Comp4 []T4
}] {
	reg := b.itemFactory.Reg
	archReg := reg.ArchetypeRegistry
	arch := &archReg.Archetypes[b.itemFactory.ArchId]
	memo := &arch.Memory
	entityCol := &arch.Columns[core.EntityColumnIndex]
	col1 := arch.GetColumn(b.itemFactory.CompInfos[0].ID)
	col2 := arch.GetColumn(b.itemFactory.CompInfos[1].ID)
	col3 := arch.GetColumn(b.itemFactory.CompInfos[2].ID)
	col4 := arch.GetColumn(b.itemFactory.CompInfos[3].ID)
	remaining := count

	return func(yield func(struct {
		Entity []Entity
		Comp1 []T1
		Comp2 []T2
		Comp3 []T3
		Comp4 []T4
	}) bool) {
		pageIdx := core.PageIdx(len(memo.Pages) - 1)
		page := &memo.Pages[pageIdx]
		available := int(memo.Layout.PageCap) - int(page.Len)

		if available == 0 {
			pagesNeeded := (remaining + int(memo.Layout.PageCap) - 1) / int(memo.Layout.PageCap)
			memo.AddPages(pagesNeeded)
			pageIdx++
			page = &memo.Pages[pageIdx]
			available = int(memo.Layout.PageCap)
		} else {
			pagesNeeded := (remaining - available + int(memo.Layout.PageCap) - 1) / int(memo.Layout.PageCap)
			if pagesNeeded > 0 {
				memo.AddPages(pagesNeeded)
				page = &memo.Pages[pageIdx]
			}
		}

		for remaining > 0 {
			allocatedRows := min(remaining, available)
			startRow := page.Len
			page.Len += core.PageRow(allocatedRows)
			memo.Len += uint32(allocatedRows)

			for i := 0; i < allocatedRows; i++ {
				entity := reg.EntityPool.Next()
				pageRow := startRow + core.PageRow(i)
				destPtr := entityCol.GetPointer(page, pageRow)
				*(*Entity)(destPtr) = entity
				archReg.EntityLinkStore.Update(entity, b.itemFactory.ArchId, pageIdx, pageRow)
			}

			if !yield(
				struct {
					Entity []Entity
					Comp1 []T1
					Comp2 []T2
					Comp3 []T3
					Comp4 []T4
				}{
					Entity: unsafe.Slice((*Entity)(entityCol.GetPointer(page, startRow)), allocatedRows),
					Comp1: unsafe.Slice((*T1)(col1.GetPointer(page, startRow)), allocatedRows),
					Comp2: unsafe.Slice((*T2)(col2.GetPointer(page, startRow)), allocatedRows),
					Comp3: unsafe.Slice((*T3)(col3.GetPointer(page, startRow)), allocatedRows),
					Comp4: unsafe.Slice((*T4)(col4.GetPointer(page, startRow)), allocatedRows),
				}) {
				return
			}

			remaining -= allocatedRows
			if remaining > 0 {
				pageIdx++
				page = &memo.Pages[pageIdx]
				available = int(memo.Layout.PageCap)
			}
		}
	}
}
// Blueprint5 defines a static template (recipe) for the mass construction
// of entities with a predefined set of 5 stateful components. It allows
// for precise memory layout planning before allocation, which is essential
// for high-performance data access patterns.
//
// For example, a Blueprint5 could be used to define complex actors that
// require exactly 5 distinct data structures to be stored contiguously,
// ensuring optimal data locality and cache efficiency.
type Blueprint5[T1 any, T2 any, T3 any, T4 any, T5 any] struct {
    itemFactory *core.ItemFactory
}

// NewBlueprint5 initializes a new template for a specific combination of 5 components.
// It accepts optional BlueprintOptions (e.g., Include[Tag]()) to extend the
// template with any number of stateless components (Tags). Tags do not occupy
// space in the data columns but allow for precise population filtering within Views.
//
// By using a static definition, archetype metadata is registered once,
// enabling rapid entity spawning with minimal memory management overhead.
//
// This constructor panics if component registration fails or if there are
// configuration conflicts, ensuring a fail-fast behavior during system initialization.
func NewBlueprint5[T1 any, T2 any, T3 any, T4 any, T5 any](
    ecs *ECS,
    opts ...BlueprintOption,
) *Blueprint5[T1, T2, T3, T4, T5] {
    registry := ecs.registry
    blueprint := core.NewBlueprint(registry)

    // mustAdd ensures that component registration and blueprint assignment
    // are successful. Panics immediately on failure to support fail-fast startup.
    mustAdd := func(info core.ComponentInfo) {
        if err := blueprint.WithComp(info); err != nil {
            panic(fmt.Sprintf("goke: blueprint5 init failed: %v", err))
        }
    }

    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T1]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T2]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T3]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T4]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T5]()))
    
    // Apply dynamic options (Tags, Exclusions) and panic on any configuration error.
    for _, opt := range opts {
        if err := opt(blueprint); err != nil {
            panic(fmt.Sprintf("goke: blueprint5 option failed: %v", err))
        }
    }

    return &Blueprint5[T1, T2, T3, T4, T5]{
        itemFactory: core.NewItemFactory(blueprint),
    }
}

// BatchCreateX instantiates entities in bulk and returns an iterator yielding
// memory-aligned chunks for each component.
//
// Example:
//
//	for page := range blueprint.Create(100) {
//		for i, _ := range page.Entity {
//			batch.Comp1[1].X = 1
//			batch.Comp1[2].X = 1
//			batch.Comp1[3].X = 1
//			batch.Comp1[4].X = 1
//			batch.Comp1[5].X = 1
//		}
//	}

func (b *Blueprint5[T1, T2, T3, T4, T5]) Create(count int) iter.Seq[struct {
	Entity []Entity
	Comp1 []T1
	Comp2 []T2
	Comp3 []T3
	Comp4 []T4
	Comp5 []T5
}] {
	reg := b.itemFactory.Reg
	archReg := reg.ArchetypeRegistry
	arch := &archReg.Archetypes[b.itemFactory.ArchId]
	memo := &arch.Memory
	entityCol := &arch.Columns[core.EntityColumnIndex]
	col1 := arch.GetColumn(b.itemFactory.CompInfos[0].ID)
	col2 := arch.GetColumn(b.itemFactory.CompInfos[1].ID)
	col3 := arch.GetColumn(b.itemFactory.CompInfos[2].ID)
	col4 := arch.GetColumn(b.itemFactory.CompInfos[3].ID)
	col5 := arch.GetColumn(b.itemFactory.CompInfos[4].ID)
	remaining := count

	return func(yield func(struct {
		Entity []Entity
		Comp1 []T1
		Comp2 []T2
		Comp3 []T3
		Comp4 []T4
		Comp5 []T5
	}) bool) {
		pageIdx := core.PageIdx(len(memo.Pages) - 1)
		page := &memo.Pages[pageIdx]
		available := int(memo.Layout.PageCap) - int(page.Len)

		if available == 0 {
			pagesNeeded := (remaining + int(memo.Layout.PageCap) - 1) / int(memo.Layout.PageCap)
			memo.AddPages(pagesNeeded)
			pageIdx++
			page = &memo.Pages[pageIdx]
			available = int(memo.Layout.PageCap)
		} else {
			pagesNeeded := (remaining - available + int(memo.Layout.PageCap) - 1) / int(memo.Layout.PageCap)
			if pagesNeeded > 0 {
				memo.AddPages(pagesNeeded)
				page = &memo.Pages[pageIdx]
			}
		}

		for remaining > 0 {
			allocatedRows := min(remaining, available)
			startRow := page.Len
			page.Len += core.PageRow(allocatedRows)
			memo.Len += uint32(allocatedRows)

			for i := 0; i < allocatedRows; i++ {
				entity := reg.EntityPool.Next()
				pageRow := startRow + core.PageRow(i)
				destPtr := entityCol.GetPointer(page, pageRow)
				*(*Entity)(destPtr) = entity
				archReg.EntityLinkStore.Update(entity, b.itemFactory.ArchId, pageIdx, pageRow)
			}

			if !yield(
				struct {
					Entity []Entity
					Comp1 []T1
					Comp2 []T2
					Comp3 []T3
					Comp4 []T4
					Comp5 []T5
				}{
					Entity: unsafe.Slice((*Entity)(entityCol.GetPointer(page, startRow)), allocatedRows),
					Comp1: unsafe.Slice((*T1)(col1.GetPointer(page, startRow)), allocatedRows),
					Comp2: unsafe.Slice((*T2)(col2.GetPointer(page, startRow)), allocatedRows),
					Comp3: unsafe.Slice((*T3)(col3.GetPointer(page, startRow)), allocatedRows),
					Comp4: unsafe.Slice((*T4)(col4.GetPointer(page, startRow)), allocatedRows),
					Comp5: unsafe.Slice((*T5)(col5.GetPointer(page, startRow)), allocatedRows),
				}) {
				return
			}

			remaining -= allocatedRows
			if remaining > 0 {
				pageIdx++
				page = &memo.Pages[pageIdx]
				available = int(memo.Layout.PageCap)
			}
		}
	}
}
// Blueprint6 defines a static template (recipe) for the mass construction
// of entities with a predefined set of 6 stateful components. It allows
// for precise memory layout planning before allocation, which is essential
// for high-performance data access patterns.
//
// For example, a Blueprint6 could be used to define complex actors that
// require exactly 6 distinct data structures to be stored contiguously,
// ensuring optimal data locality and cache efficiency.
type Blueprint6[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any] struct {
    itemFactory *core.ItemFactory
}

// NewBlueprint6 initializes a new template for a specific combination of 6 components.
// It accepts optional BlueprintOptions (e.g., Include[Tag]()) to extend the
// template with any number of stateless components (Tags). Tags do not occupy
// space in the data columns but allow for precise population filtering within Views.
//
// By using a static definition, archetype metadata is registered once,
// enabling rapid entity spawning with minimal memory management overhead.
//
// This constructor panics if component registration fails or if there are
// configuration conflicts, ensuring a fail-fast behavior during system initialization.
func NewBlueprint6[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any](
    ecs *ECS,
    opts ...BlueprintOption,
) *Blueprint6[T1, T2, T3, T4, T5, T6] {
    registry := ecs.registry
    blueprint := core.NewBlueprint(registry)

    // mustAdd ensures that component registration and blueprint assignment
    // are successful. Panics immediately on failure to support fail-fast startup.
    mustAdd := func(info core.ComponentInfo) {
        if err := blueprint.WithComp(info); err != nil {
            panic(fmt.Sprintf("goke: blueprint6 init failed: %v", err))
        }
    }

    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T1]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T2]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T3]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T4]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T5]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T6]()))
    
    // Apply dynamic options (Tags, Exclusions) and panic on any configuration error.
    for _, opt := range opts {
        if err := opt(blueprint); err != nil {
            panic(fmt.Sprintf("goke: blueprint6 option failed: %v", err))
        }
    }

    return &Blueprint6[T1, T2, T3, T4, T5, T6]{
        itemFactory: core.NewItemFactory(blueprint),
    }
}

// BatchCreateX instantiates entities in bulk and returns an iterator yielding
// memory-aligned chunks for each component.
//
// Example:
//
//	for page := range blueprint.Create(100) {
//		for i, _ := range page.Entity {
//			batch.Comp1[1].X = 1
//			batch.Comp1[2].X = 1
//			batch.Comp1[3].X = 1
//			batch.Comp1[4].X = 1
//			batch.Comp1[5].X = 1
//			batch.Comp1[6].X = 1
//		}
//	}

func (b *Blueprint6[T1, T2, T3, T4, T5, T6]) Create(count int) iter.Seq[struct {
	Entity []Entity
	Comp1 []T1
	Comp2 []T2
	Comp3 []T3
	Comp4 []T4
	Comp5 []T5
	Comp6 []T6
}] {
	reg := b.itemFactory.Reg
	archReg := reg.ArchetypeRegistry
	arch := &archReg.Archetypes[b.itemFactory.ArchId]
	memo := &arch.Memory
	entityCol := &arch.Columns[core.EntityColumnIndex]
	col1 := arch.GetColumn(b.itemFactory.CompInfos[0].ID)
	col2 := arch.GetColumn(b.itemFactory.CompInfos[1].ID)
	col3 := arch.GetColumn(b.itemFactory.CompInfos[2].ID)
	col4 := arch.GetColumn(b.itemFactory.CompInfos[3].ID)
	col5 := arch.GetColumn(b.itemFactory.CompInfos[4].ID)
	col6 := arch.GetColumn(b.itemFactory.CompInfos[5].ID)
	remaining := count

	return func(yield func(struct {
		Entity []Entity
		Comp1 []T1
		Comp2 []T2
		Comp3 []T3
		Comp4 []T4
		Comp5 []T5
		Comp6 []T6
	}) bool) {
		pageIdx := core.PageIdx(len(memo.Pages) - 1)
		page := &memo.Pages[pageIdx]
		available := int(memo.Layout.PageCap) - int(page.Len)

		if available == 0 {
			pagesNeeded := (remaining + int(memo.Layout.PageCap) - 1) / int(memo.Layout.PageCap)
			memo.AddPages(pagesNeeded)
			pageIdx++
			page = &memo.Pages[pageIdx]
			available = int(memo.Layout.PageCap)
		} else {
			pagesNeeded := (remaining - available + int(memo.Layout.PageCap) - 1) / int(memo.Layout.PageCap)
			if pagesNeeded > 0 {
				memo.AddPages(pagesNeeded)
				page = &memo.Pages[pageIdx]
			}
		}

		for remaining > 0 {
			allocatedRows := min(remaining, available)
			startRow := page.Len
			page.Len += core.PageRow(allocatedRows)
			memo.Len += uint32(allocatedRows)

			for i := 0; i < allocatedRows; i++ {
				entity := reg.EntityPool.Next()
				pageRow := startRow + core.PageRow(i)
				destPtr := entityCol.GetPointer(page, pageRow)
				*(*Entity)(destPtr) = entity
				archReg.EntityLinkStore.Update(entity, b.itemFactory.ArchId, pageIdx, pageRow)
			}

			if !yield(
				struct {
					Entity []Entity
					Comp1 []T1
					Comp2 []T2
					Comp3 []T3
					Comp4 []T4
					Comp5 []T5
					Comp6 []T6
				}{
					Entity: unsafe.Slice((*Entity)(entityCol.GetPointer(page, startRow)), allocatedRows),
					Comp1: unsafe.Slice((*T1)(col1.GetPointer(page, startRow)), allocatedRows),
					Comp2: unsafe.Slice((*T2)(col2.GetPointer(page, startRow)), allocatedRows),
					Comp3: unsafe.Slice((*T3)(col3.GetPointer(page, startRow)), allocatedRows),
					Comp4: unsafe.Slice((*T4)(col4.GetPointer(page, startRow)), allocatedRows),
					Comp5: unsafe.Slice((*T5)(col5.GetPointer(page, startRow)), allocatedRows),
					Comp6: unsafe.Slice((*T6)(col6.GetPointer(page, startRow)), allocatedRows),
				}) {
				return
			}

			remaining -= allocatedRows
			if remaining > 0 {
				pageIdx++
				page = &memo.Pages[pageIdx]
				available = int(memo.Layout.PageCap)
			}
		}
	}
}
// Blueprint7 defines a static template (recipe) for the mass construction
// of entities with a predefined set of 7 stateful components. It allows
// for precise memory layout planning before allocation, which is essential
// for high-performance data access patterns.
//
// For example, a Blueprint7 could be used to define complex actors that
// require exactly 7 distinct data structures to be stored contiguously,
// ensuring optimal data locality and cache efficiency.
type Blueprint7[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any] struct {
    itemFactory *core.ItemFactory
}

// NewBlueprint7 initializes a new template for a specific combination of 7 components.
// It accepts optional BlueprintOptions (e.g., Include[Tag]()) to extend the
// template with any number of stateless components (Tags). Tags do not occupy
// space in the data columns but allow for precise population filtering within Views.
//
// By using a static definition, archetype metadata is registered once,
// enabling rapid entity spawning with minimal memory management overhead.
//
// This constructor panics if component registration fails or if there are
// configuration conflicts, ensuring a fail-fast behavior during system initialization.
func NewBlueprint7[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any](
    ecs *ECS,
    opts ...BlueprintOption,
) *Blueprint7[T1, T2, T3, T4, T5, T6, T7] {
    registry := ecs.registry
    blueprint := core.NewBlueprint(registry)

    // mustAdd ensures that component registration and blueprint assignment
    // are successful. Panics immediately on failure to support fail-fast startup.
    mustAdd := func(info core.ComponentInfo) {
        if err := blueprint.WithComp(info); err != nil {
            panic(fmt.Sprintf("goke: blueprint7 init failed: %v", err))
        }
    }

    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T1]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T2]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T3]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T4]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T5]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T6]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T7]()))
    
    // Apply dynamic options (Tags, Exclusions) and panic on any configuration error.
    for _, opt := range opts {
        if err := opt(blueprint); err != nil {
            panic(fmt.Sprintf("goke: blueprint7 option failed: %v", err))
        }
    }

    return &Blueprint7[T1, T2, T3, T4, T5, T6, T7]{
        itemFactory: core.NewItemFactory(blueprint),
    }
}

// BatchCreateX instantiates entities in bulk and returns an iterator yielding
// memory-aligned chunks for each component.
//
// Example:
//
//	for page := range blueprint.Create(100) {
//		for i, _ := range page.Entity {
//			batch.Comp1[1].X = 1
//			batch.Comp1[2].X = 1
//			batch.Comp1[3].X = 1
//			batch.Comp1[4].X = 1
//			batch.Comp1[5].X = 1
//			batch.Comp1[6].X = 1
//			batch.Comp1[7].X = 1
//		}
//	}

func (b *Blueprint7[T1, T2, T3, T4, T5, T6, T7]) Create(count int) iter.Seq[struct {
	Entity []Entity
	Comp1 []T1
	Comp2 []T2
	Comp3 []T3
	Comp4 []T4
	Comp5 []T5
	Comp6 []T6
	Comp7 []T7
}] {
	reg := b.itemFactory.Reg
	archReg := reg.ArchetypeRegistry
	arch := &archReg.Archetypes[b.itemFactory.ArchId]
	memo := &arch.Memory
	entityCol := &arch.Columns[core.EntityColumnIndex]
	col1 := arch.GetColumn(b.itemFactory.CompInfos[0].ID)
	col2 := arch.GetColumn(b.itemFactory.CompInfos[1].ID)
	col3 := arch.GetColumn(b.itemFactory.CompInfos[2].ID)
	col4 := arch.GetColumn(b.itemFactory.CompInfos[3].ID)
	col5 := arch.GetColumn(b.itemFactory.CompInfos[4].ID)
	col6 := arch.GetColumn(b.itemFactory.CompInfos[5].ID)
	col7 := arch.GetColumn(b.itemFactory.CompInfos[6].ID)
	remaining := count

	return func(yield func(struct {
		Entity []Entity
		Comp1 []T1
		Comp2 []T2
		Comp3 []T3
		Comp4 []T4
		Comp5 []T5
		Comp6 []T6
		Comp7 []T7
	}) bool) {
		pageIdx := core.PageIdx(len(memo.Pages) - 1)
		page := &memo.Pages[pageIdx]
		available := int(memo.Layout.PageCap) - int(page.Len)

		if available == 0 {
			pagesNeeded := (remaining + int(memo.Layout.PageCap) - 1) / int(memo.Layout.PageCap)
			memo.AddPages(pagesNeeded)
			pageIdx++
			page = &memo.Pages[pageIdx]
			available = int(memo.Layout.PageCap)
		} else {
			pagesNeeded := (remaining - available + int(memo.Layout.PageCap) - 1) / int(memo.Layout.PageCap)
			if pagesNeeded > 0 {
				memo.AddPages(pagesNeeded)
				page = &memo.Pages[pageIdx]
			}
		}

		for remaining > 0 {
			allocatedRows := min(remaining, available)
			startRow := page.Len
			page.Len += core.PageRow(allocatedRows)
			memo.Len += uint32(allocatedRows)

			for i := 0; i < allocatedRows; i++ {
				entity := reg.EntityPool.Next()
				pageRow := startRow + core.PageRow(i)
				destPtr := entityCol.GetPointer(page, pageRow)
				*(*Entity)(destPtr) = entity
				archReg.EntityLinkStore.Update(entity, b.itemFactory.ArchId, pageIdx, pageRow)
			}

			if !yield(
				struct {
					Entity []Entity
					Comp1 []T1
					Comp2 []T2
					Comp3 []T3
					Comp4 []T4
					Comp5 []T5
					Comp6 []T6
					Comp7 []T7
				}{
					Entity: unsafe.Slice((*Entity)(entityCol.GetPointer(page, startRow)), allocatedRows),
					Comp1: unsafe.Slice((*T1)(col1.GetPointer(page, startRow)), allocatedRows),
					Comp2: unsafe.Slice((*T2)(col2.GetPointer(page, startRow)), allocatedRows),
					Comp3: unsafe.Slice((*T3)(col3.GetPointer(page, startRow)), allocatedRows),
					Comp4: unsafe.Slice((*T4)(col4.GetPointer(page, startRow)), allocatedRows),
					Comp5: unsafe.Slice((*T5)(col5.GetPointer(page, startRow)), allocatedRows),
					Comp6: unsafe.Slice((*T6)(col6.GetPointer(page, startRow)), allocatedRows),
					Comp7: unsafe.Slice((*T7)(col7.GetPointer(page, startRow)), allocatedRows),
				}) {
				return
			}

			remaining -= allocatedRows
			if remaining > 0 {
				pageIdx++
				page = &memo.Pages[pageIdx]
				available = int(memo.Layout.PageCap)
			}
		}
	}
}
// Blueprint8 defines a static template (recipe) for the mass construction
// of entities with a predefined set of 8 stateful components. It allows
// for precise memory layout planning before allocation, which is essential
// for high-performance data access patterns.
//
// For example, a Blueprint8 could be used to define complex actors that
// require exactly 8 distinct data structures to be stored contiguously,
// ensuring optimal data locality and cache efficiency.
type Blueprint8[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any, T8 any] struct {
    itemFactory *core.ItemFactory
}

// NewBlueprint8 initializes a new template for a specific combination of 8 components.
// It accepts optional BlueprintOptions (e.g., Include[Tag]()) to extend the
// template with any number of stateless components (Tags). Tags do not occupy
// space in the data columns but allow for precise population filtering within Views.
//
// By using a static definition, archetype metadata is registered once,
// enabling rapid entity spawning with minimal memory management overhead.
//
// This constructor panics if component registration fails or if there are
// configuration conflicts, ensuring a fail-fast behavior during system initialization.
func NewBlueprint8[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any, T8 any](
    ecs *ECS,
    opts ...BlueprintOption,
) *Blueprint8[T1, T2, T3, T4, T5, T6, T7, T8] {
    registry := ecs.registry
    blueprint := core.NewBlueprint(registry)

    // mustAdd ensures that component registration and blueprint assignment
    // are successful. Panics immediately on failure to support fail-fast startup.
    mustAdd := func(info core.ComponentInfo) {
        if err := blueprint.WithComp(info); err != nil {
            panic(fmt.Sprintf("goke: blueprint8 init failed: %v", err))
        }
    }

    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T1]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T2]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T3]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T4]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T5]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T6]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T7]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T8]()))
    
    // Apply dynamic options (Tags, Exclusions) and panic on any configuration error.
    for _, opt := range opts {
        if err := opt(blueprint); err != nil {
            panic(fmt.Sprintf("goke: blueprint8 option failed: %v", err))
        }
    }

    return &Blueprint8[T1, T2, T3, T4, T5, T6, T7, T8]{
        itemFactory: core.NewItemFactory(blueprint),
    }
}

// BatchCreateX instantiates entities in bulk and returns an iterator yielding
// memory-aligned chunks for each component.
//
// Example:
//
//	for page := range blueprint.Create(100) {
//		for i, _ := range page.Entity {
//			batch.Comp1[1].X = 1
//			batch.Comp1[2].X = 1
//			batch.Comp1[3].X = 1
//			batch.Comp1[4].X = 1
//			batch.Comp1[5].X = 1
//			batch.Comp1[6].X = 1
//			batch.Comp1[7].X = 1
//			batch.Comp1[8].X = 1
//		}
//	}

func (b *Blueprint8[T1, T2, T3, T4, T5, T6, T7, T8]) Create(count int) iter.Seq[struct {
	Entity []Entity
	Comp1 []T1
	Comp2 []T2
	Comp3 []T3
	Comp4 []T4
	Comp5 []T5
	Comp6 []T6
	Comp7 []T7
	Comp8 []T8
}] {
	reg := b.itemFactory.Reg
	archReg := reg.ArchetypeRegistry
	arch := &archReg.Archetypes[b.itemFactory.ArchId]
	memo := &arch.Memory
	entityCol := &arch.Columns[core.EntityColumnIndex]
	col1 := arch.GetColumn(b.itemFactory.CompInfos[0].ID)
	col2 := arch.GetColumn(b.itemFactory.CompInfos[1].ID)
	col3 := arch.GetColumn(b.itemFactory.CompInfos[2].ID)
	col4 := arch.GetColumn(b.itemFactory.CompInfos[3].ID)
	col5 := arch.GetColumn(b.itemFactory.CompInfos[4].ID)
	col6 := arch.GetColumn(b.itemFactory.CompInfos[5].ID)
	col7 := arch.GetColumn(b.itemFactory.CompInfos[6].ID)
	col8 := arch.GetColumn(b.itemFactory.CompInfos[7].ID)
	remaining := count

	return func(yield func(struct {
		Entity []Entity
		Comp1 []T1
		Comp2 []T2
		Comp3 []T3
		Comp4 []T4
		Comp5 []T5
		Comp6 []T6
		Comp7 []T7
		Comp8 []T8
	}) bool) {
		pageIdx := core.PageIdx(len(memo.Pages) - 1)
		page := &memo.Pages[pageIdx]
		available := int(memo.Layout.PageCap) - int(page.Len)

		if available == 0 {
			pagesNeeded := (remaining + int(memo.Layout.PageCap) - 1) / int(memo.Layout.PageCap)
			memo.AddPages(pagesNeeded)
			pageIdx++
			page = &memo.Pages[pageIdx]
			available = int(memo.Layout.PageCap)
		} else {
			pagesNeeded := (remaining - available + int(memo.Layout.PageCap) - 1) / int(memo.Layout.PageCap)
			if pagesNeeded > 0 {
				memo.AddPages(pagesNeeded)
				page = &memo.Pages[pageIdx]
			}
		}

		for remaining > 0 {
			allocatedRows := min(remaining, available)
			startRow := page.Len
			page.Len += core.PageRow(allocatedRows)
			memo.Len += uint32(allocatedRows)

			for i := 0; i < allocatedRows; i++ {
				entity := reg.EntityPool.Next()
				pageRow := startRow + core.PageRow(i)
				destPtr := entityCol.GetPointer(page, pageRow)
				*(*Entity)(destPtr) = entity
				archReg.EntityLinkStore.Update(entity, b.itemFactory.ArchId, pageIdx, pageRow)
			}

			if !yield(
				struct {
					Entity []Entity
					Comp1 []T1
					Comp2 []T2
					Comp3 []T3
					Comp4 []T4
					Comp5 []T5
					Comp6 []T6
					Comp7 []T7
					Comp8 []T8
				}{
					Entity: unsafe.Slice((*Entity)(entityCol.GetPointer(page, startRow)), allocatedRows),
					Comp1: unsafe.Slice((*T1)(col1.GetPointer(page, startRow)), allocatedRows),
					Comp2: unsafe.Slice((*T2)(col2.GetPointer(page, startRow)), allocatedRows),
					Comp3: unsafe.Slice((*T3)(col3.GetPointer(page, startRow)), allocatedRows),
					Comp4: unsafe.Slice((*T4)(col4.GetPointer(page, startRow)), allocatedRows),
					Comp5: unsafe.Slice((*T5)(col5.GetPointer(page, startRow)), allocatedRows),
					Comp6: unsafe.Slice((*T6)(col6.GetPointer(page, startRow)), allocatedRows),
					Comp7: unsafe.Slice((*T7)(col7.GetPointer(page, startRow)), allocatedRows),
					Comp8: unsafe.Slice((*T8)(col8.GetPointer(page, startRow)), allocatedRows),
				}) {
				return
			}

			remaining -= allocatedRows
			if remaining > 0 {
				pageIdx++
				page = &memo.Pages[pageIdx]
				available = int(memo.Layout.PageCap)
			}
		}
	}
}
// Blueprint9 defines a static template (recipe) for the mass construction
// of entities with a predefined set of 9 stateful components. It allows
// for precise memory layout planning before allocation, which is essential
// for high-performance data access patterns.
//
// For example, a Blueprint9 could be used to define complex actors that
// require exactly 9 distinct data structures to be stored contiguously,
// ensuring optimal data locality and cache efficiency.
type Blueprint9[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any, T8 any, T9 any] struct {
    itemFactory *core.ItemFactory
}

// NewBlueprint9 initializes a new template for a specific combination of 9 components.
// It accepts optional BlueprintOptions (e.g., Include[Tag]()) to extend the
// template with any number of stateless components (Tags). Tags do not occupy
// space in the data columns but allow for precise population filtering within Views.
//
// By using a static definition, archetype metadata is registered once,
// enabling rapid entity spawning with minimal memory management overhead.
//
// This constructor panics if component registration fails or if there are
// configuration conflicts, ensuring a fail-fast behavior during system initialization.
func NewBlueprint9[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any, T8 any, T9 any](
    ecs *ECS,
    opts ...BlueprintOption,
) *Blueprint9[T1, T2, T3, T4, T5, T6, T7, T8, T9] {
    registry := ecs.registry
    blueprint := core.NewBlueprint(registry)

    // mustAdd ensures that component registration and blueprint assignment
    // are successful. Panics immediately on failure to support fail-fast startup.
    mustAdd := func(info core.ComponentInfo) {
        if err := blueprint.WithComp(info); err != nil {
            panic(fmt.Sprintf("goke: blueprint9 init failed: %v", err))
        }
    }

    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T1]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T2]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T3]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T4]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T5]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T6]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T7]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T8]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T9]()))
    
    // Apply dynamic options (Tags, Exclusions) and panic on any configuration error.
    for _, opt := range opts {
        if err := opt(blueprint); err != nil {
            panic(fmt.Sprintf("goke: blueprint9 option failed: %v", err))
        }
    }

    return &Blueprint9[T1, T2, T3, T4, T5, T6, T7, T8, T9]{
        itemFactory: core.NewItemFactory(blueprint),
    }
}

// BatchCreateX instantiates entities in bulk and returns an iterator yielding
// memory-aligned chunks for each component.
//
// Example:
//
//	for page := range blueprint.Create(100) {
//		for i, _ := range page.Entity {
//			batch.Comp1[1].X = 1
//			batch.Comp1[2].X = 1
//			batch.Comp1[3].X = 1
//			batch.Comp1[4].X = 1
//			batch.Comp1[5].X = 1
//			batch.Comp1[6].X = 1
//			batch.Comp1[7].X = 1
//			batch.Comp1[8].X = 1
//			batch.Comp1[9].X = 1
//		}
//	}

func (b *Blueprint9[T1, T2, T3, T4, T5, T6, T7, T8, T9]) Create(count int) iter.Seq[struct {
	Entity []Entity
	Comp1 []T1
	Comp2 []T2
	Comp3 []T3
	Comp4 []T4
	Comp5 []T5
	Comp6 []T6
	Comp7 []T7
	Comp8 []T8
	Comp9 []T9
}] {
	reg := b.itemFactory.Reg
	archReg := reg.ArchetypeRegistry
	arch := &archReg.Archetypes[b.itemFactory.ArchId]
	memo := &arch.Memory
	entityCol := &arch.Columns[core.EntityColumnIndex]
	col1 := arch.GetColumn(b.itemFactory.CompInfos[0].ID)
	col2 := arch.GetColumn(b.itemFactory.CompInfos[1].ID)
	col3 := arch.GetColumn(b.itemFactory.CompInfos[2].ID)
	col4 := arch.GetColumn(b.itemFactory.CompInfos[3].ID)
	col5 := arch.GetColumn(b.itemFactory.CompInfos[4].ID)
	col6 := arch.GetColumn(b.itemFactory.CompInfos[5].ID)
	col7 := arch.GetColumn(b.itemFactory.CompInfos[6].ID)
	col8 := arch.GetColumn(b.itemFactory.CompInfos[7].ID)
	col9 := arch.GetColumn(b.itemFactory.CompInfos[8].ID)
	remaining := count

	return func(yield func(struct {
		Entity []Entity
		Comp1 []T1
		Comp2 []T2
		Comp3 []T3
		Comp4 []T4
		Comp5 []T5
		Comp6 []T6
		Comp7 []T7
		Comp8 []T8
		Comp9 []T9
	}) bool) {
		pageIdx := core.PageIdx(len(memo.Pages) - 1)
		page := &memo.Pages[pageIdx]
		available := int(memo.Layout.PageCap) - int(page.Len)

		if available == 0 {
			pagesNeeded := (remaining + int(memo.Layout.PageCap) - 1) / int(memo.Layout.PageCap)
			memo.AddPages(pagesNeeded)
			pageIdx++
			page = &memo.Pages[pageIdx]
			available = int(memo.Layout.PageCap)
		} else {
			pagesNeeded := (remaining - available + int(memo.Layout.PageCap) - 1) / int(memo.Layout.PageCap)
			if pagesNeeded > 0 {
				memo.AddPages(pagesNeeded)
				page = &memo.Pages[pageIdx]
			}
		}

		for remaining > 0 {
			allocatedRows := min(remaining, available)
			startRow := page.Len
			page.Len += core.PageRow(allocatedRows)
			memo.Len += uint32(allocatedRows)

			for i := 0; i < allocatedRows; i++ {
				entity := reg.EntityPool.Next()
				pageRow := startRow + core.PageRow(i)
				destPtr := entityCol.GetPointer(page, pageRow)
				*(*Entity)(destPtr) = entity
				archReg.EntityLinkStore.Update(entity, b.itemFactory.ArchId, pageIdx, pageRow)
			}

			if !yield(
				struct {
					Entity []Entity
					Comp1 []T1
					Comp2 []T2
					Comp3 []T3
					Comp4 []T4
					Comp5 []T5
					Comp6 []T6
					Comp7 []T7
					Comp8 []T8
					Comp9 []T9
				}{
					Entity: unsafe.Slice((*Entity)(entityCol.GetPointer(page, startRow)), allocatedRows),
					Comp1: unsafe.Slice((*T1)(col1.GetPointer(page, startRow)), allocatedRows),
					Comp2: unsafe.Slice((*T2)(col2.GetPointer(page, startRow)), allocatedRows),
					Comp3: unsafe.Slice((*T3)(col3.GetPointer(page, startRow)), allocatedRows),
					Comp4: unsafe.Slice((*T4)(col4.GetPointer(page, startRow)), allocatedRows),
					Comp5: unsafe.Slice((*T5)(col5.GetPointer(page, startRow)), allocatedRows),
					Comp6: unsafe.Slice((*T6)(col6.GetPointer(page, startRow)), allocatedRows),
					Comp7: unsafe.Slice((*T7)(col7.GetPointer(page, startRow)), allocatedRows),
					Comp8: unsafe.Slice((*T8)(col8.GetPointer(page, startRow)), allocatedRows),
					Comp9: unsafe.Slice((*T9)(col9.GetPointer(page, startRow)), allocatedRows),
				}) {
				return
			}

			remaining -= allocatedRows
			if remaining > 0 {
				pageIdx++
				page = &memo.Pages[pageIdx]
				available = int(memo.Layout.PageCap)
			}
		}
	}
}
// Blueprint10 defines a static template (recipe) for the mass construction
// of entities with a predefined set of 10 stateful components. It allows
// for precise memory layout planning before allocation, which is essential
// for high-performance data access patterns.
//
// For example, a Blueprint10 could be used to define complex actors that
// require exactly 10 distinct data structures to be stored contiguously,
// ensuring optimal data locality and cache efficiency.
type Blueprint10[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any, T8 any, T9 any, T10 any] struct {
    itemFactory *core.ItemFactory
}

// NewBlueprint10 initializes a new template for a specific combination of 10 components.
// It accepts optional BlueprintOptions (e.g., Include[Tag]()) to extend the
// template with any number of stateless components (Tags). Tags do not occupy
// space in the data columns but allow for precise population filtering within Views.
//
// By using a static definition, archetype metadata is registered once,
// enabling rapid entity spawning with minimal memory management overhead.
//
// This constructor panics if component registration fails or if there are
// configuration conflicts, ensuring a fail-fast behavior during system initialization.
func NewBlueprint10[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any, T8 any, T9 any, T10 any](
    ecs *ECS,
    opts ...BlueprintOption,
) *Blueprint10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10] {
    registry := ecs.registry
    blueprint := core.NewBlueprint(registry)

    // mustAdd ensures that component registration and blueprint assignment
    // are successful. Panics immediately on failure to support fail-fast startup.
    mustAdd := func(info core.ComponentInfo) {
        if err := blueprint.WithComp(info); err != nil {
            panic(fmt.Sprintf("goke: blueprint10 init failed: %v", err))
        }
    }

    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T1]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T2]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T3]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T4]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T5]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T6]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T7]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T8]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T9]()))
    mustAdd(registry.ComponentsRegistry.GetOrRegister(reflect.TypeFor[T10]()))
    
    // Apply dynamic options (Tags, Exclusions) and panic on any configuration error.
    for _, opt := range opts {
        if err := opt(blueprint); err != nil {
            panic(fmt.Sprintf("goke: blueprint10 option failed: %v", err))
        }
    }

    return &Blueprint10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]{
        itemFactory: core.NewItemFactory(blueprint),
    }
}

// BatchCreateX instantiates entities in bulk and returns an iterator yielding
// memory-aligned chunks for each component.
//
// Example:
//
//	for page := range blueprint.Create(100) {
//		for i, _ := range page.Entity {
//			batch.Comp1[1].X = 1
//			batch.Comp1[2].X = 1
//			batch.Comp1[3].X = 1
//			batch.Comp1[4].X = 1
//			batch.Comp1[5].X = 1
//			batch.Comp1[6].X = 1
//			batch.Comp1[7].X = 1
//			batch.Comp1[8].X = 1
//			batch.Comp1[9].X = 1
//			batch.Comp1[10].X = 1
//		}
//	}

func (b *Blueprint10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]) Create(count int) iter.Seq[struct {
	Entity []Entity
	Comp1 []T1
	Comp2 []T2
	Comp3 []T3
	Comp4 []T4
	Comp5 []T5
	Comp6 []T6
	Comp7 []T7
	Comp8 []T8
	Comp9 []T9
	Comp10 []T10
}] {
	reg := b.itemFactory.Reg
	archReg := reg.ArchetypeRegistry
	arch := &archReg.Archetypes[b.itemFactory.ArchId]
	memo := &arch.Memory
	entityCol := &arch.Columns[core.EntityColumnIndex]
	col1 := arch.GetColumn(b.itemFactory.CompInfos[0].ID)
	col2 := arch.GetColumn(b.itemFactory.CompInfos[1].ID)
	col3 := arch.GetColumn(b.itemFactory.CompInfos[2].ID)
	col4 := arch.GetColumn(b.itemFactory.CompInfos[3].ID)
	col5 := arch.GetColumn(b.itemFactory.CompInfos[4].ID)
	col6 := arch.GetColumn(b.itemFactory.CompInfos[5].ID)
	col7 := arch.GetColumn(b.itemFactory.CompInfos[6].ID)
	col8 := arch.GetColumn(b.itemFactory.CompInfos[7].ID)
	col9 := arch.GetColumn(b.itemFactory.CompInfos[8].ID)
	col10 := arch.GetColumn(b.itemFactory.CompInfos[9].ID)
	remaining := count

	return func(yield func(struct {
		Entity []Entity
		Comp1 []T1
		Comp2 []T2
		Comp3 []T3
		Comp4 []T4
		Comp5 []T5
		Comp6 []T6
		Comp7 []T7
		Comp8 []T8
		Comp9 []T9
		Comp10 []T10
	}) bool) {
		pageIdx := core.PageIdx(len(memo.Pages) - 1)
		page := &memo.Pages[pageIdx]
		available := int(memo.Layout.PageCap) - int(page.Len)

		if available == 0 {
			pagesNeeded := (remaining + int(memo.Layout.PageCap) - 1) / int(memo.Layout.PageCap)
			memo.AddPages(pagesNeeded)
			pageIdx++
			page = &memo.Pages[pageIdx]
			available = int(memo.Layout.PageCap)
		} else {
			pagesNeeded := (remaining - available + int(memo.Layout.PageCap) - 1) / int(memo.Layout.PageCap)
			if pagesNeeded > 0 {
				memo.AddPages(pagesNeeded)
				page = &memo.Pages[pageIdx]
			}
		}

		for remaining > 0 {
			allocatedRows := min(remaining, available)
			startRow := page.Len
			page.Len += core.PageRow(allocatedRows)
			memo.Len += uint32(allocatedRows)

			for i := 0; i < allocatedRows; i++ {
				entity := reg.EntityPool.Next()
				pageRow := startRow + core.PageRow(i)
				destPtr := entityCol.GetPointer(page, pageRow)
				*(*Entity)(destPtr) = entity
				archReg.EntityLinkStore.Update(entity, b.itemFactory.ArchId, pageIdx, pageRow)
			}

			if !yield(
				struct {
					Entity []Entity
					Comp1 []T1
					Comp2 []T2
					Comp3 []T3
					Comp4 []T4
					Comp5 []T5
					Comp6 []T6
					Comp7 []T7
					Comp8 []T8
					Comp9 []T9
					Comp10 []T10
				}{
					Entity: unsafe.Slice((*Entity)(entityCol.GetPointer(page, startRow)), allocatedRows),
					Comp1: unsafe.Slice((*T1)(col1.GetPointer(page, startRow)), allocatedRows),
					Comp2: unsafe.Slice((*T2)(col2.GetPointer(page, startRow)), allocatedRows),
					Comp3: unsafe.Slice((*T3)(col3.GetPointer(page, startRow)), allocatedRows),
					Comp4: unsafe.Slice((*T4)(col4.GetPointer(page, startRow)), allocatedRows),
					Comp5: unsafe.Slice((*T5)(col5.GetPointer(page, startRow)), allocatedRows),
					Comp6: unsafe.Slice((*T6)(col6.GetPointer(page, startRow)), allocatedRows),
					Comp7: unsafe.Slice((*T7)(col7.GetPointer(page, startRow)), allocatedRows),
					Comp8: unsafe.Slice((*T8)(col8.GetPointer(page, startRow)), allocatedRows),
					Comp9: unsafe.Slice((*T9)(col9.GetPointer(page, startRow)), allocatedRows),
					Comp10: unsafe.Slice((*T10)(col10.GetPointer(page, startRow)), allocatedRows),
				}) {
				return
			}

			remaining -= allocatedRows
			if remaining > 0 {
				pageIdx++
				page = &memo.Pages[pageIdx]
				available = int(memo.Layout.PageCap)
			}
		}
	}
}

