// Code generated by github.com/kjkrol/goke/internal/cmd/gen/views; DO NOT EDIT.
package goke

import (
	"fmt"
	"github.com/kjkrol/goke/internal/core"
	"iter"
	"unsafe"
)

// --------------- View1 ---------------

// View1 provides a type-safe iterator and access layer for entities that
// possess exactly 1 specific stateful components. It acts as a specialized
// window into the ECS world, filtering archetypes that satisfy the required
// component mask and any additional constraints defined via BlueprintOptions.
//
// By leveraging pre-calculated component offsets, View1 enables
// O(1) access to component data during iteration, making it the primary
// tool for implementing high-performance systems and logic loops.
type View1[T1 any] struct {
	*core.View
}

// NewView1 initializes a query for exactly 1 components.
// It panics if the component registration fails, if there are duplicate
// components, or if options (like Exclude) create a logical contradiction.
//
// This ensures that the View is valid and ready for high-performance
// iteration immediately after creation.
func NewView1[T1 any](ecs *ECS, opts ...BlueprintOption) *View1[T1] {
	registry := ecs.registry
	blueprint := core.NewBlueprint(registry)
	componentsRegistry := &registry.ComponentsRegistry

	// Helper: Validates that the required component can be part of the view.
	mustAdd := func(info core.ComponentInfo) {
		if err := blueprint.WithComp(info); err != nil {
			panic(fmt.Sprintf("goke: view1 init failed: %v", err))
		}
	}

	// 1. Resolve Component Infos (Type -> ID)

	info1 := core.EnsureComponentRegistered[T1](componentsRegistry)

	// 2. Add to Blueprint (Build Mask)

	mustAdd(info1)

	// 3. Apply dynamic options (Include/Exclude)
	for _, opt := range opts {
		if err := opt(blueprint); err != nil {
			panic(fmt.Sprintf("goke: view1 option failed: %v", err))
		}
	}

	// 4. Define Rigid Layout (Slice Literal - Zero Allocation Overhead)
	// This guarantees that T1 is at index 0, T2 at index 1, etc.
	layout := []core.ComponentInfo{
		info1,
	}

	view := core.NewView(blueprint, layout, registry)
	return &View1[T1]{View: view}
}

// All returns an iterator (iter.Seq2) that yields the unique Entity identifier
// and a tuple of pointers to its 1 components. This is designed for use
// in range loops, providing a clean, idiomatic Go way to process data while
// maintaining maximum cache efficiency.
//
// The iteration is performed archetype by archetype, ensuring that data is
// accessed contiguously in memory, which significantly reduces CPU cache misses.
//
// Example usage:
//
//	for head, _ := range view1.All() {
//	    entity := head.Entity
//	    v1 := head.V1
//
//	}
func (v *View1[T1]) All() iter.Seq2[
	struct {
		Entity core.Entity
		V1     *T1
	},
	struct{},
] {
	return func(yield func(
		struct {
			Entity core.Entity
			V1     *T1
		},
		struct{},
	) bool) {
		const strideEntity = unsafe.Sizeof(core.Entity(0))
		s1 := unsafe.Sizeof(*new(T1))

		for _, b := range v.Baked {

			// 1. Setup Entity Pointer
			pEntity := b.GetEntityColumn().Data

			// 2. Setup Component Pointers
			p1 := b.GetColumn(0).Data

			n := b.Arch.Len()
			// Death Loop (Pointer Arithmetic)
			for n > 0 {

				// Construct Head
				head := struct {
					Entity core.Entity
					V1     *T1
				}{
					Entity: *(*core.Entity)(pEntity), V1: (*T1)(p1),
				}

				// Construct Tail

				tail := struct{}{}

				if !yield(head, tail) {
					return
				}

				// Increment Pointers
				pEntity = unsafe.Add(pEntity, strideEntity)
				p1 = unsafe.Add(p1, s1)

				n--
			}
		}
	}
}

// Filter returns an iterator (iter.Seq2) that yields only the entities
// specified in the selected slice, provided they match the View's archetype
// constraints. It is optimized for scenarios where a subset of entities
// is pre-determined (e.g., via spatial partitioning or sorted results)
// but requires high-speed access to their component data.
//
// The iterator performs an internal validation for each entity to ensure
// it still belongs to an archetype compatible with this View, preventing
// invalid memory access if the entity's composition has changed.
//
// Example usage:
//
//	selected := []Entity{e1, e5, e10}
//	for head, _ := range view1.Filter(selected) {
//	    entity := head.Entity
//	    v1 := head.V1
//
//	}
func (v *View1[T1]) Filter(selected []Entity) iter.Seq2[
	struct {
		Entity Entity
		V1     *T1
	},
	struct{},
] {
	return func(yield func(
		struct {
			Entity Entity
			V1     *T1
		},
		struct{},
	) bool) {
		stride1 := unsafe.Sizeof(*new(T1))

		var ptr1 unsafe.Pointer
		var lastArchID int32 = -1
		registry := v.Reg.ArchetypeRegistry
		col1ID := v.Layout[0].ID

		for _, e := range selected {
			link, ok := registry.EntityLinkStore.Get(e)
			if !ok {
				continue
			}

			if int32(link.ArchId) != lastArchID {
				arch := &registry.Archetypes[link.ArchId]
				if !v.View.Matches(arch.Mask) {
					lastArchID = -1
					continue
				}

				ptr1 = arch.GetColumn(col1ID).Data

				lastArchID = int32(link.ArchId)
			}

			row := uintptr(link.Row)

			head := struct {
				Entity Entity
				V1     *T1
			}{
				Entity: e, V1: (*T1)(unsafe.Add(ptr1, row*stride1)),
			}

			tail := struct{}{}

			if !yield(head, tail) {
				return
			}
		}
	}
}

// Values returns a performance-critical iterator (iter.Seq2) that yields only
// component pointers, grouped into anonymous head and tail structures.
// This method is specifically designed for high-throughput data processing
// where the Entity identifier is not required.
//
// By omitting the Entity ID, this method minimizes stack pressure and
// register usage, focusing purely on data-driven transformation.
//
// Example usage:
//
//	for head, _ := range view1.Values() {
//	    v1 := head.V1
//
//
//	}
func (v *View1[T1]) Values() iter.Seq2[
	struct{ V1 *T1 },
	struct{},
] {
	return func(yield func(
		struct{ V1 *T1 },
		struct{},
	) bool) {
		// Calculate strides for types
		s1 := unsafe.Sizeof(*new(T1))

		for _, b := range v.Baked {

			// Setup Component Pointers
			p1 := b.GetColumn(0).Data

			n := b.Arch.Len()

			// Death Loop (Pointer Arithmetic)
			for n > 0 {

				// Construct Head
				head := struct{ V1 *T1 }{V1: (*T1)(p1)}

				// Construct Tail

				tail := struct{}{}

				if !yield(head, tail) {
					return
				}

				// Increment Pointers
				p1 = unsafe.Add(p1, s1)

				n--
			}
		}
	}
}

// FilterValues returns an iterator (iter.Seq2) that yields component pointers
// for a pre-selected subset of entities, skipping the Entity identifier.
// It is optimized for cases where the entity list is already known (e.g., from spatial partitioning).
//
// Like the Values method, it uses anonymous structures to ensure the Go compiler
// can perform aggressive register allocation by avoiding Entity ID overhead.
//
// Example usage:
//
//	selected := []Entity{e1, e5, e10}
//	for head, _ := range view1.FilterValues(selected) {
//	    v1 := head.V1
//
//
//	}
func (v *View1[T1]) FilterValues(selected []Entity) iter.Seq2[
	struct{ V1 *T1 },
	struct{},
] {
	return func(yield func(
		struct{ V1 *T1 },
		struct{},
	) bool) {
		stride1 := unsafe.Sizeof(*new(T1))

		var ptr1 unsafe.Pointer
		var lastArchID int32 = -1
		registry := v.Reg.ArchetypeRegistry
		col1ID := v.Layout[0].ID

		for _, e := range selected {
			link, ok := registry.EntityLinkStore.Get(e)
			if !ok {
				continue
			}

			if int32(link.ArchId) != lastArchID {
				arch := &registry.Archetypes[link.ArchId]
				if !v.View.Matches(arch.Mask) {
					lastArchID = -1
					continue
				}

				ptr1 = arch.GetColumn(col1ID).Data

				lastArchID = int32(link.ArchId)
			}

			row := uintptr(link.Row)

			vhead := struct{ V1 *T1 }{V1: (*T1)(unsafe.Add(ptr1, row*stride1))}

			vtail := struct{}{}

			if !yield(vhead, vtail) {
				return
			}
		}
	}
}

// --------------- View2 ---------------

// View2 provides a type-safe iterator and access layer for entities that
// possess exactly 2 specific stateful components. It acts as a specialized
// window into the ECS world, filtering archetypes that satisfy the required
// component mask and any additional constraints defined via BlueprintOptions.
//
// By leveraging pre-calculated component offsets, View2 enables
// O(1) access to component data during iteration, making it the primary
// tool for implementing high-performance systems and logic loops.
type View2[T1, T2 any] struct {
	*core.View
}

// NewView2 initializes a query for exactly 2 components.
// It panics if the component registration fails, if there are duplicate
// components, or if options (like Exclude) create a logical contradiction.
//
// This ensures that the View is valid and ready for high-performance
// iteration immediately after creation.
func NewView2[T1, T2 any](ecs *ECS, opts ...BlueprintOption) *View2[T1, T2] {
	registry := ecs.registry
	blueprint := core.NewBlueprint(registry)
	componentsRegistry := &registry.ComponentsRegistry

	// Helper: Validates that the required component can be part of the view.
	mustAdd := func(info core.ComponentInfo) {
		if err := blueprint.WithComp(info); err != nil {
			panic(fmt.Sprintf("goke: view2 init failed: %v", err))
		}
	}

	// 1. Resolve Component Infos (Type -> ID)

	info1 := core.EnsureComponentRegistered[T1](componentsRegistry)

	info2 := core.EnsureComponentRegistered[T2](componentsRegistry)

	// 2. Add to Blueprint (Build Mask)

	mustAdd(info1)

	mustAdd(info2)

	// 3. Apply dynamic options (Include/Exclude)
	for _, opt := range opts {
		if err := opt(blueprint); err != nil {
			panic(fmt.Sprintf("goke: view2 option failed: %v", err))
		}
	}

	// 4. Define Rigid Layout (Slice Literal - Zero Allocation Overhead)
	// This guarantees that T1 is at index 0, T2 at index 1, etc.
	layout := []core.ComponentInfo{
		info1, info2,
	}

	view := core.NewView(blueprint, layout, registry)
	return &View2[T1, T2]{View: view}
}

// All returns an iterator (iter.Seq2) that yields the unique Entity identifier
// and a tuple of pointers to its 2 components. This is designed for use
// in range loops, providing a clean, idiomatic Go way to process data while
// maintaining maximum cache efficiency.
//
// The iteration is performed archetype by archetype, ensuring that data is
// accessed contiguously in memory, which significantly reduces CPU cache misses.
//
// Example usage:
//
//	for head, _ := range view2.All() {
//	    entity := head.Entity
//	    v1 := head.V1
//
//	    v2 := head.V2
//
//	}
func (v *View2[T1, T2]) All() iter.Seq2[
	struct {
		Entity core.Entity
		V1     *T1
		V2     *T2
	},
	struct{},
] {
	return func(yield func(
		struct {
			Entity core.Entity
			V1     *T1
			V2     *T2
		},
		struct{},
	) bool) {
		const strideEntity = unsafe.Sizeof(core.Entity(0))
		s1 := unsafe.Sizeof(*new(T1))
		s2 := unsafe.Sizeof(*new(T2))

		for _, b := range v.Baked {

			// 1. Setup Entity Pointer
			pEntity := b.GetEntityColumn().Data

			// 2. Setup Component Pointers
			p1 := b.GetColumn(0).Data
			p2 := b.GetColumn(1).Data

			n := b.Arch.Len()
			// Death Loop (Pointer Arithmetic)
			for n > 0 {

				// Construct Head
				head := struct {
					Entity core.Entity
					V1     *T1
					V2     *T2
				}{
					Entity: *(*core.Entity)(pEntity), V1: (*T1)(p1), V2: (*T2)(p2),
				}

				// Construct Tail

				tail := struct{}{}

				if !yield(head, tail) {
					return
				}

				// Increment Pointers
				pEntity = unsafe.Add(pEntity, strideEntity)
				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)

				n--
			}
		}
	}
}

// Filter returns an iterator (iter.Seq2) that yields only the entities
// specified in the selected slice, provided they match the View's archetype
// constraints. It is optimized for scenarios where a subset of entities
// is pre-determined (e.g., via spatial partitioning or sorted results)
// but requires high-speed access to their component data.
//
// The iterator performs an internal validation for each entity to ensure
// it still belongs to an archetype compatible with this View, preventing
// invalid memory access if the entity's composition has changed.
//
// Example usage:
//
//	selected := []Entity{e1, e5, e10}
//	for head, _ := range view2.Filter(selected) {
//	    entity := head.Entity
//	    v1 := head.V1
//
//
//	    v2 := head.V2
//
//
//	}
func (v *View2[T1, T2]) Filter(selected []Entity) iter.Seq2[
	struct {
		Entity Entity
		V1     *T1
		V2     *T2
	},
	struct{},
] {
	return func(yield func(
		struct {
			Entity Entity
			V1     *T1
			V2     *T2
		},
		struct{},
	) bool) {
		stride1 := unsafe.Sizeof(*new(T1))
		stride2 := unsafe.Sizeof(*new(T2))

		var ptr1, ptr2 unsafe.Pointer
		var lastArchID int32 = -1
		registry := v.Reg.ArchetypeRegistry
		col1ID := v.Layout[0].ID
		col2ID := v.Layout[1].ID

		for _, e := range selected {
			link, ok := registry.EntityLinkStore.Get(e)
			if !ok {
				continue
			}

			if int32(link.ArchId) != lastArchID {
				arch := &registry.Archetypes[link.ArchId]
				if !v.View.Matches(arch.Mask) {
					lastArchID = -1
					continue
				}

				ptr1 = arch.GetColumn(col1ID).Data
				ptr2 = arch.GetColumn(col2ID).Data

				lastArchID = int32(link.ArchId)
			}

			row := uintptr(link.Row)

			head := struct {
				Entity Entity
				V1     *T1
				V2     *T2
			}{
				Entity: e, V1: (*T1)(unsafe.Add(ptr1, row*stride1)), V2: (*T2)(unsafe.Add(ptr2, row*stride2)),
			}

			tail := struct{}{}

			if !yield(head, tail) {
				return
			}
		}
	}
}

// Values returns a performance-critical iterator (iter.Seq2) that yields only
// component pointers, grouped into anonymous head and tail structures.
// This method is specifically designed for high-throughput data processing
// where the Entity identifier is not required.
//
// By omitting the Entity ID, this method minimizes stack pressure and
// register usage, focusing purely on data-driven transformation.
//
// Example usage:
//
//	for head, _ := range view2.Values() {
//	    v1 := head.V1
//
//	    v2 := head.V2
//
//	}
func (v *View2[T1, T2]) Values() iter.Seq2[
	struct {
		V1 *T1
		V2 *T2
	},
	struct{},
] {
	return func(yield func(
		struct {
			V1 *T1
			V2 *T2
		},
		struct{},
	) bool) {
		// Calculate strides for types
		s1 := unsafe.Sizeof(*new(T1))
		s2 := unsafe.Sizeof(*new(T2))

		for _, b := range v.Baked {

			// Setup Component Pointers
			p1 := b.GetColumn(0).Data
			p2 := b.GetColumn(1).Data

			n := b.Arch.Len()

			// Death Loop (Pointer Arithmetic)
			for n > 0 {

				// Construct Head
				head := struct {
					V1 *T1
					V2 *T2
				}{V1: (*T1)(p1), V2: (*T2)(p2)}

				// Construct Tail

				tail := struct{}{}

				if !yield(head, tail) {
					return
				}

				// Increment Pointers
				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)

				n--
			}
		}
	}
}

// FilterValues returns an iterator (iter.Seq2) that yields component pointers
// for a pre-selected subset of entities, skipping the Entity identifier.
// It is optimized for cases where the entity list is already known (e.g., from spatial partitioning).
//
// Like the Values method, it uses anonymous structures to ensure the Go compiler
// can perform aggressive register allocation by avoiding Entity ID overhead.
//
// Example usage:
//
//	selected := []Entity{e1, e5, e10}
//	for head, _ := range view2.FilterValues(selected) {
//	    v1 := head.V1
//
//	    v2 := head.V2
//
//	}
func (v *View2[T1, T2]) FilterValues(selected []Entity) iter.Seq2[
	struct {
		V1 *T1
		V2 *T2
	},
	struct{},
] {
	return func(yield func(
		struct {
			V1 *T1
			V2 *T2
		},
		struct{},
	) bool) {
		stride1 := unsafe.Sizeof(*new(T1))
		stride2 := unsafe.Sizeof(*new(T2))

		var ptr1, ptr2 unsafe.Pointer
		var lastArchID int32 = -1
		registry := v.Reg.ArchetypeRegistry
		col1ID := v.Layout[0].ID
		col2ID := v.Layout[1].ID

		for _, e := range selected {
			link, ok := registry.EntityLinkStore.Get(e)
			if !ok {
				continue
			}

			if int32(link.ArchId) != lastArchID {
				arch := &registry.Archetypes[link.ArchId]
				if !v.View.Matches(arch.Mask) {
					lastArchID = -1
					continue
				}

				ptr1 = arch.GetColumn(col1ID).Data
				ptr2 = arch.GetColumn(col2ID).Data

				lastArchID = int32(link.ArchId)
			}

			row := uintptr(link.Row)

			vhead := struct {
				V1 *T1
				V2 *T2
			}{V1: (*T1)(unsafe.Add(ptr1, row*stride1)), V2: (*T2)(unsafe.Add(ptr2, row*stride2))}

			vtail := struct{}{}

			if !yield(vhead, vtail) {
				return
			}
		}
	}
}

// --------------- View3 ---------------

// View3 provides a type-safe iterator and access layer for entities that
// possess exactly 3 specific stateful components. It acts as a specialized
// window into the ECS world, filtering archetypes that satisfy the required
// component mask and any additional constraints defined via BlueprintOptions.
//
// By leveraging pre-calculated component offsets, View3 enables
// O(1) access to component data during iteration, making it the primary
// tool for implementing high-performance systems and logic loops.
type View3[T1, T2, T3 any] struct {
	*core.View
}

// NewView3 initializes a query for exactly 3 components.
// It panics if the component registration fails, if there are duplicate
// components, or if options (like Exclude) create a logical contradiction.
//
// This ensures that the View is valid and ready for high-performance
// iteration immediately after creation.
func NewView3[T1, T2, T3 any](ecs *ECS, opts ...BlueprintOption) *View3[T1, T2, T3] {
	registry := ecs.registry
	blueprint := core.NewBlueprint(registry)
	componentsRegistry := &registry.ComponentsRegistry

	// Helper: Validates that the required component can be part of the view.
	mustAdd := func(info core.ComponentInfo) {
		if err := blueprint.WithComp(info); err != nil {
			panic(fmt.Sprintf("goke: view3 init failed: %v", err))
		}
	}

	// 1. Resolve Component Infos (Type -> ID)

	info1 := core.EnsureComponentRegistered[T1](componentsRegistry)

	info2 := core.EnsureComponentRegistered[T2](componentsRegistry)

	info3 := core.EnsureComponentRegistered[T3](componentsRegistry)

	// 2. Add to Blueprint (Build Mask)

	mustAdd(info1)

	mustAdd(info2)

	mustAdd(info3)

	// 3. Apply dynamic options (Include/Exclude)
	for _, opt := range opts {
		if err := opt(blueprint); err != nil {
			panic(fmt.Sprintf("goke: view3 option failed: %v", err))
		}
	}

	// 4. Define Rigid Layout (Slice Literal - Zero Allocation Overhead)
	// This guarantees that T1 is at index 0, T2 at index 1, etc.
	layout := []core.ComponentInfo{
		info1, info2, info3,
	}

	view := core.NewView(blueprint, layout, registry)
	return &View3[T1, T2, T3]{View: view}
}

// All returns an iterator (iter.Seq2) that yields the unique Entity identifier
// and a tuple of pointers to its 3 components. This is designed for use
// in range loops, providing a clean, idiomatic Go way to process data while
// maintaining maximum cache efficiency.
//
// The iteration is performed archetype by archetype, ensuring that data is
// accessed contiguously in memory, which significantly reduces CPU cache misses.
//
// Example usage:
//
//	for head, _ := range view3.All() {
//	    entity := head.Entity
//	    v1 := head.V1
//
//	    v3 := head.V3
//
//	}
func (v *View3[T1, T2, T3]) All() iter.Seq2[
	struct {
		Entity core.Entity
		V1     *T1
		V2     *T2
		V3     *T3
	},
	struct{},
] {
	return func(yield func(
		struct {
			Entity core.Entity
			V1     *T1
			V2     *T2
			V3     *T3
		},
		struct{},
	) bool) {
		const strideEntity = unsafe.Sizeof(core.Entity(0))
		s1 := unsafe.Sizeof(*new(T1))
		s2 := unsafe.Sizeof(*new(T2))
		s3 := unsafe.Sizeof(*new(T3))

		for _, b := range v.Baked {

			// 1. Setup Entity Pointer
			pEntity := b.GetEntityColumn().Data

			// 2. Setup Component Pointers
			p1 := b.GetColumn(0).Data
			p2 := b.GetColumn(1).Data
			p3 := b.GetColumn(2).Data

			n := b.Arch.Len()
			// Death Loop (Pointer Arithmetic)
			for n > 0 {

				// Construct Head
				head := struct {
					Entity core.Entity
					V1     *T1
					V2     *T2
					V3     *T3
				}{
					Entity: *(*core.Entity)(pEntity), V1: (*T1)(p1), V2: (*T2)(p2), V3: (*T3)(p3),
				}

				// Construct Tail

				tail := struct{}{}

				if !yield(head, tail) {
					return
				}

				// Increment Pointers
				pEntity = unsafe.Add(pEntity, strideEntity)
				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)
				p3 = unsafe.Add(p3, s3)

				n--
			}
		}
	}
}

// Filter returns an iterator (iter.Seq2) that yields only the entities
// specified in the selected slice, provided they match the View's archetype
// constraints. It is optimized for scenarios where a subset of entities
// is pre-determined (e.g., via spatial partitioning or sorted results)
// but requires high-speed access to their component data.
//
// The iterator performs an internal validation for each entity to ensure
// it still belongs to an archetype compatible with this View, preventing
// invalid memory access if the entity's composition has changed.
//
// Example usage:
//
//	selected := []Entity{e1, e5, e10}
//	for head, _ := range view3.Filter(selected) {
//	    entity := head.Entity
//	    v1 := head.V1
//
//
//	    v3 := head.V3
//
//
//	}
func (v *View3[T1, T2, T3]) Filter(selected []Entity) iter.Seq2[
	struct {
		Entity Entity
		V1     *T1
		V2     *T2
		V3     *T3
	},
	struct{},
] {
	return func(yield func(
		struct {
			Entity Entity
			V1     *T1
			V2     *T2
			V3     *T3
		},
		struct{},
	) bool) {
		stride1 := unsafe.Sizeof(*new(T1))
		stride2 := unsafe.Sizeof(*new(T2))
		stride3 := unsafe.Sizeof(*new(T3))

		var ptr1, ptr2, ptr3 unsafe.Pointer
		var lastArchID int32 = -1
		registry := v.Reg.ArchetypeRegistry
		col1ID := v.Layout[0].ID
		col2ID := v.Layout[1].ID
		col3ID := v.Layout[2].ID

		for _, e := range selected {
			link, ok := registry.EntityLinkStore.Get(e)
			if !ok {
				continue
			}

			if int32(link.ArchId) != lastArchID {
				arch := &registry.Archetypes[link.ArchId]
				if !v.View.Matches(arch.Mask) {
					lastArchID = -1
					continue
				}

				ptr1 = arch.GetColumn(col1ID).Data
				ptr2 = arch.GetColumn(col2ID).Data
				ptr3 = arch.GetColumn(col3ID).Data

				lastArchID = int32(link.ArchId)
			}

			row := uintptr(link.Row)

			head := struct {
				Entity Entity
				V1     *T1
				V2     *T2
				V3     *T3
			}{
				Entity: e, V1: (*T1)(unsafe.Add(ptr1, row*stride1)), V2: (*T2)(unsafe.Add(ptr2, row*stride2)), V3: (*T3)(unsafe.Add(ptr3, row*stride3)),
			}

			tail := struct{}{}

			if !yield(head, tail) {
				return
			}
		}
	}
}

// Values returns a performance-critical iterator (iter.Seq2) that yields only
// component pointers, grouped into anonymous head and tail structures.
// This method is specifically designed for high-throughput data processing
// where the Entity identifier is not required.
//
// By omitting the Entity ID, this method minimizes stack pressure and
// register usage, focusing purely on data-driven transformation.
//
// Example usage:
//
//	for head, _ := range view3.Values() {
//	    v1 := head.V1
//
//	    v3 := head.V3
//
//	}
func (v *View3[T1, T2, T3]) Values() iter.Seq2[
	struct {
		V1 *T1
		V2 *T2
		V3 *T3
	},
	struct{},
] {
	return func(yield func(
		struct {
			V1 *T1
			V2 *T2
			V3 *T3
		},
		struct{},
	) bool) {
		// Calculate strides for types
		s1 := unsafe.Sizeof(*new(T1))
		s2 := unsafe.Sizeof(*new(T2))
		s3 := unsafe.Sizeof(*new(T3))

		for _, b := range v.Baked {

			// Setup Component Pointers
			p1 := b.GetColumn(0).Data
			p2 := b.GetColumn(1).Data
			p3 := b.GetColumn(2).Data

			n := b.Arch.Len()

			// Death Loop (Pointer Arithmetic)
			for n > 0 {

				// Construct Head
				head := struct {
					V1 *T1
					V2 *T2
					V3 *T3
				}{V1: (*T1)(p1), V2: (*T2)(p2), V3: (*T3)(p3)}

				// Construct Tail

				tail := struct{}{}

				if !yield(head, tail) {
					return
				}

				// Increment Pointers
				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)
				p3 = unsafe.Add(p3, s3)

				n--
			}
		}
	}
}

// FilterValues returns an iterator (iter.Seq2) that yields component pointers
// for a pre-selected subset of entities, skipping the Entity identifier.
// It is optimized for cases where the entity list is already known (e.g., from spatial partitioning).
//
// Like the Values method, it uses anonymous structures to ensure the Go compiler
// can perform aggressive register allocation by avoiding Entity ID overhead.
//
// Example usage:
//
//	selected := []Entity{e1, e5, e10}
//	for head, _ := range view3.FilterValues(selected) {
//	    v1 := head.V1
//
//	    v3 := head.V3
//
//	}
func (v *View3[T1, T2, T3]) FilterValues(selected []Entity) iter.Seq2[
	struct {
		V1 *T1
		V2 *T2
		V3 *T3
	},
	struct{},
] {
	return func(yield func(
		struct {
			V1 *T1
			V2 *T2
			V3 *T3
		},
		struct{},
	) bool) {
		stride1 := unsafe.Sizeof(*new(T1))
		stride2 := unsafe.Sizeof(*new(T2))
		stride3 := unsafe.Sizeof(*new(T3))

		var ptr1, ptr2, ptr3 unsafe.Pointer
		var lastArchID int32 = -1
		registry := v.Reg.ArchetypeRegistry
		col1ID := v.Layout[0].ID
		col2ID := v.Layout[1].ID
		col3ID := v.Layout[2].ID

		for _, e := range selected {
			link, ok := registry.EntityLinkStore.Get(e)
			if !ok {
				continue
			}

			if int32(link.ArchId) != lastArchID {
				arch := &registry.Archetypes[link.ArchId]
				if !v.View.Matches(arch.Mask) {
					lastArchID = -1
					continue
				}

				ptr1 = arch.GetColumn(col1ID).Data
				ptr2 = arch.GetColumn(col2ID).Data
				ptr3 = arch.GetColumn(col3ID).Data

				lastArchID = int32(link.ArchId)
			}

			row := uintptr(link.Row)

			vhead := struct {
				V1 *T1
				V2 *T2
				V3 *T3
			}{V1: (*T1)(unsafe.Add(ptr1, row*stride1)), V2: (*T2)(unsafe.Add(ptr2, row*stride2)), V3: (*T3)(unsafe.Add(ptr3, row*stride3))}

			vtail := struct{}{}

			if !yield(vhead, vtail) {
				return
			}
		}
	}
}

// --------------- View4 ---------------

// View4 provides a type-safe iterator and access layer for entities that
// possess exactly 4 specific stateful components. It acts as a specialized
// window into the ECS world, filtering archetypes that satisfy the required
// component mask and any additional constraints defined via BlueprintOptions.
//
// By leveraging pre-calculated component offsets, View4 enables
// O(1) access to component data during iteration, making it the primary
// tool for implementing high-performance systems and logic loops.
type View4[T1, T2, T3, T4 any] struct {
	*core.View
}

// NewView4 initializes a query for exactly 4 components.
// It panics if the component registration fails, if there are duplicate
// components, or if options (like Exclude) create a logical contradiction.
//
// This ensures that the View is valid and ready for high-performance
// iteration immediately after creation.
func NewView4[T1, T2, T3, T4 any](ecs *ECS, opts ...BlueprintOption) *View4[T1, T2, T3, T4] {
	registry := ecs.registry
	blueprint := core.NewBlueprint(registry)
	componentsRegistry := &registry.ComponentsRegistry

	// Helper: Validates that the required component can be part of the view.
	mustAdd := func(info core.ComponentInfo) {
		if err := blueprint.WithComp(info); err != nil {
			panic(fmt.Sprintf("goke: view4 init failed: %v", err))
		}
	}

	// 1. Resolve Component Infos (Type -> ID)

	info1 := core.EnsureComponentRegistered[T1](componentsRegistry)

	info2 := core.EnsureComponentRegistered[T2](componentsRegistry)

	info3 := core.EnsureComponentRegistered[T3](componentsRegistry)

	info4 := core.EnsureComponentRegistered[T4](componentsRegistry)

	// 2. Add to Blueprint (Build Mask)

	mustAdd(info1)

	mustAdd(info2)

	mustAdd(info3)

	mustAdd(info4)

	// 3. Apply dynamic options (Include/Exclude)
	for _, opt := range opts {
		if err := opt(blueprint); err != nil {
			panic(fmt.Sprintf("goke: view4 option failed: %v", err))
		}
	}

	// 4. Define Rigid Layout (Slice Literal - Zero Allocation Overhead)
	// This guarantees that T1 is at index 0, T2 at index 1, etc.
	layout := []core.ComponentInfo{
		info1, info2, info3, info4,
	}

	view := core.NewView(blueprint, layout, registry)
	return &View4[T1, T2, T3, T4]{View: view}
}

// All returns an iterator (iter.Seq2) that yields the unique Entity identifier
// and a tuple of pointers to its 4 components. This is designed for use
// in range loops, providing a clean, idiomatic Go way to process data while
// maintaining maximum cache efficiency.
//
// The iteration is performed archetype by archetype, ensuring that data is
// accessed contiguously in memory, which significantly reduces CPU cache misses.
//
// Example usage:
//
//	for head, tail := range view4.All() {
//	    entity := head.Entity
//	    v1 := head.V1
//
//	    v4 := tail.V4
//
//	}
func (v *View4[T1, T2, T3, T4]) All() iter.Seq2[
	struct {
		Entity core.Entity
		V1     *T1
		V2     *T2
		V3     *T3
	},
	struct{ V4 *T4 },
] {
	return func(yield func(
		struct {
			Entity core.Entity
			V1     *T1
			V2     *T2
			V3     *T3
		},
		struct{ V4 *T4 },
	) bool) {
		const strideEntity = unsafe.Sizeof(core.Entity(0))
		s1 := unsafe.Sizeof(*new(T1))
		s2 := unsafe.Sizeof(*new(T2))
		s3 := unsafe.Sizeof(*new(T3))
		s4 := unsafe.Sizeof(*new(T4))

		for _, b := range v.Baked {

			// 1. Setup Entity Pointer
			pEntity := b.GetEntityColumn().Data

			// 2. Setup Component Pointers
			p1 := b.GetColumn(0).Data
			p2 := b.GetColumn(1).Data
			p3 := b.GetColumn(2).Data
			p4 := b.GetColumn(3).Data

			n := b.Arch.Len()
			// Death Loop (Pointer Arithmetic)
			for n > 0 {

				// Construct Head
				head := struct {
					Entity core.Entity
					V1     *T1
					V2     *T2
					V3     *T3
				}{
					Entity: *(*core.Entity)(pEntity), V1: (*T1)(p1), V2: (*T2)(p2), V3: (*T3)(p3),
				}

				// Construct Tail

				tail := struct{ V4 *T4 }{V4: (*T4)(p4)}

				if !yield(head, tail) {
					return
				}

				// Increment Pointers
				pEntity = unsafe.Add(pEntity, strideEntity)
				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)
				p3 = unsafe.Add(p3, s3)
				p4 = unsafe.Add(p4, s4)

				n--
			}
		}
	}
}

// Filter returns an iterator (iter.Seq2) that yields only the entities
// specified in the selected slice, provided they match the View's archetype
// constraints. It is optimized for scenarios where a subset of entities
// is pre-determined (e.g., via spatial partitioning or sorted results)
// but requires high-speed access to their component data.
//
// The iterator performs an internal validation for each entity to ensure
// it still belongs to an archetype compatible with this View, preventing
// invalid memory access if the entity's composition has changed.
//
// Example usage:
//
//	selected := []Entity{e1, e5, e10}
//	for head, tail := range view4.Filter(selected) {
//	    entity := head.Entity
//	    v1 := head.V1
//
//
//	    v4 := tail.V4
//
//
//	}
func (v *View4[T1, T2, T3, T4]) Filter(selected []Entity) iter.Seq2[
	struct {
		Entity Entity
		V1     *T1
		V2     *T2
		V3     *T3
	},
	struct{ V4 *T4 },
] {
	return func(yield func(
		struct {
			Entity Entity
			V1     *T1
			V2     *T2
			V3     *T3
		},
		struct{ V4 *T4 },
	) bool) {
		stride1 := unsafe.Sizeof(*new(T1))
		stride2 := unsafe.Sizeof(*new(T2))
		stride3 := unsafe.Sizeof(*new(T3))
		stride4 := unsafe.Sizeof(*new(T4))

		var ptr1, ptr2, ptr3, ptr4 unsafe.Pointer
		var lastArchID int32 = -1
		registry := v.Reg.ArchetypeRegistry
		col1ID := v.Layout[0].ID
		col2ID := v.Layout[1].ID
		col3ID := v.Layout[2].ID
		col4ID := v.Layout[3].ID

		for _, e := range selected {
			link, ok := registry.EntityLinkStore.Get(e)
			if !ok {
				continue
			}

			if int32(link.ArchId) != lastArchID {
				arch := &registry.Archetypes[link.ArchId]
				if !v.View.Matches(arch.Mask) {
					lastArchID = -1
					continue
				}

				ptr1 = arch.GetColumn(col1ID).Data
				ptr2 = arch.GetColumn(col2ID).Data
				ptr3 = arch.GetColumn(col3ID).Data
				ptr4 = arch.GetColumn(col4ID).Data

				lastArchID = int32(link.ArchId)
			}

			row := uintptr(link.Row)

			head := struct {
				Entity Entity
				V1     *T1
				V2     *T2
				V3     *T3
			}{
				Entity: e, V1: (*T1)(unsafe.Add(ptr1, row*stride1)), V2: (*T2)(unsafe.Add(ptr2, row*stride2)), V3: (*T3)(unsafe.Add(ptr3, row*stride3)),
			}

			tail := struct{ V4 *T4 }{V4: (*T4)(unsafe.Add(ptr4, row*stride4))}

			if !yield(head, tail) {
				return
			}
		}
	}
}

// Values returns a performance-critical iterator (iter.Seq2) that yields only
// component pointers, grouped into anonymous head and tail structures.
// This method is specifically designed for high-throughput data processing
// where the Entity identifier is not required.
//
// By omitting the Entity ID, this method minimizes stack pressure and
// register usage, focusing purely on data-driven transformation.
//
// Example usage:
//
//	for head, _ := range view4.Values() {
//	    v1 := head.V1
//
//	    v4 := head.V4
//
//	}
func (v *View4[T1, T2, T3, T4]) Values() iter.Seq2[
	struct {
		V1 *T1
		V2 *T2
		V3 *T3
		V4 *T4
	},
	struct{},
] {
	return func(yield func(
		struct {
			V1 *T1
			V2 *T2
			V3 *T3
			V4 *T4
		},
		struct{},
	) bool) {
		// Calculate strides for types
		s1 := unsafe.Sizeof(*new(T1))
		s2 := unsafe.Sizeof(*new(T2))
		s3 := unsafe.Sizeof(*new(T3))
		s4 := unsafe.Sizeof(*new(T4))

		for _, b := range v.Baked {

			// Setup Component Pointers
			p1 := b.GetColumn(0).Data
			p2 := b.GetColumn(1).Data
			p3 := b.GetColumn(2).Data
			p4 := b.GetColumn(3).Data

			n := b.Arch.Len()

			// Death Loop (Pointer Arithmetic)
			for n > 0 {

				// Construct Head
				head := struct {
					V1 *T1
					V2 *T2
					V3 *T3
					V4 *T4
				}{V1: (*T1)(p1), V2: (*T2)(p2), V3: (*T3)(p3), V4: (*T4)(p4)}

				// Construct Tail

				tail := struct{}{}

				if !yield(head, tail) {
					return
				}

				// Increment Pointers
				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)
				p3 = unsafe.Add(p3, s3)
				p4 = unsafe.Add(p4, s4)

				n--
			}
		}
	}
}

// FilterValues returns an iterator (iter.Seq2) that yields component pointers
// for a pre-selected subset of entities, skipping the Entity identifier.
// It is optimized for cases where the entity list is already known (e.g., from spatial partitioning).
//
// Like the Values method, it uses anonymous structures to ensure the Go compiler
// can perform aggressive register allocation by avoiding Entity ID overhead.
//
// Example usage:
//
//	selected := []Entity{e1, e5, e10}
//	for head, _ := range view4.FilterValues(selected) {
//	    v1 := head.V1
//
//	    v4 := head.V4
//
//	}
func (v *View4[T1, T2, T3, T4]) FilterValues(selected []Entity) iter.Seq2[
	struct {
		V1 *T1
		V2 *T2
		V3 *T3
		V4 *T4
	},
	struct{},
] {
	return func(yield func(
		struct {
			V1 *T1
			V2 *T2
			V3 *T3
			V4 *T4
		},
		struct{},
	) bool) {
		stride1 := unsafe.Sizeof(*new(T1))
		stride2 := unsafe.Sizeof(*new(T2))
		stride3 := unsafe.Sizeof(*new(T3))
		stride4 := unsafe.Sizeof(*new(T4))

		var ptr1, ptr2, ptr3, ptr4 unsafe.Pointer
		var lastArchID int32 = -1
		registry := v.Reg.ArchetypeRegistry
		col1ID := v.Layout[0].ID
		col2ID := v.Layout[1].ID
		col3ID := v.Layout[2].ID
		col4ID := v.Layout[3].ID

		for _, e := range selected {
			link, ok := registry.EntityLinkStore.Get(e)
			if !ok {
				continue
			}

			if int32(link.ArchId) != lastArchID {
				arch := &registry.Archetypes[link.ArchId]
				if !v.View.Matches(arch.Mask) {
					lastArchID = -1
					continue
				}

				ptr1 = arch.GetColumn(col1ID).Data
				ptr2 = arch.GetColumn(col2ID).Data
				ptr3 = arch.GetColumn(col3ID).Data
				ptr4 = arch.GetColumn(col4ID).Data

				lastArchID = int32(link.ArchId)
			}

			row := uintptr(link.Row)

			vhead := struct {
				V1 *T1
				V2 *T2
				V3 *T3
				V4 *T4
			}{V1: (*T1)(unsafe.Add(ptr1, row*stride1)), V2: (*T2)(unsafe.Add(ptr2, row*stride2)), V3: (*T3)(unsafe.Add(ptr3, row*stride3)), V4: (*T4)(unsafe.Add(ptr4, row*stride4))}

			vtail := struct{}{}

			if !yield(vhead, vtail) {
				return
			}
		}
	}
}

// --------------- View5 ---------------

// View5 provides a type-safe iterator and access layer for entities that
// possess exactly 5 specific stateful components. It acts as a specialized
// window into the ECS world, filtering archetypes that satisfy the required
// component mask and any additional constraints defined via BlueprintOptions.
//
// By leveraging pre-calculated component offsets, View5 enables
// O(1) access to component data during iteration, making it the primary
// tool for implementing high-performance systems and logic loops.
type View5[T1, T2, T3, T4, T5 any] struct {
	*core.View
}

// NewView5 initializes a query for exactly 5 components.
// It panics if the component registration fails, if there are duplicate
// components, or if options (like Exclude) create a logical contradiction.
//
// This ensures that the View is valid and ready for high-performance
// iteration immediately after creation.
func NewView5[T1, T2, T3, T4, T5 any](ecs *ECS, opts ...BlueprintOption) *View5[T1, T2, T3, T4, T5] {
	registry := ecs.registry
	blueprint := core.NewBlueprint(registry)
	componentsRegistry := &registry.ComponentsRegistry

	// Helper: Validates that the required component can be part of the view.
	mustAdd := func(info core.ComponentInfo) {
		if err := blueprint.WithComp(info); err != nil {
			panic(fmt.Sprintf("goke: view5 init failed: %v", err))
		}
	}

	// 1. Resolve Component Infos (Type -> ID)

	info1 := core.EnsureComponentRegistered[T1](componentsRegistry)

	info2 := core.EnsureComponentRegistered[T2](componentsRegistry)

	info3 := core.EnsureComponentRegistered[T3](componentsRegistry)

	info4 := core.EnsureComponentRegistered[T4](componentsRegistry)

	info5 := core.EnsureComponentRegistered[T5](componentsRegistry)

	// 2. Add to Blueprint (Build Mask)

	mustAdd(info1)

	mustAdd(info2)

	mustAdd(info3)

	mustAdd(info4)

	mustAdd(info5)

	// 3. Apply dynamic options (Include/Exclude)
	for _, opt := range opts {
		if err := opt(blueprint); err != nil {
			panic(fmt.Sprintf("goke: view5 option failed: %v", err))
		}
	}

	// 4. Define Rigid Layout (Slice Literal - Zero Allocation Overhead)
	// This guarantees that T1 is at index 0, T2 at index 1, etc.
	layout := []core.ComponentInfo{
		info1, info2, info3, info4, info5,
	}

	view := core.NewView(blueprint, layout, registry)
	return &View5[T1, T2, T3, T4, T5]{View: view}
}

// All returns an iterator (iter.Seq2) that yields the unique Entity identifier
// and a tuple of pointers to its 5 components. This is designed for use
// in range loops, providing a clean, idiomatic Go way to process data while
// maintaining maximum cache efficiency.
//
// The iteration is performed archetype by archetype, ensuring that data is
// accessed contiguously in memory, which significantly reduces CPU cache misses.
//
// Example usage:
//
//	for head, tail := range view5.All() {
//	    entity := head.Entity
//	    v1 := head.V1
//
//	    v5 := tail.V5
//
//	}
func (v *View5[T1, T2, T3, T4, T5]) All() iter.Seq2[
	struct {
		Entity core.Entity
		V1     *T1
		V2     *T2
		V3     *T3
	},
	struct {
		V4 *T4
		V5 *T5
	},
] {
	return func(yield func(
		struct {
			Entity core.Entity
			V1     *T1
			V2     *T2
			V3     *T3
		},
		struct {
			V4 *T4
			V5 *T5
		},
	) bool) {
		const strideEntity = unsafe.Sizeof(core.Entity(0))
		s1 := unsafe.Sizeof(*new(T1))
		s2 := unsafe.Sizeof(*new(T2))
		s3 := unsafe.Sizeof(*new(T3))
		s4 := unsafe.Sizeof(*new(T4))
		s5 := unsafe.Sizeof(*new(T5))

		for _, b := range v.Baked {

			// 1. Setup Entity Pointer
			pEntity := b.GetEntityColumn().Data

			// 2. Setup Component Pointers
			p1 := b.GetColumn(0).Data
			p2 := b.GetColumn(1).Data
			p3 := b.GetColumn(2).Data
			p4 := b.GetColumn(3).Data
			p5 := b.GetColumn(4).Data

			n := b.Arch.Len()
			// Death Loop (Pointer Arithmetic)
			for n > 0 {

				// Construct Head
				head := struct {
					Entity core.Entity
					V1     *T1
					V2     *T2
					V3     *T3
				}{
					Entity: *(*core.Entity)(pEntity), V1: (*T1)(p1), V2: (*T2)(p2), V3: (*T3)(p3),
				}

				// Construct Tail

				tail := struct {
					V4 *T4
					V5 *T5
				}{V4: (*T4)(p4), V5: (*T5)(p5)}

				if !yield(head, tail) {
					return
				}

				// Increment Pointers
				pEntity = unsafe.Add(pEntity, strideEntity)
				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)
				p3 = unsafe.Add(p3, s3)
				p4 = unsafe.Add(p4, s4)
				p5 = unsafe.Add(p5, s5)

				n--
			}
		}
	}
}

// Filter returns an iterator (iter.Seq2) that yields only the entities
// specified in the selected slice, provided they match the View's archetype
// constraints. It is optimized for scenarios where a subset of entities
// is pre-determined (e.g., via spatial partitioning or sorted results)
// but requires high-speed access to their component data.
//
// The iterator performs an internal validation for each entity to ensure
// it still belongs to an archetype compatible with this View, preventing
// invalid memory access if the entity's composition has changed.
//
// Example usage:
//
//	selected := []Entity{e1, e5, e10}
//	for head, tail := range view5.Filter(selected) {
//	    entity := head.Entity
//	    v1 := head.V1
//
//
//	    v5 := tail.V5
//
//
//	}
func (v *View5[T1, T2, T3, T4, T5]) Filter(selected []Entity) iter.Seq2[
	struct {
		Entity Entity
		V1     *T1
		V2     *T2
		V3     *T3
	},
	struct {
		V4 *T4
		V5 *T5
	},
] {
	return func(yield func(
		struct {
			Entity Entity
			V1     *T1
			V2     *T2
			V3     *T3
		},
		struct {
			V4 *T4
			V5 *T5
		},
	) bool) {
		stride1 := unsafe.Sizeof(*new(T1))
		stride2 := unsafe.Sizeof(*new(T2))
		stride3 := unsafe.Sizeof(*new(T3))
		stride4 := unsafe.Sizeof(*new(T4))
		stride5 := unsafe.Sizeof(*new(T5))

		var ptr1, ptr2, ptr3, ptr4, ptr5 unsafe.Pointer
		var lastArchID int32 = -1
		registry := v.Reg.ArchetypeRegistry
		col1ID := v.Layout[0].ID
		col2ID := v.Layout[1].ID
		col3ID := v.Layout[2].ID
		col4ID := v.Layout[3].ID
		col5ID := v.Layout[4].ID

		for _, e := range selected {
			link, ok := registry.EntityLinkStore.Get(e)
			if !ok {
				continue
			}

			if int32(link.ArchId) != lastArchID {
				arch := &registry.Archetypes[link.ArchId]
				if !v.View.Matches(arch.Mask) {
					lastArchID = -1
					continue
				}

				ptr1 = arch.GetColumn(col1ID).Data
				ptr2 = arch.GetColumn(col2ID).Data
				ptr3 = arch.GetColumn(col3ID).Data
				ptr4 = arch.GetColumn(col4ID).Data
				ptr5 = arch.GetColumn(col5ID).Data

				lastArchID = int32(link.ArchId)
			}

			row := uintptr(link.Row)

			head := struct {
				Entity Entity
				V1     *T1
				V2     *T2
				V3     *T3
			}{
				Entity: e, V1: (*T1)(unsafe.Add(ptr1, row*stride1)), V2: (*T2)(unsafe.Add(ptr2, row*stride2)), V3: (*T3)(unsafe.Add(ptr3, row*stride3)),
			}

			tail := struct {
				V4 *T4
				V5 *T5
			}{V4: (*T4)(unsafe.Add(ptr4, row*stride4)), V5: (*T5)(unsafe.Add(ptr5, row*stride5))}

			if !yield(head, tail) {
				return
			}
		}
	}
}

// Values returns a performance-critical iterator (iter.Seq2) that yields only
// component pointers, grouped into anonymous head and tail structures.
// This method is specifically designed for high-throughput data processing
// where the Entity identifier is not required.
//
// By omitting the Entity ID, this method minimizes stack pressure and
// register usage, focusing purely on data-driven transformation.
//
// Example usage:
//
//	for head, tail := range view5.Values() {
//	    v1 := head.V1
//
//
//	    v5 := tail.V5
//
//	}
func (v *View5[T1, T2, T3, T4, T5]) Values() iter.Seq2[
	struct {
		V1 *T1
		V2 *T2
		V3 *T3
		V4 *T4
	},
	struct{ V5 *T5 },
] {
	return func(yield func(
		struct {
			V1 *T1
			V2 *T2
			V3 *T3
			V4 *T4
		},
		struct{ V5 *T5 },
	) bool) {
		// Calculate strides for types
		s1 := unsafe.Sizeof(*new(T1))
		s2 := unsafe.Sizeof(*new(T2))
		s3 := unsafe.Sizeof(*new(T3))
		s4 := unsafe.Sizeof(*new(T4))
		s5 := unsafe.Sizeof(*new(T5))

		for _, b := range v.Baked {

			// Setup Component Pointers
			p1 := b.GetColumn(0).Data
			p2 := b.GetColumn(1).Data
			p3 := b.GetColumn(2).Data
			p4 := b.GetColumn(3).Data
			p5 := b.GetColumn(4).Data

			n := b.Arch.Len()

			// Death Loop (Pointer Arithmetic)
			for n > 0 {

				// Construct Head
				head := struct {
					V1 *T1
					V2 *T2
					V3 *T3
					V4 *T4
				}{V1: (*T1)(p1), V2: (*T2)(p2), V3: (*T3)(p3), V4: (*T4)(p4)}

				// Construct Tail

				tail := struct{ V5 *T5 }{V5: (*T5)(p5)}

				if !yield(head, tail) {
					return
				}

				// Increment Pointers
				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)
				p3 = unsafe.Add(p3, s3)
				p4 = unsafe.Add(p4, s4)
				p5 = unsafe.Add(p5, s5)

				n--
			}
		}
	}
}

// FilterValues returns an iterator (iter.Seq2) that yields component pointers
// for a pre-selected subset of entities, skipping the Entity identifier.
// It is optimized for cases where the entity list is already known (e.g., from spatial partitioning).
//
// Like the Values method, it uses anonymous structures to ensure the Go compiler
// can perform aggressive register allocation by avoiding Entity ID overhead.
//
// Example usage:
//
//	selected := []Entity{e1, e5, e10}
//	for head, tail := range view5.FilterValues(selected) {
//	    v1 := head.V1
//
//
//	    v5 := tail.V5
//
//	}
func (v *View5[T1, T2, T3, T4, T5]) FilterValues(selected []Entity) iter.Seq2[
	struct {
		V1 *T1
		V2 *T2
		V3 *T3
		V4 *T4
	},
	struct{ V5 *T5 },
] {
	return func(yield func(
		struct {
			V1 *T1
			V2 *T2
			V3 *T3
			V4 *T4
		},
		struct{ V5 *T5 },
	) bool) {
		stride1 := unsafe.Sizeof(*new(T1))
		stride2 := unsafe.Sizeof(*new(T2))
		stride3 := unsafe.Sizeof(*new(T3))
		stride4 := unsafe.Sizeof(*new(T4))
		stride5 := unsafe.Sizeof(*new(T5))

		var ptr1, ptr2, ptr3, ptr4, ptr5 unsafe.Pointer
		var lastArchID int32 = -1
		registry := v.Reg.ArchetypeRegistry
		col1ID := v.Layout[0].ID
		col2ID := v.Layout[1].ID
		col3ID := v.Layout[2].ID
		col4ID := v.Layout[3].ID
		col5ID := v.Layout[4].ID

		for _, e := range selected {
			link, ok := registry.EntityLinkStore.Get(e)
			if !ok {
				continue
			}

			if int32(link.ArchId) != lastArchID {
				arch := &registry.Archetypes[link.ArchId]
				if !v.View.Matches(arch.Mask) {
					lastArchID = -1
					continue
				}

				ptr1 = arch.GetColumn(col1ID).Data
				ptr2 = arch.GetColumn(col2ID).Data
				ptr3 = arch.GetColumn(col3ID).Data
				ptr4 = arch.GetColumn(col4ID).Data
				ptr5 = arch.GetColumn(col5ID).Data

				lastArchID = int32(link.ArchId)
			}

			row := uintptr(link.Row)

			vhead := struct {
				V1 *T1
				V2 *T2
				V3 *T3
				V4 *T4
			}{V1: (*T1)(unsafe.Add(ptr1, row*stride1)), V2: (*T2)(unsafe.Add(ptr2, row*stride2)), V3: (*T3)(unsafe.Add(ptr3, row*stride3)), V4: (*T4)(unsafe.Add(ptr4, row*stride4))}

			vtail := struct{ V5 *T5 }{V5: (*T5)(unsafe.Add(ptr5, row*stride5))}

			if !yield(vhead, vtail) {
				return
			}
		}
	}
}

// --------------- View6 ---------------

// View6 provides a type-safe iterator and access layer for entities that
// possess exactly 6 specific stateful components. It acts as a specialized
// window into the ECS world, filtering archetypes that satisfy the required
// component mask and any additional constraints defined via BlueprintOptions.
//
// By leveraging pre-calculated component offsets, View6 enables
// O(1) access to component data during iteration, making it the primary
// tool for implementing high-performance systems and logic loops.
type View6[T1, T2, T3, T4, T5, T6 any] struct {
	*core.View
}

// NewView6 initializes a query for exactly 6 components.
// It panics if the component registration fails, if there are duplicate
// components, or if options (like Exclude) create a logical contradiction.
//
// This ensures that the View is valid and ready for high-performance
// iteration immediately after creation.
func NewView6[T1, T2, T3, T4, T5, T6 any](ecs *ECS, opts ...BlueprintOption) *View6[T1, T2, T3, T4, T5, T6] {
	registry := ecs.registry
	blueprint := core.NewBlueprint(registry)
	componentsRegistry := &registry.ComponentsRegistry

	// Helper: Validates that the required component can be part of the view.
	mustAdd := func(info core.ComponentInfo) {
		if err := blueprint.WithComp(info); err != nil {
			panic(fmt.Sprintf("goke: view6 init failed: %v", err))
		}
	}

	// 1. Resolve Component Infos (Type -> ID)

	info1 := core.EnsureComponentRegistered[T1](componentsRegistry)

	info2 := core.EnsureComponentRegistered[T2](componentsRegistry)

	info3 := core.EnsureComponentRegistered[T3](componentsRegistry)

	info4 := core.EnsureComponentRegistered[T4](componentsRegistry)

	info5 := core.EnsureComponentRegistered[T5](componentsRegistry)

	info6 := core.EnsureComponentRegistered[T6](componentsRegistry)

	// 2. Add to Blueprint (Build Mask)

	mustAdd(info1)

	mustAdd(info2)

	mustAdd(info3)

	mustAdd(info4)

	mustAdd(info5)

	mustAdd(info6)

	// 3. Apply dynamic options (Include/Exclude)
	for _, opt := range opts {
		if err := opt(blueprint); err != nil {
			panic(fmt.Sprintf("goke: view6 option failed: %v", err))
		}
	}

	// 4. Define Rigid Layout (Slice Literal - Zero Allocation Overhead)
	// This guarantees that T1 is at index 0, T2 at index 1, etc.
	layout := []core.ComponentInfo{
		info1, info2, info3, info4, info5, info6,
	}

	view := core.NewView(blueprint, layout, registry)
	return &View6[T1, T2, T3, T4, T5, T6]{View: view}
}

// All returns an iterator (iter.Seq2) that yields the unique Entity identifier
// and a tuple of pointers to its 6 components. This is designed for use
// in range loops, providing a clean, idiomatic Go way to process data while
// maintaining maximum cache efficiency.
//
// The iteration is performed archetype by archetype, ensuring that data is
// accessed contiguously in memory, which significantly reduces CPU cache misses.
//
// Example usage:
//
//	for head, tail := range view6.All() {
//	    entity := head.Entity
//	    v1 := head.V1
//
//	    v6 := tail.V6
//
//	}
func (v *View6[T1, T2, T3, T4, T5, T6]) All() iter.Seq2[
	struct {
		Entity core.Entity
		V1     *T1
		V2     *T2
		V3     *T3
	},
	struct {
		V4 *T4
		V5 *T5
		V6 *T6
	},
] {
	return func(yield func(
		struct {
			Entity core.Entity
			V1     *T1
			V2     *T2
			V3     *T3
		},
		struct {
			V4 *T4
			V5 *T5
			V6 *T6
		},
	) bool) {
		const strideEntity = unsafe.Sizeof(core.Entity(0))
		s1 := unsafe.Sizeof(*new(T1))
		s2 := unsafe.Sizeof(*new(T2))
		s3 := unsafe.Sizeof(*new(T3))
		s4 := unsafe.Sizeof(*new(T4))
		s5 := unsafe.Sizeof(*new(T5))
		s6 := unsafe.Sizeof(*new(T6))

		for _, b := range v.Baked {

			// 1. Setup Entity Pointer
			pEntity := b.GetEntityColumn().Data

			// 2. Setup Component Pointers
			p1 := b.GetColumn(0).Data
			p2 := b.GetColumn(1).Data
			p3 := b.GetColumn(2).Data
			p4 := b.GetColumn(3).Data
			p5 := b.GetColumn(4).Data
			p6 := b.GetColumn(5).Data

			n := b.Arch.Len()
			// Death Loop (Pointer Arithmetic)
			for n > 0 {

				// Construct Head
				head := struct {
					Entity core.Entity
					V1     *T1
					V2     *T2
					V3     *T3
				}{
					Entity: *(*core.Entity)(pEntity), V1: (*T1)(p1), V2: (*T2)(p2), V3: (*T3)(p3),
				}

				// Construct Tail

				tail := struct {
					V4 *T4
					V5 *T5
					V6 *T6
				}{V4: (*T4)(p4), V5: (*T5)(p5), V6: (*T6)(p6)}

				if !yield(head, tail) {
					return
				}

				// Increment Pointers
				pEntity = unsafe.Add(pEntity, strideEntity)
				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)
				p3 = unsafe.Add(p3, s3)
				p4 = unsafe.Add(p4, s4)
				p5 = unsafe.Add(p5, s5)
				p6 = unsafe.Add(p6, s6)

				n--
			}
		}
	}
}

// Filter returns an iterator (iter.Seq2) that yields only the entities
// specified in the selected slice, provided they match the View's archetype
// constraints. It is optimized for scenarios where a subset of entities
// is pre-determined (e.g., via spatial partitioning or sorted results)
// but requires high-speed access to their component data.
//
// The iterator performs an internal validation for each entity to ensure
// it still belongs to an archetype compatible with this View, preventing
// invalid memory access if the entity's composition has changed.
//
// Example usage:
//
//	selected := []Entity{e1, e5, e10}
//	for head, tail := range view6.Filter(selected) {
//	    entity := head.Entity
//	    v1 := head.V1
//
//
//	    v6 := tail.V6
//
//
//	}
func (v *View6[T1, T2, T3, T4, T5, T6]) Filter(selected []Entity) iter.Seq2[
	struct {
		Entity Entity
		V1     *T1
		V2     *T2
		V3     *T3
	},
	struct {
		V4 *T4
		V5 *T5
		V6 *T6
	},
] {
	return func(yield func(
		struct {
			Entity Entity
			V1     *T1
			V2     *T2
			V3     *T3
		},
		struct {
			V4 *T4
			V5 *T5
			V6 *T6
		},
	) bool) {
		stride1 := unsafe.Sizeof(*new(T1))
		stride2 := unsafe.Sizeof(*new(T2))
		stride3 := unsafe.Sizeof(*new(T3))
		stride4 := unsafe.Sizeof(*new(T4))
		stride5 := unsafe.Sizeof(*new(T5))
		stride6 := unsafe.Sizeof(*new(T6))

		var ptr1, ptr2, ptr3, ptr4, ptr5, ptr6 unsafe.Pointer
		var lastArchID int32 = -1
		registry := v.Reg.ArchetypeRegistry
		col1ID := v.Layout[0].ID
		col2ID := v.Layout[1].ID
		col3ID := v.Layout[2].ID
		col4ID := v.Layout[3].ID
		col5ID := v.Layout[4].ID
		col6ID := v.Layout[5].ID

		for _, e := range selected {
			link, ok := registry.EntityLinkStore.Get(e)
			if !ok {
				continue
			}

			if int32(link.ArchId) != lastArchID {
				arch := &registry.Archetypes[link.ArchId]
				if !v.View.Matches(arch.Mask) {
					lastArchID = -1
					continue
				}

				ptr1 = arch.GetColumn(col1ID).Data
				ptr2 = arch.GetColumn(col2ID).Data
				ptr3 = arch.GetColumn(col3ID).Data
				ptr4 = arch.GetColumn(col4ID).Data
				ptr5 = arch.GetColumn(col5ID).Data
				ptr6 = arch.GetColumn(col6ID).Data

				lastArchID = int32(link.ArchId)
			}

			row := uintptr(link.Row)

			head := struct {
				Entity Entity
				V1     *T1
				V2     *T2
				V3     *T3
			}{
				Entity: e, V1: (*T1)(unsafe.Add(ptr1, row*stride1)), V2: (*T2)(unsafe.Add(ptr2, row*stride2)), V3: (*T3)(unsafe.Add(ptr3, row*stride3)),
			}

			tail := struct {
				V4 *T4
				V5 *T5
				V6 *T6
			}{V4: (*T4)(unsafe.Add(ptr4, row*stride4)), V5: (*T5)(unsafe.Add(ptr5, row*stride5)), V6: (*T6)(unsafe.Add(ptr6, row*stride6))}

			if !yield(head, tail) {
				return
			}
		}
	}
}

// Values returns a performance-critical iterator (iter.Seq2) that yields only
// component pointers, grouped into anonymous head and tail structures.
// This method is specifically designed for high-throughput data processing
// where the Entity identifier is not required.
//
// By omitting the Entity ID, this method minimizes stack pressure and
// register usage, focusing purely on data-driven transformation.
//
// Example usage:
//
//	for head, tail := range view6.Values() {
//	    v1 := head.V1
//
//
//	    v6 := tail.V6
//
//	}
func (v *View6[T1, T2, T3, T4, T5, T6]) Values() iter.Seq2[
	struct {
		V1 *T1
		V2 *T2
		V3 *T3
		V4 *T4
	},
	struct {
		V5 *T5
		V6 *T6
	},
] {
	return func(yield func(
		struct {
			V1 *T1
			V2 *T2
			V3 *T3
			V4 *T4
		},
		struct {
			V5 *T5
			V6 *T6
		},
	) bool) {
		// Calculate strides for types
		s1 := unsafe.Sizeof(*new(T1))
		s2 := unsafe.Sizeof(*new(T2))
		s3 := unsafe.Sizeof(*new(T3))
		s4 := unsafe.Sizeof(*new(T4))
		s5 := unsafe.Sizeof(*new(T5))
		s6 := unsafe.Sizeof(*new(T6))

		for _, b := range v.Baked {

			// Setup Component Pointers
			p1 := b.GetColumn(0).Data
			p2 := b.GetColumn(1).Data
			p3 := b.GetColumn(2).Data
			p4 := b.GetColumn(3).Data
			p5 := b.GetColumn(4).Data
			p6 := b.GetColumn(5).Data

			n := b.Arch.Len()

			// Death Loop (Pointer Arithmetic)
			for n > 0 {

				// Construct Head
				head := struct {
					V1 *T1
					V2 *T2
					V3 *T3
					V4 *T4
				}{V1: (*T1)(p1), V2: (*T2)(p2), V3: (*T3)(p3), V4: (*T4)(p4)}

				// Construct Tail

				tail := struct {
					V5 *T5
					V6 *T6
				}{V5: (*T5)(p5), V6: (*T6)(p6)}

				if !yield(head, tail) {
					return
				}

				// Increment Pointers
				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)
				p3 = unsafe.Add(p3, s3)
				p4 = unsafe.Add(p4, s4)
				p5 = unsafe.Add(p5, s5)
				p6 = unsafe.Add(p6, s6)

				n--
			}
		}
	}
}

// FilterValues returns an iterator (iter.Seq2) that yields component pointers
// for a pre-selected subset of entities, skipping the Entity identifier.
// It is optimized for cases where the entity list is already known (e.g., from spatial partitioning).
//
// Like the Values method, it uses anonymous structures to ensure the Go compiler
// can perform aggressive register allocation by avoiding Entity ID overhead.
//
// Example usage:
//
//	selected := []Entity{e1, e5, e10}
//	for head, tail := range view6.FilterValues(selected) {
//	    v1 := head.V1
//
//
//	    v6 := tail.V6
//
//	}
func (v *View6[T1, T2, T3, T4, T5, T6]) FilterValues(selected []Entity) iter.Seq2[
	struct {
		V1 *T1
		V2 *T2
		V3 *T3
		V4 *T4
	},
	struct {
		V5 *T5
		V6 *T6
	},
] {
	return func(yield func(
		struct {
			V1 *T1
			V2 *T2
			V3 *T3
			V4 *T4
		},
		struct {
			V5 *T5
			V6 *T6
		},
	) bool) {
		stride1 := unsafe.Sizeof(*new(T1))
		stride2 := unsafe.Sizeof(*new(T2))
		stride3 := unsafe.Sizeof(*new(T3))
		stride4 := unsafe.Sizeof(*new(T4))
		stride5 := unsafe.Sizeof(*new(T5))
		stride6 := unsafe.Sizeof(*new(T6))

		var ptr1, ptr2, ptr3, ptr4, ptr5, ptr6 unsafe.Pointer
		var lastArchID int32 = -1
		registry := v.Reg.ArchetypeRegistry
		col1ID := v.Layout[0].ID
		col2ID := v.Layout[1].ID
		col3ID := v.Layout[2].ID
		col4ID := v.Layout[3].ID
		col5ID := v.Layout[4].ID
		col6ID := v.Layout[5].ID

		for _, e := range selected {
			link, ok := registry.EntityLinkStore.Get(e)
			if !ok {
				continue
			}

			if int32(link.ArchId) != lastArchID {
				arch := &registry.Archetypes[link.ArchId]
				if !v.View.Matches(arch.Mask) {
					lastArchID = -1
					continue
				}

				ptr1 = arch.GetColumn(col1ID).Data
				ptr2 = arch.GetColumn(col2ID).Data
				ptr3 = arch.GetColumn(col3ID).Data
				ptr4 = arch.GetColumn(col4ID).Data
				ptr5 = arch.GetColumn(col5ID).Data
				ptr6 = arch.GetColumn(col6ID).Data

				lastArchID = int32(link.ArchId)
			}

			row := uintptr(link.Row)

			vhead := struct {
				V1 *T1
				V2 *T2
				V3 *T3
				V4 *T4
			}{V1: (*T1)(unsafe.Add(ptr1, row*stride1)), V2: (*T2)(unsafe.Add(ptr2, row*stride2)), V3: (*T3)(unsafe.Add(ptr3, row*stride3)), V4: (*T4)(unsafe.Add(ptr4, row*stride4))}

			vtail := struct {
				V5 *T5
				V6 *T6
			}{V5: (*T5)(unsafe.Add(ptr5, row*stride5)), V6: (*T6)(unsafe.Add(ptr6, row*stride6))}

			if !yield(vhead, vtail) {
				return
			}
		}
	}
}

// --------------- View7 ---------------

// View7 provides a type-safe iterator and access layer for entities that
// possess exactly 7 specific stateful components. It acts as a specialized
// window into the ECS world, filtering archetypes that satisfy the required
// component mask and any additional constraints defined via BlueprintOptions.
//
// By leveraging pre-calculated component offsets, View7 enables
// O(1) access to component data during iteration, making it the primary
// tool for implementing high-performance systems and logic loops.
type View7[T1, T2, T3, T4, T5, T6, T7 any] struct {
	*core.View
}

// NewView7 initializes a query for exactly 7 components.
// It panics if the component registration fails, if there are duplicate
// components, or if options (like Exclude) create a logical contradiction.
//
// This ensures that the View is valid and ready for high-performance
// iteration immediately after creation.
func NewView7[T1, T2, T3, T4, T5, T6, T7 any](ecs *ECS, opts ...BlueprintOption) *View7[T1, T2, T3, T4, T5, T6, T7] {
	registry := ecs.registry
	blueprint := core.NewBlueprint(registry)
	componentsRegistry := &registry.ComponentsRegistry

	// Helper: Validates that the required component can be part of the view.
	mustAdd := func(info core.ComponentInfo) {
		if err := blueprint.WithComp(info); err != nil {
			panic(fmt.Sprintf("goke: view7 init failed: %v", err))
		}
	}

	// 1. Resolve Component Infos (Type -> ID)

	info1 := core.EnsureComponentRegistered[T1](componentsRegistry)

	info2 := core.EnsureComponentRegistered[T2](componentsRegistry)

	info3 := core.EnsureComponentRegistered[T3](componentsRegistry)

	info4 := core.EnsureComponentRegistered[T4](componentsRegistry)

	info5 := core.EnsureComponentRegistered[T5](componentsRegistry)

	info6 := core.EnsureComponentRegistered[T6](componentsRegistry)

	info7 := core.EnsureComponentRegistered[T7](componentsRegistry)

	// 2. Add to Blueprint (Build Mask)

	mustAdd(info1)

	mustAdd(info2)

	mustAdd(info3)

	mustAdd(info4)

	mustAdd(info5)

	mustAdd(info6)

	mustAdd(info7)

	// 3. Apply dynamic options (Include/Exclude)
	for _, opt := range opts {
		if err := opt(blueprint); err != nil {
			panic(fmt.Sprintf("goke: view7 option failed: %v", err))
		}
	}

	// 4. Define Rigid Layout (Slice Literal - Zero Allocation Overhead)
	// This guarantees that T1 is at index 0, T2 at index 1, etc.
	layout := []core.ComponentInfo{
		info1, info2, info3, info4, info5, info6, info7,
	}

	view := core.NewView(blueprint, layout, registry)
	return &View7[T1, T2, T3, T4, T5, T6, T7]{View: view}
}

// All returns an iterator (iter.Seq2) that yields the unique Entity identifier
// and a tuple of pointers to its 7 components. This is designed for use
// in range loops, providing a clean, idiomatic Go way to process data while
// maintaining maximum cache efficiency.
//
// The iteration is performed archetype by archetype, ensuring that data is
// accessed contiguously in memory, which significantly reduces CPU cache misses.
//
// Example usage:
//
//	for head, tail := range view7.All() {
//	    entity := head.Entity
//	    v1 := head.V1
//
//	    v7 := tail.V7
//
//	}
func (v *View7[T1, T2, T3, T4, T5, T6, T7]) All() iter.Seq2[
	struct {
		Entity core.Entity
		V1     *T1
		V2     *T2
		V3     *T3
	},
	struct {
		V4 *T4
		V5 *T5
		V6 *T6
		V7 *T7
	},
] {
	return func(yield func(
		struct {
			Entity core.Entity
			V1     *T1
			V2     *T2
			V3     *T3
		},
		struct {
			V4 *T4
			V5 *T5
			V6 *T6
			V7 *T7
		},
	) bool) {
		const strideEntity = unsafe.Sizeof(core.Entity(0))
		s1 := unsafe.Sizeof(*new(T1))
		s2 := unsafe.Sizeof(*new(T2))
		s3 := unsafe.Sizeof(*new(T3))
		s4 := unsafe.Sizeof(*new(T4))
		s5 := unsafe.Sizeof(*new(T5))
		s6 := unsafe.Sizeof(*new(T6))
		s7 := unsafe.Sizeof(*new(T7))

		for _, b := range v.Baked {

			// 1. Setup Entity Pointer
			pEntity := b.GetEntityColumn().Data

			// 2. Setup Component Pointers
			p1 := b.GetColumn(0).Data
			p2 := b.GetColumn(1).Data
			p3 := b.GetColumn(2).Data
			p4 := b.GetColumn(3).Data
			p5 := b.GetColumn(4).Data
			p6 := b.GetColumn(5).Data
			p7 := b.GetColumn(6).Data

			n := b.Arch.Len()
			// Death Loop (Pointer Arithmetic)
			for n > 0 {

				// Construct Head
				head := struct {
					Entity core.Entity
					V1     *T1
					V2     *T2
					V3     *T3
				}{
					Entity: *(*core.Entity)(pEntity), V1: (*T1)(p1), V2: (*T2)(p2), V3: (*T3)(p3),
				}

				// Construct Tail

				tail := struct {
					V4 *T4
					V5 *T5
					V6 *T6
					V7 *T7
				}{V4: (*T4)(p4), V5: (*T5)(p5), V6: (*T6)(p6), V7: (*T7)(p7)}

				if !yield(head, tail) {
					return
				}

				// Increment Pointers
				pEntity = unsafe.Add(pEntity, strideEntity)
				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)
				p3 = unsafe.Add(p3, s3)
				p4 = unsafe.Add(p4, s4)
				p5 = unsafe.Add(p5, s5)
				p6 = unsafe.Add(p6, s6)
				p7 = unsafe.Add(p7, s7)

				n--
			}
		}
	}
}

// Filter returns an iterator (iter.Seq2) that yields only the entities
// specified in the selected slice, provided they match the View's archetype
// constraints. It is optimized for scenarios where a subset of entities
// is pre-determined (e.g., via spatial partitioning or sorted results)
// but requires high-speed access to their component data.
//
// The iterator performs an internal validation for each entity to ensure
// it still belongs to an archetype compatible with this View, preventing
// invalid memory access if the entity's composition has changed.
//
// Example usage:
//
//	selected := []Entity{e1, e5, e10}
//	for head, tail := range view7.Filter(selected) {
//	    entity := head.Entity
//	    v1 := head.V1
//
//
//	    v7 := tail.V7
//
//
//	}
func (v *View7[T1, T2, T3, T4, T5, T6, T7]) Filter(selected []Entity) iter.Seq2[
	struct {
		Entity Entity
		V1     *T1
		V2     *T2
		V3     *T3
	},
	struct {
		V4 *T4
		V5 *T5
		V6 *T6
		V7 *T7
	},
] {
	return func(yield func(
		struct {
			Entity Entity
			V1     *T1
			V2     *T2
			V3     *T3
		},
		struct {
			V4 *T4
			V5 *T5
			V6 *T6
			V7 *T7
		},
	) bool) {
		stride1 := unsafe.Sizeof(*new(T1))
		stride2 := unsafe.Sizeof(*new(T2))
		stride3 := unsafe.Sizeof(*new(T3))
		stride4 := unsafe.Sizeof(*new(T4))
		stride5 := unsafe.Sizeof(*new(T5))
		stride6 := unsafe.Sizeof(*new(T6))
		stride7 := unsafe.Sizeof(*new(T7))

		var ptr1, ptr2, ptr3, ptr4, ptr5, ptr6, ptr7 unsafe.Pointer
		var lastArchID int32 = -1
		registry := v.Reg.ArchetypeRegistry
		col1ID := v.Layout[0].ID
		col2ID := v.Layout[1].ID
		col3ID := v.Layout[2].ID
		col4ID := v.Layout[3].ID
		col5ID := v.Layout[4].ID
		col6ID := v.Layout[5].ID
		col7ID := v.Layout[6].ID

		for _, e := range selected {
			link, ok := registry.EntityLinkStore.Get(e)
			if !ok {
				continue
			}

			if int32(link.ArchId) != lastArchID {
				arch := &registry.Archetypes[link.ArchId]
				if !v.View.Matches(arch.Mask) {
					lastArchID = -1
					continue
				}

				ptr1 = arch.GetColumn(col1ID).Data
				ptr2 = arch.GetColumn(col2ID).Data
				ptr3 = arch.GetColumn(col3ID).Data
				ptr4 = arch.GetColumn(col4ID).Data
				ptr5 = arch.GetColumn(col5ID).Data
				ptr6 = arch.GetColumn(col6ID).Data
				ptr7 = arch.GetColumn(col7ID).Data

				lastArchID = int32(link.ArchId)
			}

			row := uintptr(link.Row)

			head := struct {
				Entity Entity
				V1     *T1
				V2     *T2
				V3     *T3
			}{
				Entity: e, V1: (*T1)(unsafe.Add(ptr1, row*stride1)), V2: (*T2)(unsafe.Add(ptr2, row*stride2)), V3: (*T3)(unsafe.Add(ptr3, row*stride3)),
			}

			tail := struct {
				V4 *T4
				V5 *T5
				V6 *T6
				V7 *T7
			}{V4: (*T4)(unsafe.Add(ptr4, row*stride4)), V5: (*T5)(unsafe.Add(ptr5, row*stride5)), V6: (*T6)(unsafe.Add(ptr6, row*stride6)), V7: (*T7)(unsafe.Add(ptr7, row*stride7))}

			if !yield(head, tail) {
				return
			}
		}
	}
}

// Values returns a performance-critical iterator (iter.Seq2) that yields only
// component pointers, grouped into anonymous head and tail structures.
// This method is specifically designed for high-throughput data processing
// where the Entity identifier is not required.
//
// By omitting the Entity ID, this method minimizes stack pressure and
// register usage, focusing purely on data-driven transformation.
//
// Example usage:
//
//	for head, tail := range view7.Values() {
//	    v1 := head.V1
//
//
//	    v7 := tail.V7
//
//	}
func (v *View7[T1, T2, T3, T4, T5, T6, T7]) Values() iter.Seq2[
	struct {
		V1 *T1
		V2 *T2
		V3 *T3
		V4 *T4
	},
	struct {
		V5 *T5
		V6 *T6
		V7 *T7
	},
] {
	return func(yield func(
		struct {
			V1 *T1
			V2 *T2
			V3 *T3
			V4 *T4
		},
		struct {
			V5 *T5
			V6 *T6
			V7 *T7
		},
	) bool) {
		// Calculate strides for types
		s1 := unsafe.Sizeof(*new(T1))
		s2 := unsafe.Sizeof(*new(T2))
		s3 := unsafe.Sizeof(*new(T3))
		s4 := unsafe.Sizeof(*new(T4))
		s5 := unsafe.Sizeof(*new(T5))
		s6 := unsafe.Sizeof(*new(T6))
		s7 := unsafe.Sizeof(*new(T7))

		for _, b := range v.Baked {

			// Setup Component Pointers
			p1 := b.GetColumn(0).Data
			p2 := b.GetColumn(1).Data
			p3 := b.GetColumn(2).Data
			p4 := b.GetColumn(3).Data
			p5 := b.GetColumn(4).Data
			p6 := b.GetColumn(5).Data
			p7 := b.GetColumn(6).Data

			n := b.Arch.Len()

			// Death Loop (Pointer Arithmetic)
			for n > 0 {

				// Construct Head
				head := struct {
					V1 *T1
					V2 *T2
					V3 *T3
					V4 *T4
				}{V1: (*T1)(p1), V2: (*T2)(p2), V3: (*T3)(p3), V4: (*T4)(p4)}

				// Construct Tail

				tail := struct {
					V5 *T5
					V6 *T6
					V7 *T7
				}{V5: (*T5)(p5), V6: (*T6)(p6), V7: (*T7)(p7)}

				if !yield(head, tail) {
					return
				}

				// Increment Pointers
				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)
				p3 = unsafe.Add(p3, s3)
				p4 = unsafe.Add(p4, s4)
				p5 = unsafe.Add(p5, s5)
				p6 = unsafe.Add(p6, s6)
				p7 = unsafe.Add(p7, s7)

				n--
			}
		}
	}
}

// FilterValues returns an iterator (iter.Seq2) that yields component pointers
// for a pre-selected subset of entities, skipping the Entity identifier.
// It is optimized for cases where the entity list is already known (e.g., from spatial partitioning).
//
// Like the Values method, it uses anonymous structures to ensure the Go compiler
// can perform aggressive register allocation by avoiding Entity ID overhead.
//
// Example usage:
//
//	selected := []Entity{e1, e5, e10}
//	for head, tail := range view7.FilterValues(selected) {
//	    v1 := head.V1
//
//
//	    v7 := tail.V7
//
//	}
func (v *View7[T1, T2, T3, T4, T5, T6, T7]) FilterValues(selected []Entity) iter.Seq2[
	struct {
		V1 *T1
		V2 *T2
		V3 *T3
		V4 *T4
	},
	struct {
		V5 *T5
		V6 *T6
		V7 *T7
	},
] {
	return func(yield func(
		struct {
			V1 *T1
			V2 *T2
			V3 *T3
			V4 *T4
		},
		struct {
			V5 *T5
			V6 *T6
			V7 *T7
		},
	) bool) {
		stride1 := unsafe.Sizeof(*new(T1))
		stride2 := unsafe.Sizeof(*new(T2))
		stride3 := unsafe.Sizeof(*new(T3))
		stride4 := unsafe.Sizeof(*new(T4))
		stride5 := unsafe.Sizeof(*new(T5))
		stride6 := unsafe.Sizeof(*new(T6))
		stride7 := unsafe.Sizeof(*new(T7))

		var ptr1, ptr2, ptr3, ptr4, ptr5, ptr6, ptr7 unsafe.Pointer
		var lastArchID int32 = -1
		registry := v.Reg.ArchetypeRegistry
		col1ID := v.Layout[0].ID
		col2ID := v.Layout[1].ID
		col3ID := v.Layout[2].ID
		col4ID := v.Layout[3].ID
		col5ID := v.Layout[4].ID
		col6ID := v.Layout[5].ID
		col7ID := v.Layout[6].ID

		for _, e := range selected {
			link, ok := registry.EntityLinkStore.Get(e)
			if !ok {
				continue
			}

			if int32(link.ArchId) != lastArchID {
				arch := &registry.Archetypes[link.ArchId]
				if !v.View.Matches(arch.Mask) {
					lastArchID = -1
					continue
				}

				ptr1 = arch.GetColumn(col1ID).Data
				ptr2 = arch.GetColumn(col2ID).Data
				ptr3 = arch.GetColumn(col3ID).Data
				ptr4 = arch.GetColumn(col4ID).Data
				ptr5 = arch.GetColumn(col5ID).Data
				ptr6 = arch.GetColumn(col6ID).Data
				ptr7 = arch.GetColumn(col7ID).Data

				lastArchID = int32(link.ArchId)
			}

			row := uintptr(link.Row)

			vhead := struct {
				V1 *T1
				V2 *T2
				V3 *T3
				V4 *T4
			}{V1: (*T1)(unsafe.Add(ptr1, row*stride1)), V2: (*T2)(unsafe.Add(ptr2, row*stride2)), V3: (*T3)(unsafe.Add(ptr3, row*stride3)), V4: (*T4)(unsafe.Add(ptr4, row*stride4))}

			vtail := struct {
				V5 *T5
				V6 *T6
				V7 *T7
			}{V5: (*T5)(unsafe.Add(ptr5, row*stride5)), V6: (*T6)(unsafe.Add(ptr6, row*stride6)), V7: (*T7)(unsafe.Add(ptr7, row*stride7))}

			if !yield(vhead, vtail) {
				return
			}
		}
	}
}

// --------------- View8 ---------------

// View8 provides a type-safe iterator and access layer for entities that
// possess exactly 8 specific stateful components. It acts as a specialized
// window into the ECS world, filtering archetypes that satisfy the required
// component mask and any additional constraints defined via BlueprintOptions.
//
// By leveraging pre-calculated component offsets, View8 enables
// O(1) access to component data during iteration, making it the primary
// tool for implementing high-performance systems and logic loops.
type View8[T1, T2, T3, T4, T5, T6, T7, T8 any] struct {
	*core.View
}

// NewView8 initializes a query for exactly 8 components.
// It panics if the component registration fails, if there are duplicate
// components, or if options (like Exclude) create a logical contradiction.
//
// This ensures that the View is valid and ready for high-performance
// iteration immediately after creation.
func NewView8[T1, T2, T3, T4, T5, T6, T7, T8 any](ecs *ECS, opts ...BlueprintOption) *View8[T1, T2, T3, T4, T5, T6, T7, T8] {
	registry := ecs.registry
	blueprint := core.NewBlueprint(registry)
	componentsRegistry := &registry.ComponentsRegistry

	// Helper: Validates that the required component can be part of the view.
	mustAdd := func(info core.ComponentInfo) {
		if err := blueprint.WithComp(info); err != nil {
			panic(fmt.Sprintf("goke: view8 init failed: %v", err))
		}
	}

	// 1. Resolve Component Infos (Type -> ID)

	info1 := core.EnsureComponentRegistered[T1](componentsRegistry)

	info2 := core.EnsureComponentRegistered[T2](componentsRegistry)

	info3 := core.EnsureComponentRegistered[T3](componentsRegistry)

	info4 := core.EnsureComponentRegistered[T4](componentsRegistry)

	info5 := core.EnsureComponentRegistered[T5](componentsRegistry)

	info6 := core.EnsureComponentRegistered[T6](componentsRegistry)

	info7 := core.EnsureComponentRegistered[T7](componentsRegistry)

	info8 := core.EnsureComponentRegistered[T8](componentsRegistry)

	// 2. Add to Blueprint (Build Mask)

	mustAdd(info1)

	mustAdd(info2)

	mustAdd(info3)

	mustAdd(info4)

	mustAdd(info5)

	mustAdd(info6)

	mustAdd(info7)

	mustAdd(info8)

	// 3. Apply dynamic options (Include/Exclude)
	for _, opt := range opts {
		if err := opt(blueprint); err != nil {
			panic(fmt.Sprintf("goke: view8 option failed: %v", err))
		}
	}

	// 4. Define Rigid Layout (Slice Literal - Zero Allocation Overhead)
	// This guarantees that T1 is at index 0, T2 at index 1, etc.
	layout := []core.ComponentInfo{
		info1, info2, info3, info4, info5, info6, info7, info8,
	}

	view := core.NewView(blueprint, layout, registry)
	return &View8[T1, T2, T3, T4, T5, T6, T7, T8]{View: view}
}

// All returns an iterator (iter.Seq2) that yields the unique Entity identifier
// and a tuple of pointers to its 8 components. This is designed for use
// in range loops, providing a clean, idiomatic Go way to process data while
// maintaining maximum cache efficiency.
//
// The iteration is performed archetype by archetype, ensuring that data is
// accessed contiguously in memory, which significantly reduces CPU cache misses.
//
// Example usage:
//
//	for head, tail := range view8.All() {
//	    entity := head.Entity
//	    v1 := head.V1
//
//	    v8 := tail.V8
//
//	}
func (v *View8[T1, T2, T3, T4, T5, T6, T7, T8]) All() iter.Seq2[
	struct {
		Entity core.Entity
		V1     *T1
		V2     *T2
		V3     *T3
	},
	struct {
		V4 *T4
		V5 *T5
		V6 *T6
		V7 *T7
		V8 *T8
	},
] {
	return func(yield func(
		struct {
			Entity core.Entity
			V1     *T1
			V2     *T2
			V3     *T3
		},
		struct {
			V4 *T4
			V5 *T5
			V6 *T6
			V7 *T7
			V8 *T8
		},
	) bool) {
		const strideEntity = unsafe.Sizeof(core.Entity(0))
		s1 := unsafe.Sizeof(*new(T1))
		s2 := unsafe.Sizeof(*new(T2))
		s3 := unsafe.Sizeof(*new(T3))
		s4 := unsafe.Sizeof(*new(T4))
		s5 := unsafe.Sizeof(*new(T5))
		s6 := unsafe.Sizeof(*new(T6))
		s7 := unsafe.Sizeof(*new(T7))
		s8 := unsafe.Sizeof(*new(T8))

		for _, b := range v.Baked {

			// 1. Setup Entity Pointer
			pEntity := b.GetEntityColumn().Data

			// 2. Setup Component Pointers
			p1 := b.GetColumn(0).Data
			p2 := b.GetColumn(1).Data
			p3 := b.GetColumn(2).Data
			p4 := b.GetColumn(3).Data
			p5 := b.GetColumn(4).Data
			p6 := b.GetColumn(5).Data
			p7 := b.GetColumn(6).Data
			p8 := b.GetColumn(7).Data

			n := b.Arch.Len()
			// Death Loop (Pointer Arithmetic)
			for n > 0 {

				// Construct Head
				head := struct {
					Entity core.Entity
					V1     *T1
					V2     *T2
					V3     *T3
				}{
					Entity: *(*core.Entity)(pEntity), V1: (*T1)(p1), V2: (*T2)(p2), V3: (*T3)(p3),
				}

				// Construct Tail

				tail := struct {
					V4 *T4
					V5 *T5
					V6 *T6
					V7 *T7
					V8 *T8
				}{V4: (*T4)(p4), V5: (*T5)(p5), V6: (*T6)(p6), V7: (*T7)(p7), V8: (*T8)(p8)}

				if !yield(head, tail) {
					return
				}

				// Increment Pointers
				pEntity = unsafe.Add(pEntity, strideEntity)
				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)
				p3 = unsafe.Add(p3, s3)
				p4 = unsafe.Add(p4, s4)
				p5 = unsafe.Add(p5, s5)
				p6 = unsafe.Add(p6, s6)
				p7 = unsafe.Add(p7, s7)
				p8 = unsafe.Add(p8, s8)

				n--
			}
		}
	}
}

// Filter returns an iterator (iter.Seq2) that yields only the entities
// specified in the selected slice, provided they match the View's archetype
// constraints. It is optimized for scenarios where a subset of entities
// is pre-determined (e.g., via spatial partitioning or sorted results)
// but requires high-speed access to their component data.
//
// The iterator performs an internal validation for each entity to ensure
// it still belongs to an archetype compatible with this View, preventing
// invalid memory access if the entity's composition has changed.
//
// Example usage:
//
//	selected := []Entity{e1, e5, e10}
//	for head, tail := range view8.Filter(selected) {
//	    entity := head.Entity
//	    v1 := head.V1
//
//
//	    v8 := tail.V8
//
//
//	}
func (v *View8[T1, T2, T3, T4, T5, T6, T7, T8]) Filter(selected []Entity) iter.Seq2[
	struct {
		Entity Entity
		V1     *T1
		V2     *T2
		V3     *T3
	},
	struct {
		V4 *T4
		V5 *T5
		V6 *T6
		V7 *T7
		V8 *T8
	},
] {
	return func(yield func(
		struct {
			Entity Entity
			V1     *T1
			V2     *T2
			V3     *T3
		},
		struct {
			V4 *T4
			V5 *T5
			V6 *T6
			V7 *T7
			V8 *T8
		},
	) bool) {
		stride1 := unsafe.Sizeof(*new(T1))
		stride2 := unsafe.Sizeof(*new(T2))
		stride3 := unsafe.Sizeof(*new(T3))
		stride4 := unsafe.Sizeof(*new(T4))
		stride5 := unsafe.Sizeof(*new(T5))
		stride6 := unsafe.Sizeof(*new(T6))
		stride7 := unsafe.Sizeof(*new(T7))
		stride8 := unsafe.Sizeof(*new(T8))

		var ptr1, ptr2, ptr3, ptr4, ptr5, ptr6, ptr7, ptr8 unsafe.Pointer
		var lastArchID int32 = -1
		registry := v.Reg.ArchetypeRegistry
		col1ID := v.Layout[0].ID
		col2ID := v.Layout[1].ID
		col3ID := v.Layout[2].ID
		col4ID := v.Layout[3].ID
		col5ID := v.Layout[4].ID
		col6ID := v.Layout[5].ID
		col7ID := v.Layout[6].ID
		col8ID := v.Layout[7].ID

		for _, e := range selected {
			link, ok := registry.EntityLinkStore.Get(e)
			if !ok {
				continue
			}

			if int32(link.ArchId) != lastArchID {
				arch := &registry.Archetypes[link.ArchId]
				if !v.View.Matches(arch.Mask) {
					lastArchID = -1
					continue
				}

				ptr1 = arch.GetColumn(col1ID).Data
				ptr2 = arch.GetColumn(col2ID).Data
				ptr3 = arch.GetColumn(col3ID).Data
				ptr4 = arch.GetColumn(col4ID).Data
				ptr5 = arch.GetColumn(col5ID).Data
				ptr6 = arch.GetColumn(col6ID).Data
				ptr7 = arch.GetColumn(col7ID).Data
				ptr8 = arch.GetColumn(col8ID).Data

				lastArchID = int32(link.ArchId)
			}

			row := uintptr(link.Row)

			head := struct {
				Entity Entity
				V1     *T1
				V2     *T2
				V3     *T3
			}{
				Entity: e, V1: (*T1)(unsafe.Add(ptr1, row*stride1)), V2: (*T2)(unsafe.Add(ptr2, row*stride2)), V3: (*T3)(unsafe.Add(ptr3, row*stride3)),
			}

			tail := struct {
				V4 *T4
				V5 *T5
				V6 *T6
				V7 *T7
				V8 *T8
			}{V4: (*T4)(unsafe.Add(ptr4, row*stride4)), V5: (*T5)(unsafe.Add(ptr5, row*stride5)), V6: (*T6)(unsafe.Add(ptr6, row*stride6)), V7: (*T7)(unsafe.Add(ptr7, row*stride7)), V8: (*T8)(unsafe.Add(ptr8, row*stride8))}

			if !yield(head, tail) {
				return
			}
		}
	}
}

// Values returns a performance-critical iterator (iter.Seq2) that yields only
// component pointers, grouped into anonymous head and tail structures.
// This method is specifically designed for high-throughput data processing
// where the Entity identifier is not required.
//
// By omitting the Entity ID, this method minimizes stack pressure and
// register usage, focusing purely on data-driven transformation.
//
// Example usage:
//
//	for head, tail := range view8.Values() {
//	    v1 := head.V1
//
//
//	    v8 := tail.V8
//
//	}
func (v *View8[T1, T2, T3, T4, T5, T6, T7, T8]) Values() iter.Seq2[
	struct {
		V1 *T1
		V2 *T2
		V3 *T3
		V4 *T4
	},
	struct {
		V5 *T5
		V6 *T6
		V7 *T7
		V8 *T8
	},
] {
	return func(yield func(
		struct {
			V1 *T1
			V2 *T2
			V3 *T3
			V4 *T4
		},
		struct {
			V5 *T5
			V6 *T6
			V7 *T7
			V8 *T8
		},
	) bool) {
		// Calculate strides for types
		s1 := unsafe.Sizeof(*new(T1))
		s2 := unsafe.Sizeof(*new(T2))
		s3 := unsafe.Sizeof(*new(T3))
		s4 := unsafe.Sizeof(*new(T4))
		s5 := unsafe.Sizeof(*new(T5))
		s6 := unsafe.Sizeof(*new(T6))
		s7 := unsafe.Sizeof(*new(T7))
		s8 := unsafe.Sizeof(*new(T8))

		for _, b := range v.Baked {

			// Setup Component Pointers
			p1 := b.GetColumn(0).Data
			p2 := b.GetColumn(1).Data
			p3 := b.GetColumn(2).Data
			p4 := b.GetColumn(3).Data
			p5 := b.GetColumn(4).Data
			p6 := b.GetColumn(5).Data
			p7 := b.GetColumn(6).Data
			p8 := b.GetColumn(7).Data

			n := b.Arch.Len()

			// Death Loop (Pointer Arithmetic)
			for n > 0 {

				// Construct Head
				head := struct {
					V1 *T1
					V2 *T2
					V3 *T3
					V4 *T4
				}{V1: (*T1)(p1), V2: (*T2)(p2), V3: (*T3)(p3), V4: (*T4)(p4)}

				// Construct Tail

				tail := struct {
					V5 *T5
					V6 *T6
					V7 *T7
					V8 *T8
				}{V5: (*T5)(p5), V6: (*T6)(p6), V7: (*T7)(p7), V8: (*T8)(p8)}

				if !yield(head, tail) {
					return
				}

				// Increment Pointers
				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)
				p3 = unsafe.Add(p3, s3)
				p4 = unsafe.Add(p4, s4)
				p5 = unsafe.Add(p5, s5)
				p6 = unsafe.Add(p6, s6)
				p7 = unsafe.Add(p7, s7)
				p8 = unsafe.Add(p8, s8)

				n--
			}
		}
	}
}

// FilterValues returns an iterator (iter.Seq2) that yields component pointers
// for a pre-selected subset of entities, skipping the Entity identifier.
// It is optimized for cases where the entity list is already known (e.g., from spatial partitioning).
//
// Like the Values method, it uses anonymous structures to ensure the Go compiler
// can perform aggressive register allocation by avoiding Entity ID overhead.
//
// Example usage:
//
//	selected := []Entity{e1, e5, e10}
//	for head, tail := range view8.FilterValues(selected) {
//	    v1 := head.V1
//
//
//	    v8 := tail.V8
//
//	}
func (v *View8[T1, T2, T3, T4, T5, T6, T7, T8]) FilterValues(selected []Entity) iter.Seq2[
	struct {
		V1 *T1
		V2 *T2
		V3 *T3
		V4 *T4
	},
	struct {
		V5 *T5
		V6 *T6
		V7 *T7
		V8 *T8
	},
] {
	return func(yield func(
		struct {
			V1 *T1
			V2 *T2
			V3 *T3
			V4 *T4
		},
		struct {
			V5 *T5
			V6 *T6
			V7 *T7
			V8 *T8
		},
	) bool) {
		stride1 := unsafe.Sizeof(*new(T1))
		stride2 := unsafe.Sizeof(*new(T2))
		stride3 := unsafe.Sizeof(*new(T3))
		stride4 := unsafe.Sizeof(*new(T4))
		stride5 := unsafe.Sizeof(*new(T5))
		stride6 := unsafe.Sizeof(*new(T6))
		stride7 := unsafe.Sizeof(*new(T7))
		stride8 := unsafe.Sizeof(*new(T8))

		var ptr1, ptr2, ptr3, ptr4, ptr5, ptr6, ptr7, ptr8 unsafe.Pointer
		var lastArchID int32 = -1
		registry := v.Reg.ArchetypeRegistry
		col1ID := v.Layout[0].ID
		col2ID := v.Layout[1].ID
		col3ID := v.Layout[2].ID
		col4ID := v.Layout[3].ID
		col5ID := v.Layout[4].ID
		col6ID := v.Layout[5].ID
		col7ID := v.Layout[6].ID
		col8ID := v.Layout[7].ID

		for _, e := range selected {
			link, ok := registry.EntityLinkStore.Get(e)
			if !ok {
				continue
			}

			if int32(link.ArchId) != lastArchID {
				arch := &registry.Archetypes[link.ArchId]
				if !v.View.Matches(arch.Mask) {
					lastArchID = -1
					continue
				}

				ptr1 = arch.GetColumn(col1ID).Data
				ptr2 = arch.GetColumn(col2ID).Data
				ptr3 = arch.GetColumn(col3ID).Data
				ptr4 = arch.GetColumn(col4ID).Data
				ptr5 = arch.GetColumn(col5ID).Data
				ptr6 = arch.GetColumn(col6ID).Data
				ptr7 = arch.GetColumn(col7ID).Data
				ptr8 = arch.GetColumn(col8ID).Data

				lastArchID = int32(link.ArchId)
			}

			row := uintptr(link.Row)

			vhead := struct {
				V1 *T1
				V2 *T2
				V3 *T3
				V4 *T4
			}{V1: (*T1)(unsafe.Add(ptr1, row*stride1)), V2: (*T2)(unsafe.Add(ptr2, row*stride2)), V3: (*T3)(unsafe.Add(ptr3, row*stride3)), V4: (*T4)(unsafe.Add(ptr4, row*stride4))}

			vtail := struct {
				V5 *T5
				V6 *T6
				V7 *T7
				V8 *T8
			}{V5: (*T5)(unsafe.Add(ptr5, row*stride5)), V6: (*T6)(unsafe.Add(ptr6, row*stride6)), V7: (*T7)(unsafe.Add(ptr7, row*stride7)), V8: (*T8)(unsafe.Add(ptr8, row*stride8))}

			if !yield(vhead, vtail) {
				return
			}
		}
	}
}
