// Code generated by gen/queries; DO NOT EDIT.
package ecsq
import (
	"iter"
	"unsafe"

	"github.com/kjkrol/goke/internal/core"
)

type Query3[T1, T2, T3 any] struct {
	*core.View
}

func NewQuery3[T1, T2, T3 any](reg *core.Registry, options ...core.ViewOption) *Query3[T1, T2, T3] {
	viewBuilder := core.NewViewBuilder(reg)
	core.OnCompType[T1](viewBuilder)
	core.OnCompType[T2](viewBuilder)
	core.OnCompType[T3](viewBuilder)
	for _, opt := range options {
		opt(viewBuilder)
	}
	return &Query3[T1, T2, T3]{View: viewBuilder.Build()}
}

type Head3[T1, T2, T3 any] struct {
	Entity core.Entity
	V1 *T1
	V2 *T2
	V3 *T3
}
type PHead3[T1, T2, T3 any] struct {
	V1 *T1
	V2 *T2
	V3 *T3
}

func (q *Query3[T1, T2, T3]) All3() iter.Seq[Head3[T1, T2, T3]] {
	return func(yield func(Head3[T1, T2, T3]) bool) {
		for i := range q.Baked {
			b := &q.Baked[i]
			p1, s1 := b.Columns[0].Data, b.Columns[0].ItemSize
			p2, s2 := b.Columns[1].Data, b.Columns[1].ItemSize
			p3, s3 := b.Columns[2].Data, b.Columns[2].ItemSize
			for j := 0; j < *b.Len; j++ {
				if !yield(Head3[T1, T2, T3]{Entity: (*b.Entities)[j], V1: (*T1)(p1), V2: (*T2)(p2), V3: (*T3)(p3)}) { return }
				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)
				p3 = unsafe.Add(p3, s3)
			}
		}
	}
}

func (q *Query3[T1, T2, T3]) Filter3(entities []core.Entity) iter.Seq[Head3[T1, T2, T3]] {
	links := q.Reg.ArchetypeRegistry.EntityArchLinks
	return func(yield func(Head3[T1, T2, T3]) bool) {
		var lastArch *core.Archetype; var cols [3]*core.Column
		for _, e := range entities {
			link := links[e.Index()]; arch := link.Arch
			if arch == nil || q.View.Matches(arch.Mask) { continue }
			if arch != lastArch { for i := 0; i < 3; i++ { cols[i] = arch.Columns[q.CompIDs[i]] }; lastArch = arch }
			idx := uintptr(link.Row)
			if !yield(Head3[T1, T2, T3]{Entity: e, V1: (*T1)(unsafe.Add(cols[0].Data, idx*cols[0].ItemSize)), V2: (*T2)(unsafe.Add(cols[1].Data, idx*cols[1].ItemSize)), V3: (*T3)(unsafe.Add(cols[2].Data, idx*cols[2].ItemSize))}) { return }
		}
	}
}

func (q *Query3[T1, T2, T3]) PureAll3() iter.Seq[PHead3[T1, T2, T3]] {
	return func(yield func(PHead3[T1, T2, T3]) bool) {
		for i := range q.Baked {
			b := &q.Baked[i]
			p1, s1 := b.Columns[0].Data, b.Columns[0].ItemSize
			p2, s2 := b.Columns[1].Data, b.Columns[1].ItemSize
			p3, s3 := b.Columns[2].Data, b.Columns[2].ItemSize
			for j := 0; j < *b.Len; j++ {
				if !yield(PHead3[T1, T2, T3]{V1: (*T1)(p1), V2: (*T2)(p2), V3: (*T3)(p3)}) { return }
				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)
				p3 = unsafe.Add(p3, s3)
			}
		}
	}
}

func (q *Query3[T1, T2, T3]) PureFilter3(entities []core.Entity) iter.Seq[PHead3[T1, T2, T3]] {
	links := q.Reg.ArchetypeRegistry.EntityArchLinks
	return func(yield func(PHead3[T1, T2, T3]) bool) {
		var lastArch *core.Archetype; var cols [3]*core.Column
		for _, e := range entities {
			link := links[e.Index()]; arch := link.Arch
			if arch == nil || q.View.Matches(arch.Mask) { continue }
			if arch != lastArch { for i := 0; i < 3; i++ { cols[i] = arch.Columns[q.CompIDs[i]] }; lastArch = arch }
			idx := uintptr(link.Row)
			if !yield(PHead3[T1, T2, T3]{V1: (*T1)(unsafe.Add(cols[0].Data, idx*cols[0].ItemSize)), V2: (*T2)(unsafe.Add(cols[1].Data, idx*cols[1].ItemSize)), V3: (*T3)(unsafe.Add(cols[2].Data, idx*cols[2].ItemSize))}) { return }
		}
	}
}
