// Code generated by github.com/kjkrol/goke/internal/cmd/gen/views; DO NOT EDIT.
package query

import (
	"iter"
	"unsafe"

	"github.com/kjkrol/goke/internal/arch"
	"github.com/kjkrol/goke/internal/comp"
	"github.com/kjkrol/uid"
)

// --------------- View1 ---------------

// View1 iterates entities that have T1, yielding typed slices per chunk.
type View1[T1 any] struct {
	*View
}

// NewView1 creates a View for entities that have T1, filtered by opts.
func NewView1[T1 any](
	catalog *Catalog,
	opts ...comp.BlueprintOpt,
) *View1[T1] {
	var s comp.Spec1[T1]
	s.Init(catalog.cc, opts...)
	return &View1[T1]{View: catalog.AddView(&s.Blueprint)}
}

// All returns an iterator over matched entities, yielded in contiguous chunks.
//
// Example:
//
//	for chunk := range view.All() {
//		for i := range chunk.Entity {
//			_ = chunk.Entity[i]
//		}
//	}
func (v *View1[T1]) All() iter.Seq[struct {
	Entity []uid.UID64
	Comp1  []T1
}] {
	return func(yield func(
		struct {
			Entity []uid.UID64
			Comp1  []T1
		},
	) bool) {
		for _, bt := range v.BakedTables {
			for i := range bt.Table.Chunks {
				chunk := &bt.Table.Chunks[i]
				count := chunk.Len
				if count == 0 {
					continue
				}
				base := chunk.Ptr
				if !yield(
					struct {
						Entity []uid.UID64
						Comp1  []T1
					}{
						Entity: unsafe.Slice((*uid.UID64)(base), count),
						Comp1:  unsafe.Slice((*T1)(unsafe.Add(base, bt.CompOffsets[0])), count),
					}) {
					return
				}
			}
		}
	}
}

// Filter yields the subset of selected entities that match the View's filter.
func (v *View1[T1]) Filter(selected []uid.UID64) iter.Seq2[int, struct {
	Entity uid.UID64
	Comp1  *T1
}] {
	return func(yield func(int, struct {
		Entity uid.UID64
		Comp1  *T1
	}) bool) {
		entityIndex := v.EntityIndex

		var lastArchID arch.ID = arch.NullID
		var bt *BakedTable
		for i, e := range selected {
			link, ok := entityIndex.Get(e)
			if !ok {
				continue
			}
			if link.ArchId != lastArchID {
				bt = v.Get(link.ArchId)
				lastArchID = link.ArchId
			}
			if bt == nil {
				continue
			}
			physPage := &bt.Table.Chunks[link.Pos.ChunkIdx]
			slot := uintptr(link.Pos.ChunkSlot)
			c0Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[0]+(slot*bt.CompSizes[0]))
			if !yield(i, struct {
				Entity uid.UID64
				Comp1  *T1
			}{
				Entity: e,
				Comp1:  (*T1)(c0Ptr),
			}) {
				return
			}
		}
	}
}

// --------------- View2 ---------------

// View2 iterates entities that have T1, T2, yielding typed slices per chunk.
type View2[T1 any, T2 any] struct {
	*View
}

// NewView2 creates a View for entities that have T1, T2, filtered by opts.
func NewView2[T1 any, T2 any](
	catalog *Catalog,
	opts ...comp.BlueprintOpt,
) *View2[T1, T2] {
	var s comp.Spec2[T1, T2]
	s.Init(catalog.cc, opts...)
	return &View2[T1, T2]{View: catalog.AddView(&s.Blueprint)}
}

// All returns an iterator over matched entities, yielded in contiguous chunks.
//
// Example:
//
//	for chunk := range view.All() {
//		for i := range chunk.Entity {
//			_ = chunk.Entity[i]
//		}
//	}
func (v *View2[T1, T2]) All() iter.Seq[struct {
	Entity []uid.UID64
	Comp1  []T1
	Comp2  []T2
}] {
	return func(yield func(
		struct {
			Entity []uid.UID64
			Comp1  []T1
			Comp2  []T2
		},
	) bool) {
		for _, bt := range v.BakedTables {
			for i := range bt.Table.Chunks {
				chunk := &bt.Table.Chunks[i]
				count := chunk.Len
				if count == 0 {
					continue
				}
				base := chunk.Ptr
				if !yield(
					struct {
						Entity []uid.UID64
						Comp1  []T1
						Comp2  []T2
					}{
						Entity: unsafe.Slice((*uid.UID64)(base), count),
						Comp1:  unsafe.Slice((*T1)(unsafe.Add(base, bt.CompOffsets[0])), count),
						Comp2:  unsafe.Slice((*T2)(unsafe.Add(base, bt.CompOffsets[1])), count),
					}) {
					return
				}
			}
		}
	}
}

// Filter yields the subset of selected entities that match the View's filter.
func (v *View2[T1, T2]) Filter(selected []uid.UID64) iter.Seq2[int, struct {
	Entity uid.UID64
	Comp1  *T1
	Comp2  *T2
}] {
	return func(yield func(int, struct {
		Entity uid.UID64
		Comp1  *T1
		Comp2  *T2
	}) bool) {
		entityIndex := v.EntityIndex

		var lastArchID arch.ID = arch.NullID
		var bt *BakedTable
		for i, e := range selected {
			link, ok := entityIndex.Get(e)
			if !ok {
				continue
			}
			if link.ArchId != lastArchID {
				bt = v.Get(link.ArchId)
				lastArchID = link.ArchId
			}
			if bt == nil {
				continue
			}
			physPage := &bt.Table.Chunks[link.Pos.ChunkIdx]
			slot := uintptr(link.Pos.ChunkSlot)
			c0Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[0]+(slot*bt.CompSizes[0]))
			c1Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[1]+(slot*bt.CompSizes[1]))
			if !yield(i, struct {
				Entity uid.UID64
				Comp1  *T1
				Comp2  *T2
			}{
				Entity: e,
				Comp1:  (*T1)(c0Ptr),
				Comp2:  (*T2)(c1Ptr),
			}) {
				return
			}
		}
	}
}

// --------------- View3 ---------------

// View3 iterates entities that have T1, T2, T3, yielding typed slices per chunk.
type View3[T1 any, T2 any, T3 any] struct {
	*View
}

// NewView3 creates a View for entities that have T1, T2, T3, filtered by opts.
func NewView3[T1 any, T2 any, T3 any](
	catalog *Catalog,
	opts ...comp.BlueprintOpt,
) *View3[T1, T2, T3] {
	var s comp.Spec3[T1, T2, T3]
	s.Init(catalog.cc, opts...)
	return &View3[T1, T2, T3]{View: catalog.AddView(&s.Blueprint)}
}

// All returns an iterator over matched entities, yielded in contiguous chunks.
//
// Example:
//
//	for chunk := range view.All() {
//		for i := range chunk.Entity {
//			_ = chunk.Entity[i]
//		}
//	}
func (v *View3[T1, T2, T3]) All() iter.Seq[struct {
	Entity []uid.UID64
	Comp1  []T1
	Comp2  []T2
	Comp3  []T3
}] {
	return func(yield func(
		struct {
			Entity []uid.UID64
			Comp1  []T1
			Comp2  []T2
			Comp3  []T3
		},
	) bool) {
		for _, bt := range v.BakedTables {
			for i := range bt.Table.Chunks {
				chunk := &bt.Table.Chunks[i]
				count := chunk.Len
				if count == 0 {
					continue
				}
				base := chunk.Ptr
				if !yield(
					struct {
						Entity []uid.UID64
						Comp1  []T1
						Comp2  []T2
						Comp3  []T3
					}{
						Entity: unsafe.Slice((*uid.UID64)(base), count),
						Comp1:  unsafe.Slice((*T1)(unsafe.Add(base, bt.CompOffsets[0])), count),
						Comp2:  unsafe.Slice((*T2)(unsafe.Add(base, bt.CompOffsets[1])), count),
						Comp3:  unsafe.Slice((*T3)(unsafe.Add(base, bt.CompOffsets[2])), count),
					}) {
					return
				}
			}
		}
	}
}

// Filter yields the subset of selected entities that match the View's filter.
func (v *View3[T1, T2, T3]) Filter(selected []uid.UID64) iter.Seq2[int, struct {
	Entity uid.UID64
	Comp1  *T1
	Comp2  *T2
	Comp3  *T3
}] {
	return func(yield func(int, struct {
		Entity uid.UID64
		Comp1  *T1
		Comp2  *T2
		Comp3  *T3
	}) bool) {
		entityIndex := v.EntityIndex

		var lastArchID arch.ID = arch.NullID
		var bt *BakedTable
		for i, e := range selected {
			link, ok := entityIndex.Get(e)
			if !ok {
				continue
			}
			if link.ArchId != lastArchID {
				bt = v.Get(link.ArchId)
				lastArchID = link.ArchId
			}
			if bt == nil {
				continue
			}
			physPage := &bt.Table.Chunks[link.Pos.ChunkIdx]
			slot := uintptr(link.Pos.ChunkSlot)
			c0Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[0]+(slot*bt.CompSizes[0]))
			c1Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[1]+(slot*bt.CompSizes[1]))
			c2Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[2]+(slot*bt.CompSizes[2]))
			if !yield(i, struct {
				Entity uid.UID64
				Comp1  *T1
				Comp2  *T2
				Comp3  *T3
			}{
				Entity: e,
				Comp1:  (*T1)(c0Ptr),
				Comp2:  (*T2)(c1Ptr),
				Comp3:  (*T3)(c2Ptr),
			}) {
				return
			}
		}
	}
}

// --------------- View4 ---------------

// View4 iterates entities that have T1, T2, T3, T4, yielding typed slices per chunk.
type View4[T1 any, T2 any, T3 any, T4 any] struct {
	*View
}

// NewView4 creates a View for entities that have T1, T2, T3, T4, filtered by opts.
func NewView4[T1 any, T2 any, T3 any, T4 any](
	catalog *Catalog,
	opts ...comp.BlueprintOpt,
) *View4[T1, T2, T3, T4] {
	var s comp.Spec4[T1, T2, T3, T4]
	s.Init(catalog.cc, opts...)
	return &View4[T1, T2, T3, T4]{View: catalog.AddView(&s.Blueprint)}
}

// All returns an iterator over matched entities, yielded in contiguous chunks.
//
// Example:
//
//	for chunk := range view.All() {
//		for i := range chunk.Entity {
//			_ = chunk.Entity[i]
//		}
//	}
func (v *View4[T1, T2, T3, T4]) All() iter.Seq[struct {
	Entity []uid.UID64
	Comp1  []T1
	Comp2  []T2
	Comp3  []T3
	Comp4  []T4
}] {
	return func(yield func(
		struct {
			Entity []uid.UID64
			Comp1  []T1
			Comp2  []T2
			Comp3  []T3
			Comp4  []T4
		},
	) bool) {
		for _, bt := range v.BakedTables {
			for i := range bt.Table.Chunks {
				chunk := &bt.Table.Chunks[i]
				count := chunk.Len
				if count == 0 {
					continue
				}
				base := chunk.Ptr
				if !yield(
					struct {
						Entity []uid.UID64
						Comp1  []T1
						Comp2  []T2
						Comp3  []T3
						Comp4  []T4
					}{
						Entity: unsafe.Slice((*uid.UID64)(base), count),
						Comp1:  unsafe.Slice((*T1)(unsafe.Add(base, bt.CompOffsets[0])), count),
						Comp2:  unsafe.Slice((*T2)(unsafe.Add(base, bt.CompOffsets[1])), count),
						Comp3:  unsafe.Slice((*T3)(unsafe.Add(base, bt.CompOffsets[2])), count),
						Comp4:  unsafe.Slice((*T4)(unsafe.Add(base, bt.CompOffsets[3])), count),
					}) {
					return
				}
			}
		}
	}
}

// Filter yields the subset of selected entities that match the View's filter.
func (v *View4[T1, T2, T3, T4]) Filter(selected []uid.UID64) iter.Seq2[int, struct {
	Entity uid.UID64
	Comp1  *T1
	Comp2  *T2
	Comp3  *T3
	Comp4  *T4
}] {
	return func(yield func(int, struct {
		Entity uid.UID64
		Comp1  *T1
		Comp2  *T2
		Comp3  *T3
		Comp4  *T4
	}) bool) {
		entityIndex := v.EntityIndex

		var lastArchID arch.ID = arch.NullID
		var bt *BakedTable
		for i, e := range selected {
			link, ok := entityIndex.Get(e)
			if !ok {
				continue
			}
			if link.ArchId != lastArchID {
				bt = v.Get(link.ArchId)
				lastArchID = link.ArchId
			}
			if bt == nil {
				continue
			}
			physPage := &bt.Table.Chunks[link.Pos.ChunkIdx]
			slot := uintptr(link.Pos.ChunkSlot)
			c0Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[0]+(slot*bt.CompSizes[0]))
			c1Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[1]+(slot*bt.CompSizes[1]))
			c2Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[2]+(slot*bt.CompSizes[2]))
			c3Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[3]+(slot*bt.CompSizes[3]))
			if !yield(i, struct {
				Entity uid.UID64
				Comp1  *T1
				Comp2  *T2
				Comp3  *T3
				Comp4  *T4
			}{
				Entity: e,
				Comp1:  (*T1)(c0Ptr),
				Comp2:  (*T2)(c1Ptr),
				Comp3:  (*T3)(c2Ptr),
				Comp4:  (*T4)(c3Ptr),
			}) {
				return
			}
		}
	}
}

// --------------- View5 ---------------

// View5 iterates entities that have T1, T2, T3, T4, T5, yielding typed slices per chunk.
type View5[T1 any, T2 any, T3 any, T4 any, T5 any] struct {
	*View
}

// NewView5 creates a View for entities that have T1, T2, T3, T4, T5, filtered by opts.
func NewView5[T1 any, T2 any, T3 any, T4 any, T5 any](
	catalog *Catalog,
	opts ...comp.BlueprintOpt,
) *View5[T1, T2, T3, T4, T5] {
	var s comp.Spec5[T1, T2, T3, T4, T5]
	s.Init(catalog.cc, opts...)
	return &View5[T1, T2, T3, T4, T5]{View: catalog.AddView(&s.Blueprint)}
}

// All returns an iterator over matched entities, yielded in contiguous chunks.
//
// Example:
//
//	for chunk := range view.All() {
//		for i := range chunk.Entity {
//			_ = chunk.Entity[i]
//		}
//	}
func (v *View5[T1, T2, T3, T4, T5]) All() iter.Seq[struct {
	Entity []uid.UID64
	Comp1  []T1
	Comp2  []T2
	Comp3  []T3
	Comp4  []T4
	Comp5  []T5
}] {
	return func(yield func(
		struct {
			Entity []uid.UID64
			Comp1  []T1
			Comp2  []T2
			Comp3  []T3
			Comp4  []T4
			Comp5  []T5
		},
	) bool) {
		for _, bt := range v.BakedTables {
			for i := range bt.Table.Chunks {
				chunk := &bt.Table.Chunks[i]
				count := chunk.Len
				if count == 0 {
					continue
				}
				base := chunk.Ptr
				if !yield(
					struct {
						Entity []uid.UID64
						Comp1  []T1
						Comp2  []T2
						Comp3  []T3
						Comp4  []T4
						Comp5  []T5
					}{
						Entity: unsafe.Slice((*uid.UID64)(base), count),
						Comp1:  unsafe.Slice((*T1)(unsafe.Add(base, bt.CompOffsets[0])), count),
						Comp2:  unsafe.Slice((*T2)(unsafe.Add(base, bt.CompOffsets[1])), count),
						Comp3:  unsafe.Slice((*T3)(unsafe.Add(base, bt.CompOffsets[2])), count),
						Comp4:  unsafe.Slice((*T4)(unsafe.Add(base, bt.CompOffsets[3])), count),
						Comp5:  unsafe.Slice((*T5)(unsafe.Add(base, bt.CompOffsets[4])), count),
					}) {
					return
				}
			}
		}
	}
}

// Filter yields the subset of selected entities that match the View's filter.
func (v *View5[T1, T2, T3, T4, T5]) Filter(selected []uid.UID64) iter.Seq2[int, struct {
	Entity uid.UID64
	Comp1  *T1
	Comp2  *T2
	Comp3  *T3
	Comp4  *T4
	Comp5  *T5
}] {
	return func(yield func(int, struct {
		Entity uid.UID64
		Comp1  *T1
		Comp2  *T2
		Comp3  *T3
		Comp4  *T4
		Comp5  *T5
	}) bool) {
		entityIndex := v.EntityIndex

		var lastArchID arch.ID = arch.NullID
		var bt *BakedTable
		for i, e := range selected {
			link, ok := entityIndex.Get(e)
			if !ok {
				continue
			}
			if link.ArchId != lastArchID {
				bt = v.Get(link.ArchId)
				lastArchID = link.ArchId
			}
			if bt == nil {
				continue
			}
			physPage := &bt.Table.Chunks[link.Pos.ChunkIdx]
			slot := uintptr(link.Pos.ChunkSlot)
			c0Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[0]+(slot*bt.CompSizes[0]))
			c1Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[1]+(slot*bt.CompSizes[1]))
			c2Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[2]+(slot*bt.CompSizes[2]))
			c3Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[3]+(slot*bt.CompSizes[3]))
			c4Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[4]+(slot*bt.CompSizes[4]))
			if !yield(i, struct {
				Entity uid.UID64
				Comp1  *T1
				Comp2  *T2
				Comp3  *T3
				Comp4  *T4
				Comp5  *T5
			}{
				Entity: e,
				Comp1:  (*T1)(c0Ptr),
				Comp2:  (*T2)(c1Ptr),
				Comp3:  (*T3)(c2Ptr),
				Comp4:  (*T4)(c3Ptr),
				Comp5:  (*T5)(c4Ptr),
			}) {
				return
			}
		}
	}
}

// --------------- View6 ---------------

// View6 iterates entities that have T1, T2, T3, T4, T5, T6, yielding typed slices per chunk.
type View6[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any] struct {
	*View
}

// NewView6 creates a View for entities that have T1, T2, T3, T4, T5, T6, filtered by opts.
func NewView6[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any](
	catalog *Catalog,
	opts ...comp.BlueprintOpt,
) *View6[T1, T2, T3, T4, T5, T6] {
	var s comp.Spec6[T1, T2, T3, T4, T5, T6]
	s.Init(catalog.cc, opts...)
	return &View6[T1, T2, T3, T4, T5, T6]{View: catalog.AddView(&s.Blueprint)}
}

// All returns an iterator over matched entities, yielded in contiguous chunks.
//
// Example:
//
//	for chunk := range view.All() {
//		for i := range chunk.Entity {
//			_ = chunk.Entity[i]
//		}
//	}
func (v *View6[T1, T2, T3, T4, T5, T6]) All() iter.Seq[struct {
	Entity []uid.UID64
	Comp1  []T1
	Comp2  []T2
	Comp3  []T3
	Comp4  []T4
	Comp5  []T5
	Comp6  []T6
}] {
	return func(yield func(
		struct {
			Entity []uid.UID64
			Comp1  []T1
			Comp2  []T2
			Comp3  []T3
			Comp4  []T4
			Comp5  []T5
			Comp6  []T6
		},
	) bool) {
		for _, bt := range v.BakedTables {
			for i := range bt.Table.Chunks {
				chunk := &bt.Table.Chunks[i]
				count := chunk.Len
				if count == 0 {
					continue
				}
				base := chunk.Ptr
				if !yield(
					struct {
						Entity []uid.UID64
						Comp1  []T1
						Comp2  []T2
						Comp3  []T3
						Comp4  []T4
						Comp5  []T5
						Comp6  []T6
					}{
						Entity: unsafe.Slice((*uid.UID64)(base), count),
						Comp1:  unsafe.Slice((*T1)(unsafe.Add(base, bt.CompOffsets[0])), count),
						Comp2:  unsafe.Slice((*T2)(unsafe.Add(base, bt.CompOffsets[1])), count),
						Comp3:  unsafe.Slice((*T3)(unsafe.Add(base, bt.CompOffsets[2])), count),
						Comp4:  unsafe.Slice((*T4)(unsafe.Add(base, bt.CompOffsets[3])), count),
						Comp5:  unsafe.Slice((*T5)(unsafe.Add(base, bt.CompOffsets[4])), count),
						Comp6:  unsafe.Slice((*T6)(unsafe.Add(base, bt.CompOffsets[5])), count),
					}) {
					return
				}
			}
		}
	}
}

// Filter yields the subset of selected entities that match the View's filter.
func (v *View6[T1, T2, T3, T4, T5, T6]) Filter(selected []uid.UID64) iter.Seq2[int, struct {
	Entity uid.UID64
	Comp1  *T1
	Comp2  *T2
	Comp3  *T3
	Comp4  *T4
	Comp5  *T5
	Comp6  *T6
}] {
	return func(yield func(int, struct {
		Entity uid.UID64
		Comp1  *T1
		Comp2  *T2
		Comp3  *T3
		Comp4  *T4
		Comp5  *T5
		Comp6  *T6
	}) bool) {
		entityIndex := v.EntityIndex

		var lastArchID arch.ID = arch.NullID
		var bt *BakedTable
		for i, e := range selected {
			link, ok := entityIndex.Get(e)
			if !ok {
				continue
			}
			if link.ArchId != lastArchID {
				bt = v.Get(link.ArchId)
				lastArchID = link.ArchId
			}
			if bt == nil {
				continue
			}
			physPage := &bt.Table.Chunks[link.Pos.ChunkIdx]
			slot := uintptr(link.Pos.ChunkSlot)
			c0Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[0]+(slot*bt.CompSizes[0]))
			c1Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[1]+(slot*bt.CompSizes[1]))
			c2Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[2]+(slot*bt.CompSizes[2]))
			c3Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[3]+(slot*bt.CompSizes[3]))
			c4Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[4]+(slot*bt.CompSizes[4]))
			c5Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[5]+(slot*bt.CompSizes[5]))
			if !yield(i, struct {
				Entity uid.UID64
				Comp1  *T1
				Comp2  *T2
				Comp3  *T3
				Comp4  *T4
				Comp5  *T5
				Comp6  *T6
			}{
				Entity: e,
				Comp1:  (*T1)(c0Ptr),
				Comp2:  (*T2)(c1Ptr),
				Comp3:  (*T3)(c2Ptr),
				Comp4:  (*T4)(c3Ptr),
				Comp5:  (*T5)(c4Ptr),
				Comp6:  (*T6)(c5Ptr),
			}) {
				return
			}
		}
	}
}

// --------------- View7 ---------------

// View7 iterates entities that have T1, T2, T3, T4, T5, T6, T7, yielding typed slices per chunk.
type View7[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any] struct {
	*View
}

// NewView7 creates a View for entities that have T1, T2, T3, T4, T5, T6, T7, filtered by opts.
func NewView7[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any](
	catalog *Catalog,
	opts ...comp.BlueprintOpt,
) *View7[T1, T2, T3, T4, T5, T6, T7] {
	var s comp.Spec7[T1, T2, T3, T4, T5, T6, T7]
	s.Init(catalog.cc, opts...)
	return &View7[T1, T2, T3, T4, T5, T6, T7]{View: catalog.AddView(&s.Blueprint)}
}

// All returns an iterator over matched entities, yielded in contiguous chunks.
//
// Example:
//
//	for chunk := range view.All() {
//		for i := range chunk.Entity {
//			_ = chunk.Entity[i]
//		}
//	}
func (v *View7[T1, T2, T3, T4, T5, T6, T7]) All() iter.Seq[struct {
	Entity []uid.UID64
	Comp1  []T1
	Comp2  []T2
	Comp3  []T3
	Comp4  []T4
	Comp5  []T5
	Comp6  []T6
	Comp7  []T7
}] {
	return func(yield func(
		struct {
			Entity []uid.UID64
			Comp1  []T1
			Comp2  []T2
			Comp3  []T3
			Comp4  []T4
			Comp5  []T5
			Comp6  []T6
			Comp7  []T7
		},
	) bool) {
		for _, bt := range v.BakedTables {
			for i := range bt.Table.Chunks {
				chunk := &bt.Table.Chunks[i]
				count := chunk.Len
				if count == 0 {
					continue
				}
				base := chunk.Ptr
				if !yield(
					struct {
						Entity []uid.UID64
						Comp1  []T1
						Comp2  []T2
						Comp3  []T3
						Comp4  []T4
						Comp5  []T5
						Comp6  []T6
						Comp7  []T7
					}{
						Entity: unsafe.Slice((*uid.UID64)(base), count),
						Comp1:  unsafe.Slice((*T1)(unsafe.Add(base, bt.CompOffsets[0])), count),
						Comp2:  unsafe.Slice((*T2)(unsafe.Add(base, bt.CompOffsets[1])), count),
						Comp3:  unsafe.Slice((*T3)(unsafe.Add(base, bt.CompOffsets[2])), count),
						Comp4:  unsafe.Slice((*T4)(unsafe.Add(base, bt.CompOffsets[3])), count),
						Comp5:  unsafe.Slice((*T5)(unsafe.Add(base, bt.CompOffsets[4])), count),
						Comp6:  unsafe.Slice((*T6)(unsafe.Add(base, bt.CompOffsets[5])), count),
						Comp7:  unsafe.Slice((*T7)(unsafe.Add(base, bt.CompOffsets[6])), count),
					}) {
					return
				}
			}
		}
	}
}

// Filter yields the subset of selected entities that match the View's filter.
func (v *View7[T1, T2, T3, T4, T5, T6, T7]) Filter(selected []uid.UID64) iter.Seq2[int, struct {
	Entity uid.UID64
	Comp1  *T1
	Comp2  *T2
	Comp3  *T3
	Comp4  *T4
	Comp5  *T5
	Comp6  *T6
	Comp7  *T7
}] {
	return func(yield func(int, struct {
		Entity uid.UID64
		Comp1  *T1
		Comp2  *T2
		Comp3  *T3
		Comp4  *T4
		Comp5  *T5
		Comp6  *T6
		Comp7  *T7
	}) bool) {
		entityIndex := v.EntityIndex

		var lastArchID arch.ID = arch.NullID
		var bt *BakedTable
		for i, e := range selected {
			link, ok := entityIndex.Get(e)
			if !ok {
				continue
			}
			if link.ArchId != lastArchID {
				bt = v.Get(link.ArchId)
				lastArchID = link.ArchId
			}
			if bt == nil {
				continue
			}
			physPage := &bt.Table.Chunks[link.Pos.ChunkIdx]
			slot := uintptr(link.Pos.ChunkSlot)
			c0Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[0]+(slot*bt.CompSizes[0]))
			c1Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[1]+(slot*bt.CompSizes[1]))
			c2Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[2]+(slot*bt.CompSizes[2]))
			c3Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[3]+(slot*bt.CompSizes[3]))
			c4Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[4]+(slot*bt.CompSizes[4]))
			c5Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[5]+(slot*bt.CompSizes[5]))
			c6Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[6]+(slot*bt.CompSizes[6]))
			if !yield(i, struct {
				Entity uid.UID64
				Comp1  *T1
				Comp2  *T2
				Comp3  *T3
				Comp4  *T4
				Comp5  *T5
				Comp6  *T6
				Comp7  *T7
			}{
				Entity: e,
				Comp1:  (*T1)(c0Ptr),
				Comp2:  (*T2)(c1Ptr),
				Comp3:  (*T3)(c2Ptr),
				Comp4:  (*T4)(c3Ptr),
				Comp5:  (*T5)(c4Ptr),
				Comp6:  (*T6)(c5Ptr),
				Comp7:  (*T7)(c6Ptr),
			}) {
				return
			}
		}
	}
}

// --------------- View8 ---------------

// View8 iterates entities that have T1, T2, T3, T4, T5, T6, T7, T8, yielding typed slices per chunk.
type View8[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any, T8 any] struct {
	*View
}

// NewView8 creates a View for entities that have T1, T2, T3, T4, T5, T6, T7, T8, filtered by opts.
func NewView8[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any, T8 any](
	catalog *Catalog,
	opts ...comp.BlueprintOpt,
) *View8[T1, T2, T3, T4, T5, T6, T7, T8] {
	var s comp.Spec8[T1, T2, T3, T4, T5, T6, T7, T8]
	s.Init(catalog.cc, opts...)
	return &View8[T1, T2, T3, T4, T5, T6, T7, T8]{View: catalog.AddView(&s.Blueprint)}
}

// All returns an iterator over matched entities, yielded in contiguous chunks.
//
// Example:
//
//	for chunk := range view.All() {
//		for i := range chunk.Entity {
//			_ = chunk.Entity[i]
//		}
//	}
func (v *View8[T1, T2, T3, T4, T5, T6, T7, T8]) All() iter.Seq[struct {
	Entity []uid.UID64
	Comp1  []T1
	Comp2  []T2
	Comp3  []T3
	Comp4  []T4
	Comp5  []T5
	Comp6  []T6
	Comp7  []T7
	Comp8  []T8
}] {
	return func(yield func(
		struct {
			Entity []uid.UID64
			Comp1  []T1
			Comp2  []T2
			Comp3  []T3
			Comp4  []T4
			Comp5  []T5
			Comp6  []T6
			Comp7  []T7
			Comp8  []T8
		},
	) bool) {
		for _, bt := range v.BakedTables {
			for i := range bt.Table.Chunks {
				chunk := &bt.Table.Chunks[i]
				count := chunk.Len
				if count == 0 {
					continue
				}
				base := chunk.Ptr
				if !yield(
					struct {
						Entity []uid.UID64
						Comp1  []T1
						Comp2  []T2
						Comp3  []T3
						Comp4  []T4
						Comp5  []T5
						Comp6  []T6
						Comp7  []T7
						Comp8  []T8
					}{
						Entity: unsafe.Slice((*uid.UID64)(base), count),
						Comp1:  unsafe.Slice((*T1)(unsafe.Add(base, bt.CompOffsets[0])), count),
						Comp2:  unsafe.Slice((*T2)(unsafe.Add(base, bt.CompOffsets[1])), count),
						Comp3:  unsafe.Slice((*T3)(unsafe.Add(base, bt.CompOffsets[2])), count),
						Comp4:  unsafe.Slice((*T4)(unsafe.Add(base, bt.CompOffsets[3])), count),
						Comp5:  unsafe.Slice((*T5)(unsafe.Add(base, bt.CompOffsets[4])), count),
						Comp6:  unsafe.Slice((*T6)(unsafe.Add(base, bt.CompOffsets[5])), count),
						Comp7:  unsafe.Slice((*T7)(unsafe.Add(base, bt.CompOffsets[6])), count),
						Comp8:  unsafe.Slice((*T8)(unsafe.Add(base, bt.CompOffsets[7])), count),
					}) {
					return
				}
			}
		}
	}
}

// Filter yields the subset of selected entities that match the View's filter.
func (v *View8[T1, T2, T3, T4, T5, T6, T7, T8]) Filter(selected []uid.UID64) iter.Seq2[int, struct {
	Entity uid.UID64
	Comp1  *T1
	Comp2  *T2
	Comp3  *T3
	Comp4  *T4
	Comp5  *T5
	Comp6  *T6
	Comp7  *T7
	Comp8  *T8
}] {
	return func(yield func(int, struct {
		Entity uid.UID64
		Comp1  *T1
		Comp2  *T2
		Comp3  *T3
		Comp4  *T4
		Comp5  *T5
		Comp6  *T6
		Comp7  *T7
		Comp8  *T8
	}) bool) {
		entityIndex := v.EntityIndex

		var lastArchID arch.ID = arch.NullID
		var bt *BakedTable
		for i, e := range selected {
			link, ok := entityIndex.Get(e)
			if !ok {
				continue
			}
			if link.ArchId != lastArchID {
				bt = v.Get(link.ArchId)
				lastArchID = link.ArchId
			}
			if bt == nil {
				continue
			}
			physPage := &bt.Table.Chunks[link.Pos.ChunkIdx]
			slot := uintptr(link.Pos.ChunkSlot)
			c0Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[0]+(slot*bt.CompSizes[0]))
			c1Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[1]+(slot*bt.CompSizes[1]))
			c2Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[2]+(slot*bt.CompSizes[2]))
			c3Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[3]+(slot*bt.CompSizes[3]))
			c4Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[4]+(slot*bt.CompSizes[4]))
			c5Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[5]+(slot*bt.CompSizes[5]))
			c6Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[6]+(slot*bt.CompSizes[6]))
			c7Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[7]+(slot*bt.CompSizes[7]))
			if !yield(i, struct {
				Entity uid.UID64
				Comp1  *T1
				Comp2  *T2
				Comp3  *T3
				Comp4  *T4
				Comp5  *T5
				Comp6  *T6
				Comp7  *T7
				Comp8  *T8
			}{
				Entity: e,
				Comp1:  (*T1)(c0Ptr),
				Comp2:  (*T2)(c1Ptr),
				Comp3:  (*T3)(c2Ptr),
				Comp4:  (*T4)(c3Ptr),
				Comp5:  (*T5)(c4Ptr),
				Comp6:  (*T6)(c5Ptr),
				Comp7:  (*T7)(c6Ptr),
				Comp8:  (*T8)(c7Ptr),
			}) {
				return
			}
		}
	}
}

// --------------- View9 ---------------

// View9 iterates entities that have T1, T2, T3, T4, T5, T6, T7, T8, T9, yielding typed slices per chunk.
type View9[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any, T8 any, T9 any] struct {
	*View
}

// NewView9 creates a View for entities that have T1, T2, T3, T4, T5, T6, T7, T8, T9, filtered by opts.
func NewView9[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any, T8 any, T9 any](
	catalog *Catalog,
	opts ...comp.BlueprintOpt,
) *View9[T1, T2, T3, T4, T5, T6, T7, T8, T9] {
	var s comp.Spec9[T1, T2, T3, T4, T5, T6, T7, T8, T9]
	s.Init(catalog.cc, opts...)
	return &View9[T1, T2, T3, T4, T5, T6, T7, T8, T9]{View: catalog.AddView(&s.Blueprint)}
}

// All returns an iterator over matched entities, yielded in contiguous chunks.
//
// Example:
//
//	for chunk := range view.All() {
//		for i := range chunk.Entity {
//			_ = chunk.Entity[i]
//		}
//	}
func (v *View9[T1, T2, T3, T4, T5, T6, T7, T8, T9]) All() iter.Seq[struct {
	Entity []uid.UID64
	Comp1  []T1
	Comp2  []T2
	Comp3  []T3
	Comp4  []T4
	Comp5  []T5
	Comp6  []T6
	Comp7  []T7
	Comp8  []T8
	Comp9  []T9
}] {
	return func(yield func(
		struct {
			Entity []uid.UID64
			Comp1  []T1
			Comp2  []T2
			Comp3  []T3
			Comp4  []T4
			Comp5  []T5
			Comp6  []T6
			Comp7  []T7
			Comp8  []T8
			Comp9  []T9
		},
	) bool) {
		for _, bt := range v.BakedTables {
			for i := range bt.Table.Chunks {
				chunk := &bt.Table.Chunks[i]
				count := chunk.Len
				if count == 0 {
					continue
				}
				base := chunk.Ptr
				if !yield(
					struct {
						Entity []uid.UID64
						Comp1  []T1
						Comp2  []T2
						Comp3  []T3
						Comp4  []T4
						Comp5  []T5
						Comp6  []T6
						Comp7  []T7
						Comp8  []T8
						Comp9  []T9
					}{
						Entity: unsafe.Slice((*uid.UID64)(base), count),
						Comp1:  unsafe.Slice((*T1)(unsafe.Add(base, bt.CompOffsets[0])), count),
						Comp2:  unsafe.Slice((*T2)(unsafe.Add(base, bt.CompOffsets[1])), count),
						Comp3:  unsafe.Slice((*T3)(unsafe.Add(base, bt.CompOffsets[2])), count),
						Comp4:  unsafe.Slice((*T4)(unsafe.Add(base, bt.CompOffsets[3])), count),
						Comp5:  unsafe.Slice((*T5)(unsafe.Add(base, bt.CompOffsets[4])), count),
						Comp6:  unsafe.Slice((*T6)(unsafe.Add(base, bt.CompOffsets[5])), count),
						Comp7:  unsafe.Slice((*T7)(unsafe.Add(base, bt.CompOffsets[6])), count),
						Comp8:  unsafe.Slice((*T8)(unsafe.Add(base, bt.CompOffsets[7])), count),
						Comp9:  unsafe.Slice((*T9)(unsafe.Add(base, bt.CompOffsets[8])), count),
					}) {
					return
				}
			}
		}
	}
}

// Filter yields the subset of selected entities that match the View's filter.
func (v *View9[T1, T2, T3, T4, T5, T6, T7, T8, T9]) Filter(selected []uid.UID64) iter.Seq2[int, struct {
	Entity uid.UID64
	Comp1  *T1
	Comp2  *T2
	Comp3  *T3
	Comp4  *T4
	Comp5  *T5
	Comp6  *T6
	Comp7  *T7
	Comp8  *T8
	Comp9  *T9
}] {
	return func(yield func(int, struct {
		Entity uid.UID64
		Comp1  *T1
		Comp2  *T2
		Comp3  *T3
		Comp4  *T4
		Comp5  *T5
		Comp6  *T6
		Comp7  *T7
		Comp8  *T8
		Comp9  *T9
	}) bool) {
		entityIndex := v.EntityIndex

		var lastArchID arch.ID = arch.NullID
		var bt *BakedTable
		for i, e := range selected {
			link, ok := entityIndex.Get(e)
			if !ok {
				continue
			}
			if link.ArchId != lastArchID {
				bt = v.Get(link.ArchId)
				lastArchID = link.ArchId
			}
			if bt == nil {
				continue
			}
			physPage := &bt.Table.Chunks[link.Pos.ChunkIdx]
			slot := uintptr(link.Pos.ChunkSlot)
			c0Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[0]+(slot*bt.CompSizes[0]))
			c1Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[1]+(slot*bt.CompSizes[1]))
			c2Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[2]+(slot*bt.CompSizes[2]))
			c3Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[3]+(slot*bt.CompSizes[3]))
			c4Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[4]+(slot*bt.CompSizes[4]))
			c5Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[5]+(slot*bt.CompSizes[5]))
			c6Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[6]+(slot*bt.CompSizes[6]))
			c7Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[7]+(slot*bt.CompSizes[7]))
			c8Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[8]+(slot*bt.CompSizes[8]))
			if !yield(i, struct {
				Entity uid.UID64
				Comp1  *T1
				Comp2  *T2
				Comp3  *T3
				Comp4  *T4
				Comp5  *T5
				Comp6  *T6
				Comp7  *T7
				Comp8  *T8
				Comp9  *T9
			}{
				Entity: e,
				Comp1:  (*T1)(c0Ptr),
				Comp2:  (*T2)(c1Ptr),
				Comp3:  (*T3)(c2Ptr),
				Comp4:  (*T4)(c3Ptr),
				Comp5:  (*T5)(c4Ptr),
				Comp6:  (*T6)(c5Ptr),
				Comp7:  (*T7)(c6Ptr),
				Comp8:  (*T8)(c7Ptr),
				Comp9:  (*T9)(c8Ptr),
			}) {
				return
			}
		}
	}
}

// --------------- View10 ---------------

// View10 iterates entities that have T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, yielding typed slices per chunk.
type View10[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any, T8 any, T9 any, T10 any] struct {
	*View
}

// NewView10 creates a View for entities that have T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, filtered by opts.
func NewView10[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any, T8 any, T9 any, T10 any](
	catalog *Catalog,
	opts ...comp.BlueprintOpt,
) *View10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10] {
	var s comp.Spec10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]
	s.Init(catalog.cc, opts...)
	return &View10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]{View: catalog.AddView(&s.Blueprint)}
}

// All returns an iterator over matched entities, yielded in contiguous chunks.
//
// Example:
//
//	for chunk := range view.All() {
//		for i := range chunk.Entity {
//			_ = chunk.Entity[i]
//		}
//	}
func (v *View10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]) All() iter.Seq[struct {
	Entity []uid.UID64
	Comp1  []T1
	Comp2  []T2
	Comp3  []T3
	Comp4  []T4
	Comp5  []T5
	Comp6  []T6
	Comp7  []T7
	Comp8  []T8
	Comp9  []T9
	Comp10 []T10
}] {
	return func(yield func(
		struct {
			Entity []uid.UID64
			Comp1  []T1
			Comp2  []T2
			Comp3  []T3
			Comp4  []T4
			Comp5  []T5
			Comp6  []T6
			Comp7  []T7
			Comp8  []T8
			Comp9  []T9
			Comp10 []T10
		},
	) bool) {
		for _, bt := range v.BakedTables {
			for i := range bt.Table.Chunks {
				chunk := &bt.Table.Chunks[i]
				count := chunk.Len
				if count == 0 {
					continue
				}
				base := chunk.Ptr
				if !yield(
					struct {
						Entity []uid.UID64
						Comp1  []T1
						Comp2  []T2
						Comp3  []T3
						Comp4  []T4
						Comp5  []T5
						Comp6  []T6
						Comp7  []T7
						Comp8  []T8
						Comp9  []T9
						Comp10 []T10
					}{
						Entity: unsafe.Slice((*uid.UID64)(base), count),
						Comp1:  unsafe.Slice((*T1)(unsafe.Add(base, bt.CompOffsets[0])), count),
						Comp2:  unsafe.Slice((*T2)(unsafe.Add(base, bt.CompOffsets[1])), count),
						Comp3:  unsafe.Slice((*T3)(unsafe.Add(base, bt.CompOffsets[2])), count),
						Comp4:  unsafe.Slice((*T4)(unsafe.Add(base, bt.CompOffsets[3])), count),
						Comp5:  unsafe.Slice((*T5)(unsafe.Add(base, bt.CompOffsets[4])), count),
						Comp6:  unsafe.Slice((*T6)(unsafe.Add(base, bt.CompOffsets[5])), count),
						Comp7:  unsafe.Slice((*T7)(unsafe.Add(base, bt.CompOffsets[6])), count),
						Comp8:  unsafe.Slice((*T8)(unsafe.Add(base, bt.CompOffsets[7])), count),
						Comp9:  unsafe.Slice((*T9)(unsafe.Add(base, bt.CompOffsets[8])), count),
						Comp10: unsafe.Slice((*T10)(unsafe.Add(base, bt.CompOffsets[9])), count),
					}) {
					return
				}
			}
		}
	}
}

// Filter yields the subset of selected entities that match the View's filter.
func (v *View10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]) Filter(selected []uid.UID64) iter.Seq2[int, struct {
	Entity uid.UID64
	Comp1  *T1
	Comp2  *T2
	Comp3  *T3
	Comp4  *T4
	Comp5  *T5
	Comp6  *T6
	Comp7  *T7
	Comp8  *T8
	Comp9  *T9
	Comp10 *T10
}] {
	return func(yield func(int, struct {
		Entity uid.UID64
		Comp1  *T1
		Comp2  *T2
		Comp3  *T3
		Comp4  *T4
		Comp5  *T5
		Comp6  *T6
		Comp7  *T7
		Comp8  *T8
		Comp9  *T9
		Comp10 *T10
	}) bool) {
		entityIndex := v.EntityIndex

		var lastArchID arch.ID = arch.NullID
		var bt *BakedTable
		for i, e := range selected {
			link, ok := entityIndex.Get(e)
			if !ok {
				continue
			}
			if link.ArchId != lastArchID {
				bt = v.Get(link.ArchId)
				lastArchID = link.ArchId
			}
			if bt == nil {
				continue
			}
			physPage := &bt.Table.Chunks[link.Pos.ChunkIdx]
			slot := uintptr(link.Pos.ChunkSlot)
			c0Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[0]+(slot*bt.CompSizes[0]))
			c1Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[1]+(slot*bt.CompSizes[1]))
			c2Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[2]+(slot*bt.CompSizes[2]))
			c3Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[3]+(slot*bt.CompSizes[3]))
			c4Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[4]+(slot*bt.CompSizes[4]))
			c5Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[5]+(slot*bt.CompSizes[5]))
			c6Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[6]+(slot*bt.CompSizes[6]))
			c7Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[7]+(slot*bt.CompSizes[7]))
			c8Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[8]+(slot*bt.CompSizes[8]))
			c9Ptr := unsafe.Add(physPage.Ptr, bt.CompOffsets[9]+(slot*bt.CompSizes[9]))
			if !yield(i, struct {
				Entity uid.UID64
				Comp1  *T1
				Comp2  *T2
				Comp3  *T3
				Comp4  *T4
				Comp5  *T5
				Comp6  *T6
				Comp7  *T7
				Comp8  *T8
				Comp9  *T9
				Comp10 *T10
			}{
				Entity: e,
				Comp1:  (*T1)(c0Ptr),
				Comp2:  (*T2)(c1Ptr),
				Comp3:  (*T3)(c2Ptr),
				Comp4:  (*T4)(c3Ptr),
				Comp5:  (*T5)(c4Ptr),
				Comp6:  (*T6)(c5Ptr),
				Comp7:  (*T7)(c6Ptr),
				Comp8:  (*T8)(c7Ptr),
				Comp9:  (*T9)(c8Ptr),
				Comp10: (*T10)(c9Ptr),
			}) {
				return
			}
		}
	}
}
