// Code generated by github.com/kjkrol/goke/internal/cmd/gen/specs; DO NOT EDIT.
package comp

import (
	"fmt"
	"reflect"
)

// Spec0 interns 0 component type(s) and builds the component mask.
type Spec0 struct {
	Blueprint
}

// Init interns T1..T0 via c, builds the inclusion mask, and applies opts.
// Panics on duplicate component types or conflicting opts.
func (s *Spec0) Init(c *Catalog, opts ...BlueprintOpt) {
	for _, opt := range opts {
		if err := opt(&s.Blueprint, c); err != nil {
			panic(fmt.Sprintf("comp: Spec0.Init option: %v", err))
		}
	}
}

// Spec1 interns 1 component type(s) and builds the component mask.
type Spec1[T1 any] struct {
	Blueprint
	Meta1 Meta
}

// Init interns T1..T1 via c, builds the inclusion mask, and applies opts.
// Panics on duplicate component types or conflicting opts.
func (s *Spec1[T1]) Init(c *Catalog, opts ...BlueprintOpt) {
	s.Meta1 = c.Intern(reflect.TypeFor[T1]())
	if err := s.Blueprint.Comp(s.Meta1); err != nil {
		panic(fmt.Sprintf("comp: Spec1.Init: %v", err))
	}
	for _, opt := range opts {
		if err := opt(&s.Blueprint, c); err != nil {
			panic(fmt.Sprintf("comp: Spec1.Init option: %v", err))
		}
	}
}

// Spec2 interns 2 component type(s) and builds the component mask.
type Spec2[T1 any, T2 any] struct {
	Blueprint
	Meta1 Meta
	Meta2 Meta
}

// Init interns T1..T2 via c, builds the inclusion mask, and applies opts.
// Panics on duplicate component types or conflicting opts.
func (s *Spec2[T1, T2]) Init(c *Catalog, opts ...BlueprintOpt) {
	s.Meta1 = c.Intern(reflect.TypeFor[T1]())
	if err := s.Blueprint.Comp(s.Meta1); err != nil {
		panic(fmt.Sprintf("comp: Spec2.Init: %v", err))
	}
	s.Meta2 = c.Intern(reflect.TypeFor[T2]())
	if err := s.Blueprint.Comp(s.Meta2); err != nil {
		panic(fmt.Sprintf("comp: Spec2.Init: %v", err))
	}
	for _, opt := range opts {
		if err := opt(&s.Blueprint, c); err != nil {
			panic(fmt.Sprintf("comp: Spec2.Init option: %v", err))
		}
	}
}

// Spec3 interns 3 component type(s) and builds the component mask.
type Spec3[T1 any, T2 any, T3 any] struct {
	Blueprint
	Meta1 Meta
	Meta2 Meta
	Meta3 Meta
}

// Init interns T1..T3 via c, builds the inclusion mask, and applies opts.
// Panics on duplicate component types or conflicting opts.
func (s *Spec3[T1, T2, T3]) Init(c *Catalog, opts ...BlueprintOpt) {
	s.Meta1 = c.Intern(reflect.TypeFor[T1]())
	if err := s.Blueprint.Comp(s.Meta1); err != nil {
		panic(fmt.Sprintf("comp: Spec3.Init: %v", err))
	}
	s.Meta2 = c.Intern(reflect.TypeFor[T2]())
	if err := s.Blueprint.Comp(s.Meta2); err != nil {
		panic(fmt.Sprintf("comp: Spec3.Init: %v", err))
	}
	s.Meta3 = c.Intern(reflect.TypeFor[T3]())
	if err := s.Blueprint.Comp(s.Meta3); err != nil {
		panic(fmt.Sprintf("comp: Spec3.Init: %v", err))
	}
	for _, opt := range opts {
		if err := opt(&s.Blueprint, c); err != nil {
			panic(fmt.Sprintf("comp: Spec3.Init option: %v", err))
		}
	}
}

// Spec4 interns 4 component type(s) and builds the component mask.
type Spec4[T1 any, T2 any, T3 any, T4 any] struct {
	Blueprint
	Meta1 Meta
	Meta2 Meta
	Meta3 Meta
	Meta4 Meta
}

// Init interns T1..T4 via c, builds the inclusion mask, and applies opts.
// Panics on duplicate component types or conflicting opts.
func (s *Spec4[T1, T2, T3, T4]) Init(c *Catalog, opts ...BlueprintOpt) {
	s.Meta1 = c.Intern(reflect.TypeFor[T1]())
	if err := s.Blueprint.Comp(s.Meta1); err != nil {
		panic(fmt.Sprintf("comp: Spec4.Init: %v", err))
	}
	s.Meta2 = c.Intern(reflect.TypeFor[T2]())
	if err := s.Blueprint.Comp(s.Meta2); err != nil {
		panic(fmt.Sprintf("comp: Spec4.Init: %v", err))
	}
	s.Meta3 = c.Intern(reflect.TypeFor[T3]())
	if err := s.Blueprint.Comp(s.Meta3); err != nil {
		panic(fmt.Sprintf("comp: Spec4.Init: %v", err))
	}
	s.Meta4 = c.Intern(reflect.TypeFor[T4]())
	if err := s.Blueprint.Comp(s.Meta4); err != nil {
		panic(fmt.Sprintf("comp: Spec4.Init: %v", err))
	}
	for _, opt := range opts {
		if err := opt(&s.Blueprint, c); err != nil {
			panic(fmt.Sprintf("comp: Spec4.Init option: %v", err))
		}
	}
}

// Spec5 interns 5 component type(s) and builds the component mask.
type Spec5[T1 any, T2 any, T3 any, T4 any, T5 any] struct {
	Blueprint
	Meta1 Meta
	Meta2 Meta
	Meta3 Meta
	Meta4 Meta
	Meta5 Meta
}

// Init interns T1..T5 via c, builds the inclusion mask, and applies opts.
// Panics on duplicate component types or conflicting opts.
func (s *Spec5[T1, T2, T3, T4, T5]) Init(c *Catalog, opts ...BlueprintOpt) {
	s.Meta1 = c.Intern(reflect.TypeFor[T1]())
	if err := s.Blueprint.Comp(s.Meta1); err != nil {
		panic(fmt.Sprintf("comp: Spec5.Init: %v", err))
	}
	s.Meta2 = c.Intern(reflect.TypeFor[T2]())
	if err := s.Blueprint.Comp(s.Meta2); err != nil {
		panic(fmt.Sprintf("comp: Spec5.Init: %v", err))
	}
	s.Meta3 = c.Intern(reflect.TypeFor[T3]())
	if err := s.Blueprint.Comp(s.Meta3); err != nil {
		panic(fmt.Sprintf("comp: Spec5.Init: %v", err))
	}
	s.Meta4 = c.Intern(reflect.TypeFor[T4]())
	if err := s.Blueprint.Comp(s.Meta4); err != nil {
		panic(fmt.Sprintf("comp: Spec5.Init: %v", err))
	}
	s.Meta5 = c.Intern(reflect.TypeFor[T5]())
	if err := s.Blueprint.Comp(s.Meta5); err != nil {
		panic(fmt.Sprintf("comp: Spec5.Init: %v", err))
	}
	for _, opt := range opts {
		if err := opt(&s.Blueprint, c); err != nil {
			panic(fmt.Sprintf("comp: Spec5.Init option: %v", err))
		}
	}
}

// Spec6 interns 6 component type(s) and builds the component mask.
type Spec6[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any] struct {
	Blueprint
	Meta1 Meta
	Meta2 Meta
	Meta3 Meta
	Meta4 Meta
	Meta5 Meta
	Meta6 Meta
}

// Init interns T1..T6 via c, builds the inclusion mask, and applies opts.
// Panics on duplicate component types or conflicting opts.
func (s *Spec6[T1, T2, T3, T4, T5, T6]) Init(c *Catalog, opts ...BlueprintOpt) {
	s.Meta1 = c.Intern(reflect.TypeFor[T1]())
	if err := s.Blueprint.Comp(s.Meta1); err != nil {
		panic(fmt.Sprintf("comp: Spec6.Init: %v", err))
	}
	s.Meta2 = c.Intern(reflect.TypeFor[T2]())
	if err := s.Blueprint.Comp(s.Meta2); err != nil {
		panic(fmt.Sprintf("comp: Spec6.Init: %v", err))
	}
	s.Meta3 = c.Intern(reflect.TypeFor[T3]())
	if err := s.Blueprint.Comp(s.Meta3); err != nil {
		panic(fmt.Sprintf("comp: Spec6.Init: %v", err))
	}
	s.Meta4 = c.Intern(reflect.TypeFor[T4]())
	if err := s.Blueprint.Comp(s.Meta4); err != nil {
		panic(fmt.Sprintf("comp: Spec6.Init: %v", err))
	}
	s.Meta5 = c.Intern(reflect.TypeFor[T5]())
	if err := s.Blueprint.Comp(s.Meta5); err != nil {
		panic(fmt.Sprintf("comp: Spec6.Init: %v", err))
	}
	s.Meta6 = c.Intern(reflect.TypeFor[T6]())
	if err := s.Blueprint.Comp(s.Meta6); err != nil {
		panic(fmt.Sprintf("comp: Spec6.Init: %v", err))
	}
	for _, opt := range opts {
		if err := opt(&s.Blueprint, c); err != nil {
			panic(fmt.Sprintf("comp: Spec6.Init option: %v", err))
		}
	}
}

// Spec7 interns 7 component type(s) and builds the component mask.
type Spec7[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any] struct {
	Blueprint
	Meta1 Meta
	Meta2 Meta
	Meta3 Meta
	Meta4 Meta
	Meta5 Meta
	Meta6 Meta
	Meta7 Meta
}

// Init interns T1..T7 via c, builds the inclusion mask, and applies opts.
// Panics on duplicate component types or conflicting opts.
func (s *Spec7[T1, T2, T3, T4, T5, T6, T7]) Init(c *Catalog, opts ...BlueprintOpt) {
	s.Meta1 = c.Intern(reflect.TypeFor[T1]())
	if err := s.Blueprint.Comp(s.Meta1); err != nil {
		panic(fmt.Sprintf("comp: Spec7.Init: %v", err))
	}
	s.Meta2 = c.Intern(reflect.TypeFor[T2]())
	if err := s.Blueprint.Comp(s.Meta2); err != nil {
		panic(fmt.Sprintf("comp: Spec7.Init: %v", err))
	}
	s.Meta3 = c.Intern(reflect.TypeFor[T3]())
	if err := s.Blueprint.Comp(s.Meta3); err != nil {
		panic(fmt.Sprintf("comp: Spec7.Init: %v", err))
	}
	s.Meta4 = c.Intern(reflect.TypeFor[T4]())
	if err := s.Blueprint.Comp(s.Meta4); err != nil {
		panic(fmt.Sprintf("comp: Spec7.Init: %v", err))
	}
	s.Meta5 = c.Intern(reflect.TypeFor[T5]())
	if err := s.Blueprint.Comp(s.Meta5); err != nil {
		panic(fmt.Sprintf("comp: Spec7.Init: %v", err))
	}
	s.Meta6 = c.Intern(reflect.TypeFor[T6]())
	if err := s.Blueprint.Comp(s.Meta6); err != nil {
		panic(fmt.Sprintf("comp: Spec7.Init: %v", err))
	}
	s.Meta7 = c.Intern(reflect.TypeFor[T7]())
	if err := s.Blueprint.Comp(s.Meta7); err != nil {
		panic(fmt.Sprintf("comp: Spec7.Init: %v", err))
	}
	for _, opt := range opts {
		if err := opt(&s.Blueprint, c); err != nil {
			panic(fmt.Sprintf("comp: Spec7.Init option: %v", err))
		}
	}
}

// Spec8 interns 8 component type(s) and builds the component mask.
type Spec8[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any, T8 any] struct {
	Blueprint
	Meta1 Meta
	Meta2 Meta
	Meta3 Meta
	Meta4 Meta
	Meta5 Meta
	Meta6 Meta
	Meta7 Meta
	Meta8 Meta
}

// Init interns T1..T8 via c, builds the inclusion mask, and applies opts.
// Panics on duplicate component types or conflicting opts.
func (s *Spec8[T1, T2, T3, T4, T5, T6, T7, T8]) Init(c *Catalog, opts ...BlueprintOpt) {
	s.Meta1 = c.Intern(reflect.TypeFor[T1]())
	if err := s.Blueprint.Comp(s.Meta1); err != nil {
		panic(fmt.Sprintf("comp: Spec8.Init: %v", err))
	}
	s.Meta2 = c.Intern(reflect.TypeFor[T2]())
	if err := s.Blueprint.Comp(s.Meta2); err != nil {
		panic(fmt.Sprintf("comp: Spec8.Init: %v", err))
	}
	s.Meta3 = c.Intern(reflect.TypeFor[T3]())
	if err := s.Blueprint.Comp(s.Meta3); err != nil {
		panic(fmt.Sprintf("comp: Spec8.Init: %v", err))
	}
	s.Meta4 = c.Intern(reflect.TypeFor[T4]())
	if err := s.Blueprint.Comp(s.Meta4); err != nil {
		panic(fmt.Sprintf("comp: Spec8.Init: %v", err))
	}
	s.Meta5 = c.Intern(reflect.TypeFor[T5]())
	if err := s.Blueprint.Comp(s.Meta5); err != nil {
		panic(fmt.Sprintf("comp: Spec8.Init: %v", err))
	}
	s.Meta6 = c.Intern(reflect.TypeFor[T6]())
	if err := s.Blueprint.Comp(s.Meta6); err != nil {
		panic(fmt.Sprintf("comp: Spec8.Init: %v", err))
	}
	s.Meta7 = c.Intern(reflect.TypeFor[T7]())
	if err := s.Blueprint.Comp(s.Meta7); err != nil {
		panic(fmt.Sprintf("comp: Spec8.Init: %v", err))
	}
	s.Meta8 = c.Intern(reflect.TypeFor[T8]())
	if err := s.Blueprint.Comp(s.Meta8); err != nil {
		panic(fmt.Sprintf("comp: Spec8.Init: %v", err))
	}
	for _, opt := range opts {
		if err := opt(&s.Blueprint, c); err != nil {
			panic(fmt.Sprintf("comp: Spec8.Init option: %v", err))
		}
	}
}

// Spec9 interns 9 component type(s) and builds the component mask.
type Spec9[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any, T8 any, T9 any] struct {
	Blueprint
	Meta1 Meta
	Meta2 Meta
	Meta3 Meta
	Meta4 Meta
	Meta5 Meta
	Meta6 Meta
	Meta7 Meta
	Meta8 Meta
	Meta9 Meta
}

// Init interns T1..T9 via c, builds the inclusion mask, and applies opts.
// Panics on duplicate component types or conflicting opts.
func (s *Spec9[T1, T2, T3, T4, T5, T6, T7, T8, T9]) Init(c *Catalog, opts ...BlueprintOpt) {
	s.Meta1 = c.Intern(reflect.TypeFor[T1]())
	if err := s.Blueprint.Comp(s.Meta1); err != nil {
		panic(fmt.Sprintf("comp: Spec9.Init: %v", err))
	}
	s.Meta2 = c.Intern(reflect.TypeFor[T2]())
	if err := s.Blueprint.Comp(s.Meta2); err != nil {
		panic(fmt.Sprintf("comp: Spec9.Init: %v", err))
	}
	s.Meta3 = c.Intern(reflect.TypeFor[T3]())
	if err := s.Blueprint.Comp(s.Meta3); err != nil {
		panic(fmt.Sprintf("comp: Spec9.Init: %v", err))
	}
	s.Meta4 = c.Intern(reflect.TypeFor[T4]())
	if err := s.Blueprint.Comp(s.Meta4); err != nil {
		panic(fmt.Sprintf("comp: Spec9.Init: %v", err))
	}
	s.Meta5 = c.Intern(reflect.TypeFor[T5]())
	if err := s.Blueprint.Comp(s.Meta5); err != nil {
		panic(fmt.Sprintf("comp: Spec9.Init: %v", err))
	}
	s.Meta6 = c.Intern(reflect.TypeFor[T6]())
	if err := s.Blueprint.Comp(s.Meta6); err != nil {
		panic(fmt.Sprintf("comp: Spec9.Init: %v", err))
	}
	s.Meta7 = c.Intern(reflect.TypeFor[T7]())
	if err := s.Blueprint.Comp(s.Meta7); err != nil {
		panic(fmt.Sprintf("comp: Spec9.Init: %v", err))
	}
	s.Meta8 = c.Intern(reflect.TypeFor[T8]())
	if err := s.Blueprint.Comp(s.Meta8); err != nil {
		panic(fmt.Sprintf("comp: Spec9.Init: %v", err))
	}
	s.Meta9 = c.Intern(reflect.TypeFor[T9]())
	if err := s.Blueprint.Comp(s.Meta9); err != nil {
		panic(fmt.Sprintf("comp: Spec9.Init: %v", err))
	}
	for _, opt := range opts {
		if err := opt(&s.Blueprint, c); err != nil {
			panic(fmt.Sprintf("comp: Spec9.Init option: %v", err))
		}
	}
}

// Spec10 interns 10 component type(s) and builds the component mask.
type Spec10[T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any, T8 any, T9 any, T10 any] struct {
	Blueprint
	Meta1  Meta
	Meta2  Meta
	Meta3  Meta
	Meta4  Meta
	Meta5  Meta
	Meta6  Meta
	Meta7  Meta
	Meta8  Meta
	Meta9  Meta
	Meta10 Meta
}

// Init interns T1..T10 via c, builds the inclusion mask, and applies opts.
// Panics on duplicate component types or conflicting opts.
func (s *Spec10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]) Init(c *Catalog, opts ...BlueprintOpt) {
	s.Meta1 = c.Intern(reflect.TypeFor[T1]())
	if err := s.Blueprint.Comp(s.Meta1); err != nil {
		panic(fmt.Sprintf("comp: Spec10.Init: %v", err))
	}
	s.Meta2 = c.Intern(reflect.TypeFor[T2]())
	if err := s.Blueprint.Comp(s.Meta2); err != nil {
		panic(fmt.Sprintf("comp: Spec10.Init: %v", err))
	}
	s.Meta3 = c.Intern(reflect.TypeFor[T3]())
	if err := s.Blueprint.Comp(s.Meta3); err != nil {
		panic(fmt.Sprintf("comp: Spec10.Init: %v", err))
	}
	s.Meta4 = c.Intern(reflect.TypeFor[T4]())
	if err := s.Blueprint.Comp(s.Meta4); err != nil {
		panic(fmt.Sprintf("comp: Spec10.Init: %v", err))
	}
	s.Meta5 = c.Intern(reflect.TypeFor[T5]())
	if err := s.Blueprint.Comp(s.Meta5); err != nil {
		panic(fmt.Sprintf("comp: Spec10.Init: %v", err))
	}
	s.Meta6 = c.Intern(reflect.TypeFor[T6]())
	if err := s.Blueprint.Comp(s.Meta6); err != nil {
		panic(fmt.Sprintf("comp: Spec10.Init: %v", err))
	}
	s.Meta7 = c.Intern(reflect.TypeFor[T7]())
	if err := s.Blueprint.Comp(s.Meta7); err != nil {
		panic(fmt.Sprintf("comp: Spec10.Init: %v", err))
	}
	s.Meta8 = c.Intern(reflect.TypeFor[T8]())
	if err := s.Blueprint.Comp(s.Meta8); err != nil {
		panic(fmt.Sprintf("comp: Spec10.Init: %v", err))
	}
	s.Meta9 = c.Intern(reflect.TypeFor[T9]())
	if err := s.Blueprint.Comp(s.Meta9); err != nil {
		panic(fmt.Sprintf("comp: Spec10.Init: %v", err))
	}
	s.Meta10 = c.Intern(reflect.TypeFor[T10]())
	if err := s.Blueprint.Comp(s.Meta10); err != nil {
		panic(fmt.Sprintf("comp: Spec10.Init: %v", err))
	}
	for _, opt := range opts {
		if err := opt(&s.Blueprint, c); err != nil {
			panic(fmt.Sprintf("comp: Spec10.Init option: %v", err))
		}
	}
}
