// Code generated by gen/queries; DO NOT EDIT.
package ecsq
import (
	"iter"
	"unsafe"

	"github.com/kjkrol/goke/internal/core"
)

type Query1[T1 any] struct {
	*core.View
}

func NewQuery1[T1 any](reg *core.Registry, options ...core.ViewOption) *Query1[T1] {
	viewBuilder := core.NewViewBuilder(reg)
	core.OnCompType[T1](viewBuilder)
	for _, opt := range options {
		opt(viewBuilder)
	}
	return &Query1[T1]{View: viewBuilder.Build()}
}

type Head1[T1 any] struct {
	Entity core.Entity
	V1 *T1
}
type PHead1[T1 any] struct {
	V1 *T1
}

func (q *Query1[T1]) All1() iter.Seq[Head1[T1]] {
	return func(yield func(Head1[T1]) bool) {
		for i := range q.Baked {
			b := &q.Baked[i]
			p1, s1 := b.Columns[0].Data, b.Columns[0].ItemSize
			for j := 0; j < *b.Len; j++ {
				if !yield(Head1[T1]{Entity: (*b.Entities)[j], V1: (*T1)(p1)}) { return }
				p1 = unsafe.Add(p1, s1)
			}
		}
	}
}

func (q *Query1[T1]) Filter1(entities []core.Entity) iter.Seq[Head1[T1]] {
	links := q.Reg.ArchetypeRegistry.EntityArchLinks
	return func(yield func(Head1[T1]) bool) {
		var lastArch *core.Archetype; var cols [1]*core.Column
		for _, e := range entities {
			link := links[e.Index()]; arch := link.Arch
			if arch == nil || q.View.Matches(arch.Mask) { continue }
			if arch != lastArch { for i := 0; i < 1; i++ { cols[i] = arch.Columns[q.CompIDs[i]] }; lastArch = arch }
			idx := uintptr(link.Row)
			if !yield(Head1[T1]{Entity: e, V1: (*T1)(unsafe.Add(cols[0].Data, idx*cols[0].ItemSize))}) { return }
		}
	}
}

func (q *Query1[T1]) PureAll1() iter.Seq[PHead1[T1]] {
	return func(yield func(PHead1[T1]) bool) {
		for i := range q.Baked {
			b := &q.Baked[i]
			p1, s1 := b.Columns[0].Data, b.Columns[0].ItemSize
			for j := 0; j < *b.Len; j++ {
				if !yield(PHead1[T1]{V1: (*T1)(p1)}) { return }
				p1 = unsafe.Add(p1, s1)
			}
		}
	}
}

func (q *Query1[T1]) PureFilter1(entities []core.Entity) iter.Seq[PHead1[T1]] {
	links := q.Reg.ArchetypeRegistry.EntityArchLinks
	return func(yield func(PHead1[T1]) bool) {
		var lastArch *core.Archetype; var cols [1]*core.Column
		for _, e := range entities {
			link := links[e.Index()]; arch := link.Arch
			if arch == nil || q.View.Matches(arch.Mask) { continue }
			if arch != lastArch { for i := 0; i < 1; i++ { cols[i] = arch.Columns[q.CompIDs[i]] }; lastArch = arch }
			idx := uintptr(link.Row)
			if !yield(PHead1[T1]{V1: (*T1)(unsafe.Add(cols[0].Data, idx*cols[0].ItemSize))}) { return }
		}
	}
}
