package main

import (
	"fmt"
	"os"
	"strings"
	"text/template"
)

const viewTemplate = `// Code generated by go generate; DO NOT EDIT.
package ecs

import (
    "iter"
    "unsafe"
)

// -------------- Row Structures --------------

{{range .Count}}{{$n := .}}
type Head{{$n}}[{{headParams $n}}] struct {
    Entity Entity
    {{headFields $n}}
}

{{if gt (tailCount $n) 0}}
type Tail{{$n}}[{{tailParams $n}}] struct {
    {{tailFields $n}}
}
{{end}}

// -------------- View{{$n}} --------------

type matchedArch{{$n}}[{{allParams $n}}] struct {
    arch     *Archetype
    entities []Entity
    count    int
    {{range $i := seq $n}}ptr{{add $i 1}}  unsafe.Pointer; size{{add $i 1}} uintptr;{{end}}
}

type View{{$n}}[{{allParams $n}}] struct {
    viewBase
    ids      [{{$n}}]ComponentID
    baked    []matchedArch{{$n}}[{{allTypes $n}}]
    bakedIdx map[*Archetype]*matchedArch{{$n}}[{{allTypes $n}}]
}

func (v *View{{$n}}[{{allTypes $n}}]) Reindex() {
    v.viewBase.Reindex()
    v.baked = v.baked[:0]
    v.bakedIdx = make(map[*Archetype]*matchedArch{{$n}}[{{allTypes $n}}])
    for _, arch := range v.matched {
        if arch.len == 0 { continue }
        mArch := matchedArch{{$n}}[{{allTypes $n}}]{arch: arch, entities: arch.entities[:arch.len], count: arch.len}
        {{range $i := seq $n}}col{{add $i 1}} := arch.columns[v.ids[{{$i}}]]; mArch.ptr{{add $i 1}} = col{{add $i 1}}.data; mArch.size{{add $i 1}} = col{{add $i 1}}.itemSize;{{end}}
        v.baked = append(v.baked, mArch)
        v.bakedIdx[arch] = &v.baked[len(v.baked)-1]
    }
}

func NewView{{$n}}[{{allParams $n}}](reg *Registry) *View{{$n}}[{{allTypes $n}}] {
    {{registration $n}}
    ids := [{{$n}}]ComponentID{ {{idList $n}} }
    var mask ArchetypeMask
    for _, id := range ids { mask = mask.Set(id) }
    v := &View{{$n}}[{{allTypes $n}}]{
        viewBase: viewBase{reg: reg, mask: mask, entityArchLinks: reg.archetypeRegistry.entityArchLinks},
        ids: ids,
    }
    v.Reindex() 
    return v
}

func (v *View{{$n}}[{{allTypes $n}}]) All() {{if le $n 2}}iter.Seq[Head{{$n}}[{{allTypes $n}}]]{{else}}iter.Seq2[Head{{$n}}[{{headTypesCall $n}}], Tail{{$n}}[{{tailTypesCall $n}}]]{{end}} {
    return func(yield {{if le $n 2}}func(Head{{$n}}[{{allTypes $n}}]) bool{{else}}func(Head{{$n}}[{{headTypesCall $n}}], Tail{{$n}}[{{tailTypesCall $n}}]) bool{{end}}) {
        {{if le $n 2}}var h Head{{$n}}[{{allTypes $n}}]{{else}}var h Head{{$n}}[{{headTypesCall $n}}]; var t Tail{{$n}}[{{tailTypesCall $n}}]{{end}}
        for i := range v.baked {
            b := &v.baked[i]
            {{range $i := seq $n}}p{{add $i 1}} := b.ptr{{add $i 1}}; s{{add $i 1}} := b.size{{add $i 1}};{{end}}
            for j := 0; j < b.count; j++ {
                h.Entity = b.entities[j]
                {{range $idx := headIndices $n}}h.V{{$idx}} = (*T{{$idx}})(p{{$idx}});{{end}}
                {{if gt (tailCount $n) 0}}{{range $idx := tailIndices $n}}t.V{{$idx}} = (*T{{$idx}})(p{{$idx}});{{end}}{{end}}
                {{if le $n 2}}if !yield(h) { return }{{else}}if !yield(h, t) { return }{{end}}
                {{range $i := seq $n}}p{{add $i 1}} = unsafe.Add(p{{add $i 1}}, s{{add $i 1}});{{end}}
            }
        }
    }
}

func (v *View{{$n}}[{{allTypes $n}}]) Filtered(entities []Entity) {{if le $n 2}}iter.Seq[Head{{$n}}[{{allTypes $n}}]]{{else}}iter.Seq2[Head{{$n}}[{{headTypesCall $n}}], Tail{{$n}}[{{tailTypesCall $n}}]]{{end}} {
    return func(yield {{if le $n 2}}func(Head{{$n}}[{{allTypes $n}}]) bool{{else}}func(Head{{$n}}[{{headTypesCall $n}}], Tail{{$n}}[{{tailTypesCall $n}}]) bool{{end}}) {
        {{if le $n 2}}var h Head{{$n}}[{{allTypes $n}}]{{else}}var h Head{{$n}}[{{headTypesCall $n}}]; var t Tail{{$n}}[{{tailTypesCall $n}}]{{end}}
        for _, e := range entities {
            backLink := v.viewBase.entityArchLinks[e.Index()]
            arch := backLink.arch
            if arch == nil || !arch.mask.Contains(v.mask) { continue }
            b, ok := v.bakedIdx[arch]
            if !ok { continue }
            idx := uintptr(backLink.row)
            h.Entity = e
            {{range $idx := headIndices $n}}h.V{{$idx}} = (*T{{$idx}})(unsafe.Add(b.ptr{{$idx}}, idx * b.size{{$idx}}));{{end}}
            {{if gt (tailCount $n) 0}}{{range $idx := tailIndices $n}}t.V{{$idx}} = (*T{{$idx}})(unsafe.Add(b.ptr{{$idx}}, idx * b.size{{$idx}}));{{end}}{{end}}
            {{if le $n 2}}if !yield(h) { return }{{else}}if !yield(h, t) { return }{{end}}
        }
    }
}
{{end}}`

func main() {
	fMap := template.FuncMap{
		"add": func(a, b int) int { return a + b },
		"seq": func(n int) []int {
			res := make([]int, n)
			for i := 0; i < n; i++ {
				res[i] = i
			}
			return res
		},
		"allParams": func(n int) string {
			var res []string
			for i := 1; i <= n; i++ {
				res = append(res, fmt.Sprintf("T%d any", i))
			}
			return strings.Join(res, ", ")
		},
		"allTypes": func(n int) string {
			var res []string
			for i := 1; i <= n; i++ {
				res = append(res, fmt.Sprintf("T%d", i))
			}
			return strings.Join(res, ", ")
		},
		"headParams": func(n int) string {
			count := 2
			if n <= 2 {
				count = n
			}
			if n == 7 {
				count = 3
			}
			var res []string
			for i := 1; i <= count; i++ {
				res = append(res, fmt.Sprintf("U%d any", i))
			}
			return strings.Join(res, ", ")
		},
		"tailParams": func(n int) string {
			count := 0
			if n >= 3 && n <= 5 {
				count = 3
			}
			if n == 6 || n == 7 {
				count = 4
			}
			if n == 8 {
				count = 6
			}
			var res []string
			for i := 1; i <= count; i++ {
				res = append(res, fmt.Sprintf("W%d any", i))
			}
			return strings.Join(res, ", ")
		},
		"headFields": func(n int) string {
			indices := []int{1, 2}
			if n <= 2 {
				indices = []int{1, 2}[:n]
			}
			if n == 7 {
				indices = []int{1, 2, 7}
			}
			var res []string
			for i, idx := range indices {
				res = append(res, fmt.Sprintf("V%d *U%d", idx, i+1))
			}
			return strings.Join(res, "; ")
		},
		"tailFields": func(n int) string {
			var indices []int
			if n >= 3 && n <= 5 {
				indices = []int{3, 4, 5}
			}
			if n == 6 || n == 7 {
				indices = []int{3, 4, 5, 6}
			}
			if n == 8 {
				indices = []int{3, 4, 5, 6, 7, 8}
			}
			var res []string
			for i, idx := range indices {
				res = append(res, fmt.Sprintf("V%d *W%d", idx, i+1))
			}
			return strings.Join(res, "; ")
		},
		"headTypesCall": func(n int) string {
			if n <= 2 {
				return strings.Join([]string{"T1", "T2"}[:n], ", ")
			}
			if n == 7 {
				return "T1, T2, T7"
			}
			return "T1, T2"
		},
		"tailTypesCall": func(n int) string {
			var indices []int
			if n >= 3 && n <= 5 {
				indices = []int{3, 4, 5}
			}
			if n == 6 || n == 7 {
				indices = []int{3, 4, 5, 6}
			}
			if n == 8 {
				indices = []int{3, 4, 5, 6, 7, 8}
			}
			var res []string
			for _, idx := range indices {
				res = append(res, fmt.Sprintf("T%d", idx))
			}
			return strings.Join(res, ", ")
		},
		"headIndices": func(n int) []int {
			if n <= 2 {
				return []int{1, 2}[:n]
			}
			if n == 7 {
				return []int{1, 2, 7}
			}
			return []int{1, 2}
		},
		"tailIndices": func(n int) []int {
			if n >= 3 && n <= 5 {
				return []int{3, 4, 5}
			}
			if n == 6 || n == 7 {
				return []int{3, 4, 5, 6}
			}
			if n == 8 {
				return []int{3, 4, 5, 6, 7, 8}
			}
			return nil
		},
		"tailCount": func(n int) int {
			if n < 3 {
				return 0
			}
			return 1
		},
		"registration": func(n int) string {
			var res []string
			for i := 1; i <= n; i++ {
				res = append(res, fmt.Sprintf("id%d := ensureComponentRegistered[T%d](reg.componentsRegistry)", i, i))
			}
			return strings.Join(res, "\n\t")
		},
		"idList": func(n int) string {
			var res []string
			for i := 1; i <= n; i++ {
				res = append(res, fmt.Sprintf("id%d", i))
			}
			return strings.Join(res, ", ")
		},
	}

	tmpl := template.Must(template.New("ecs").Funcs(fMap).Parse(viewTemplate))
	f, _ := os.Create("views_gen.go")
	defer f.Close()
	tmpl.Execute(f, struct{ Count []int }{Count: []int{1, 2, 3, 4, 5, 6, 7, 8}})
}
