// Code generated by ecs/gen; DO NOT EDIT.
package ecs
import (
	"iter"
	"unsafe"
)

type Query5[T1, T2, T3, T4, T5 any] struct {
	*View
}

func NewQuery5[T1, T2, T3, T4, T5 any](reg *Registry, options ...QueryOption) *Query5[T1, T2, T3, T4, T5] {
	viewBuilder := NewViewBuilder(reg)
	OnCompType[T1](viewBuilder)
	OnCompType[T2](viewBuilder)
	OnCompType[T3](viewBuilder)
	OnCompType[T4](viewBuilder)
	OnCompType[T5](viewBuilder)
	for _, opt := range options {
		opt(viewBuilder)
	}
	return &Query5[T1, T2, T3, T4, T5]{View: viewBuilder.Build()}
}

type Head5[T1, T2, T3 any] struct {
	Entity Entity
	V1 *T1
	V2 *T2
	V3 *T3
}
type Tail5[T4, T5 any] struct {
	V4 *T4
	V5 *T5
}
type PHead5[T1, T2, T3, T4 any] struct {
	V1 *T1
	V2 *T2
	V3 *T3
	V4 *T4
}
type PTail5[T5 any] struct {
	V5 *T5
}

func (q *Query5[T1, T2, T3, T4, T5]) All5() iter.Seq2[Head5[T1, T2, T3], Tail5[T4, T5]] {
	return func(yield func(Head5[T1, T2, T3], Tail5[T4, T5]) bool) {
		for i := range q.baked {
			b := &q.baked[i]
			p1, s1 := b.columns[0].data, b.columns[0].itemSize
			p2, s2 := b.columns[1].data, b.columns[1].itemSize
			p3, s3 := b.columns[2].data, b.columns[2].itemSize
			p4, s4 := b.columns[3].data, b.columns[3].itemSize
			p5, s5 := b.columns[4].data, b.columns[4].itemSize
			for j := 0; j < *b.len; j++ {
				if !yield(Head5[T1, T2, T3]{Entity: (*b.entities)[j], V1: (*T1)(p1), V2: (*T2)(p2), V3: (*T3)(p3)}, Tail5[T4, T5]{V4: (*T4)(p4), V5: (*T5)(p5)}) { return }
				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)
				p3 = unsafe.Add(p3, s3)
				p4 = unsafe.Add(p4, s4)
				p5 = unsafe.Add(p5, s5)
			}
		}
	}
}

func (q *Query5[T1, T2, T3, T4, T5]) Filter5(entities []Entity) iter.Seq2[Head5[T1, T2, T3], Tail5[T4, T5]] {
	links := q.reg.archetypeRegistry.entityArchLinks
	return func(yield func(Head5[T1, T2, T3], Tail5[T4, T5]) bool) {
		var lastArch *Archetype; var cols [5]*column
		for _, e := range entities {
			link := links[e.Index()]; arch := link.arch
			if arch == nil || !arch.mask.Contains(q.mask) { continue }
			if arch != lastArch { for i := 0; i < 5; i++ { cols[i] = arch.columns[q.compIDs[i]] }; lastArch = arch }
			idx := uintptr(link.row)
			if !yield(Head5[T1, T2, T3]{Entity: e, V1: (*T1)(unsafe.Add(cols[0].data, idx*cols[0].itemSize)), V2: (*T2)(unsafe.Add(cols[1].data, idx*cols[1].itemSize)), V3: (*T3)(unsafe.Add(cols[2].data, idx*cols[2].itemSize))}, Tail5[T4, T5]{V4: (*T4)(unsafe.Add(cols[3].data, idx*cols[3].itemSize)), V5: (*T5)(unsafe.Add(cols[4].data, idx*cols[4].itemSize))}) { return }
		}
	}
}

func (q *Query5[T1, T2, T3, T4, T5]) PureAll5() iter.Seq2[PHead5[T1, T2, T3, T4], PTail5[T5]] {
	return func(yield func(PHead5[T1, T2, T3, T4], PTail5[T5]) bool) {
		for i := range q.baked {
			b := &q.baked[i]
			p1, s1 := b.columns[0].data, b.columns[0].itemSize
			p2, s2 := b.columns[1].data, b.columns[1].itemSize
			p3, s3 := b.columns[2].data, b.columns[2].itemSize
			p4, s4 := b.columns[3].data, b.columns[3].itemSize
			p5, s5 := b.columns[4].data, b.columns[4].itemSize
			for j := 0; j < *b.len; j++ {
				if !yield(PHead5[T1, T2, T3, T4]{V1: (*T1)(p1), V2: (*T2)(p2), V3: (*T3)(p3), V4: (*T4)(p4)}, PTail5[T5]{V5: (*T5)(p5)}) { return }
				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)
				p3 = unsafe.Add(p3, s3)
				p4 = unsafe.Add(p4, s4)
				p5 = unsafe.Add(p5, s5)
			}
		}
	}
}

func (q *Query5[T1, T2, T3, T4, T5]) PureFilter5(entities []Entity) iter.Seq2[PHead5[T1, T2, T3, T4], PTail5[T5]] {
	links := q.reg.archetypeRegistry.entityArchLinks
	return func(yield func(PHead5[T1, T2, T3, T4], PTail5[T5]) bool) {
		var lastArch *Archetype; var cols [5]*column
		for _, e := range entities {
			link := links[e.Index()]; arch := link.arch
			if arch == nil || !arch.mask.Contains(q.mask) { continue }
			if arch != lastArch { for i := 0; i < 5; i++ { cols[i] = arch.columns[q.compIDs[i]] }; lastArch = arch }
			idx := uintptr(link.row)
			if !yield(PHead5[T1, T2, T3, T4]{V1: (*T1)(unsafe.Add(cols[0].data, idx*cols[0].itemSize)), V2: (*T2)(unsafe.Add(cols[1].data, idx*cols[1].itemSize)), V3: (*T3)(unsafe.Add(cols[2].data, idx*cols[2].itemSize)), V4: (*T4)(unsafe.Add(cols[3].data, idx*cols[3].itemSize))}, PTail5[T5]{V5: (*T5)(unsafe.Add(cols[4].data, idx*cols[4].itemSize))}) { return }
		}
	}
}
