// Code generated by ecs/gen; DO NOT EDIT.
package ecs
import (
	"iter"
	"unsafe"
)

type Query7[T1, T2, T3, T4, T5, T6, T7 any] struct {
	*View
}

func newQuery7[T1, T2, T3, T4, T5, T6, T7 any](reg *Registry, options ...ViewOption) *Query7[T1, T2, T3, T4, T5, T6, T7] {
	viewBuilder := NewViewBuilder(reg)
	OnCompType[T1](viewBuilder)
	OnCompType[T2](viewBuilder)
	OnCompType[T3](viewBuilder)
	OnCompType[T4](viewBuilder)
	OnCompType[T5](viewBuilder)
	OnCompType[T6](viewBuilder)
	OnCompType[T7](viewBuilder)
	for _, opt := range options {
		opt(viewBuilder)
	}
	return &Query7[T1, T2, T3, T4, T5, T6, T7]{View: viewBuilder.Build()}
}

type Head7[T1, T2, T3 any] struct {
	Entity Entity
	V1 *T1
	V2 *T2
	V3 *T3
}
type Tail7[T4, T5, T6, T7 any] struct {
	V4 *T4
	V5 *T5
	V6 *T6
	V7 *T7
}
type PHead7[T1, T2, T3, T4 any] struct {
	V1 *T1
	V2 *T2
	V3 *T3
	V4 *T4
}
type PTail7[T5, T6, T7 any] struct {
	V5 *T5
	V6 *T6
	V7 *T7
}

func (q *Query7[T1, T2, T3, T4, T5, T6, T7]) All7() iter.Seq2[Head7[T1, T2, T3], Tail7[T4, T5, T6, T7]] {
	return func(yield func(Head7[T1, T2, T3], Tail7[T4, T5, T6, T7]) bool) {
		for i := range q.baked {
			b := &q.baked[i]
			p1, s1 := b.columns[0].data, b.columns[0].itemSize
			p2, s2 := b.columns[1].data, b.columns[1].itemSize
			p3, s3 := b.columns[2].data, b.columns[2].itemSize
			p4, s4 := b.columns[3].data, b.columns[3].itemSize
			p5, s5 := b.columns[4].data, b.columns[4].itemSize
			p6, s6 := b.columns[5].data, b.columns[5].itemSize
			p7, s7 := b.columns[6].data, b.columns[6].itemSize
			for j := 0; j < *b.len; j++ {
				if !yield(Head7[T1, T2, T3]{Entity: (*b.entities)[j], V1: (*T1)(p1), V2: (*T2)(p2), V3: (*T3)(p3)}, Tail7[T4, T5, T6, T7]{V4: (*T4)(p4), V5: (*T5)(p5), V6: (*T6)(p6), V7: (*T7)(p7)}) { return }
				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)
				p3 = unsafe.Add(p3, s3)
				p4 = unsafe.Add(p4, s4)
				p5 = unsafe.Add(p5, s5)
				p6 = unsafe.Add(p6, s6)
				p7 = unsafe.Add(p7, s7)
			}
		}
	}
}

func (q *Query7[T1, T2, T3, T4, T5, T6, T7]) Filter7(entities []Entity) iter.Seq2[Head7[T1, T2, T3], Tail7[T4, T5, T6, T7]] {
	links := q.reg.archetypeRegistry.entityArchLinks
	return func(yield func(Head7[T1, T2, T3], Tail7[T4, T5, T6, T7]) bool) {
		var lastArch *Archetype; var cols [7]*column
		for _, e := range entities {
			link := links[e.Index()]; arch := link.arch
			if arch == nil || q.View.matches(arch.mask) { continue }
			if arch != lastArch { for i := 0; i < 7; i++ { cols[i] = arch.columns[q.compIDs[i]] }; lastArch = arch }
			idx := uintptr(link.row)
			if !yield(Head7[T1, T2, T3]{Entity: e, V1: (*T1)(unsafe.Add(cols[0].data, idx*cols[0].itemSize)), V2: (*T2)(unsafe.Add(cols[1].data, idx*cols[1].itemSize)), V3: (*T3)(unsafe.Add(cols[2].data, idx*cols[2].itemSize))}, Tail7[T4, T5, T6, T7]{V4: (*T4)(unsafe.Add(cols[3].data, idx*cols[3].itemSize)), V5: (*T5)(unsafe.Add(cols[4].data, idx*cols[4].itemSize)), V6: (*T6)(unsafe.Add(cols[5].data, idx*cols[5].itemSize)), V7: (*T7)(unsafe.Add(cols[6].data, idx*cols[6].itemSize))}) { return }
		}
	}
}

func (q *Query7[T1, T2, T3, T4, T5, T6, T7]) PureAll7() iter.Seq2[PHead7[T1, T2, T3, T4], PTail7[T5, T6, T7]] {
	return func(yield func(PHead7[T1, T2, T3, T4], PTail7[T5, T6, T7]) bool) {
		for i := range q.baked {
			b := &q.baked[i]
			p1, s1 := b.columns[0].data, b.columns[0].itemSize
			p2, s2 := b.columns[1].data, b.columns[1].itemSize
			p3, s3 := b.columns[2].data, b.columns[2].itemSize
			p4, s4 := b.columns[3].data, b.columns[3].itemSize
			p5, s5 := b.columns[4].data, b.columns[4].itemSize
			p6, s6 := b.columns[5].data, b.columns[5].itemSize
			p7, s7 := b.columns[6].data, b.columns[6].itemSize
			for j := 0; j < *b.len; j++ {
				if !yield(PHead7[T1, T2, T3, T4]{V1: (*T1)(p1), V2: (*T2)(p2), V3: (*T3)(p3), V4: (*T4)(p4)}, PTail7[T5, T6, T7]{V5: (*T5)(p5), V6: (*T6)(p6), V7: (*T7)(p7)}) { return }
				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)
				p3 = unsafe.Add(p3, s3)
				p4 = unsafe.Add(p4, s4)
				p5 = unsafe.Add(p5, s5)
				p6 = unsafe.Add(p6, s6)
				p7 = unsafe.Add(p7, s7)
			}
		}
	}
}

func (q *Query7[T1, T2, T3, T4, T5, T6, T7]) PureFilter7(entities []Entity) iter.Seq2[PHead7[T1, T2, T3, T4], PTail7[T5, T6, T7]] {
	links := q.reg.archetypeRegistry.entityArchLinks
	return func(yield func(PHead7[T1, T2, T3, T4], PTail7[T5, T6, T7]) bool) {
		var lastArch *Archetype; var cols [7]*column
		for _, e := range entities {
			link := links[e.Index()]; arch := link.arch
			if arch == nil || q.View.matches(arch.mask) { continue }
			if arch != lastArch { for i := 0; i < 7; i++ { cols[i] = arch.columns[q.compIDs[i]] }; lastArch = arch }
			idx := uintptr(link.row)
			if !yield(PHead7[T1, T2, T3, T4]{V1: (*T1)(unsafe.Add(cols[0].data, idx*cols[0].itemSize)), V2: (*T2)(unsafe.Add(cols[1].data, idx*cols[1].itemSize)), V3: (*T3)(unsafe.Add(cols[2].data, idx*cols[2].itemSize)), V4: (*T4)(unsafe.Add(cols[3].data, idx*cols[3].itemSize))}, PTail7[T5, T6, T7]{V5: (*T5)(unsafe.Add(cols[4].data, idx*cols[4].itemSize)), V6: (*T6)(unsafe.Add(cols[5].data, idx*cols[5].itemSize)), V7: (*T7)(unsafe.Add(cols[6].data, idx*cols[6].itemSize))}) { return }
		}
	}
}
