// Code generated by ecs/gen; DO NOT EDIT.
package ecs
import (
	"iter"
	"unsafe"
)

type Query3[T1, T2, T3 any] struct {
	*View
}

func NewQuery3[T1, T2, T3 any](reg *Registry, options ...ViewOption) *Query3[T1, T2, T3] {
	viewBuilder := NewViewBuilder(reg)
	OnCompType[T1](viewBuilder)
	OnCompType[T2](viewBuilder)
	OnCompType[T3](viewBuilder)
	for _, opt := range options {
		opt(viewBuilder)
	}
	return &Query3[T1, T2, T3]{View: viewBuilder.Build()}
}

type Head3[T1, T2, T3 any] struct {
	Entity Entity
	V1 *T1
	V2 *T2
	V3 *T3
}
type PHead3[T1, T2, T3 any] struct {
	V1 *T1
	V2 *T2
	V3 *T3
}

func (q *Query3[T1, T2, T3]) All3() iter.Seq[Head3[T1, T2, T3]] {
	return func(yield func(Head3[T1, T2, T3]) bool) {
		for i := range q.baked {
			b := &q.baked[i]
			p1, s1 := b.columns[0].data, b.columns[0].itemSize
			p2, s2 := b.columns[1].data, b.columns[1].itemSize
			p3, s3 := b.columns[2].data, b.columns[2].itemSize
			for j := 0; j < *b.len; j++ {
				if !yield(Head3[T1, T2, T3]{Entity: (*b.entities)[j], V1: (*T1)(p1), V2: (*T2)(p2), V3: (*T3)(p3)}) { return }
				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)
				p3 = unsafe.Add(p3, s3)
			}
		}
	}
}

func (q *Query3[T1, T2, T3]) Filter3(entities []Entity) iter.Seq[Head3[T1, T2, T3]] {
	links := q.reg.archetypeRegistry.entityArchLinks
	return func(yield func(Head3[T1, T2, T3]) bool) {
		var lastArch *Archetype; var cols [3]*column
		for _, e := range entities {
			link := links[e.Index()]; arch := link.arch
			if arch == nil || q.View.matches(arch.mask) { continue }
			if arch != lastArch { for i := 0; i < 3; i++ { cols[i] = arch.columns[q.compIDs[i]] }; lastArch = arch }
			idx := uintptr(link.row)
			if !yield(Head3[T1, T2, T3]{Entity: e, V1: (*T1)(unsafe.Add(cols[0].data, idx*cols[0].itemSize)), V2: (*T2)(unsafe.Add(cols[1].data, idx*cols[1].itemSize)), V3: (*T3)(unsafe.Add(cols[2].data, idx*cols[2].itemSize))}) { return }
		}
	}
}

func (q *Query3[T1, T2, T3]) PureAll3() iter.Seq[PHead3[T1, T2, T3]] {
	return func(yield func(PHead3[T1, T2, T3]) bool) {
		for i := range q.baked {
			b := &q.baked[i]
			p1, s1 := b.columns[0].data, b.columns[0].itemSize
			p2, s2 := b.columns[1].data, b.columns[1].itemSize
			p3, s3 := b.columns[2].data, b.columns[2].itemSize
			for j := 0; j < *b.len; j++ {
				if !yield(PHead3[T1, T2, T3]{V1: (*T1)(p1), V2: (*T2)(p2), V3: (*T3)(p3)}) { return }
				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)
				p3 = unsafe.Add(p3, s3)
			}
		}
	}
}

func (q *Query3[T1, T2, T3]) PureFilter3(entities []Entity) iter.Seq[PHead3[T1, T2, T3]] {
	links := q.reg.archetypeRegistry.entityArchLinks
	return func(yield func(PHead3[T1, T2, T3]) bool) {
		var lastArch *Archetype; var cols [3]*column
		for _, e := range entities {
			link := links[e.Index()]; arch := link.arch
			if arch == nil || q.View.matches(arch.mask) { continue }
			if arch != lastArch { for i := 0; i < 3; i++ { cols[i] = arch.columns[q.compIDs[i]] }; lastArch = arch }
			idx := uintptr(link.row)
			if !yield(PHead3[T1, T2, T3]{V1: (*T1)(unsafe.Add(cols[0].data, idx*cols[0].itemSize)), V2: (*T2)(unsafe.Add(cols[1].data, idx*cols[1].itemSize)), V3: (*T3)(unsafe.Add(cols[2].data, idx*cols[2].itemSize))}) { return }
		}
	}
}
