// Code generated by ecs/gen; DO NOT EDIT.
package ecs
import (
	"iter"
	"unsafe"
)

type Query2[T1, T2 any] struct {
	*View
}

func newQuery2[T1, T2 any](reg *Registry, options ...ViewOption) *Query2[T1, T2] {
	viewBuilder := NewViewBuilder(reg)
	OnCompType[T1](viewBuilder)
	OnCompType[T2](viewBuilder)
	for _, opt := range options {
		opt(viewBuilder)
	}
	return &Query2[T1, T2]{View: viewBuilder.Build()}
}

type Head2[T1, T2 any] struct {
	Entity Entity
	V1 *T1
	V2 *T2
}
type PHead2[T1, T2 any] struct {
	V1 *T1
	V2 *T2
}

func (q *Query2[T1, T2]) All2() iter.Seq[Head2[T1, T2]] {
	return func(yield func(Head2[T1, T2]) bool) {
		for i := range q.baked {
			b := &q.baked[i]
			p1, s1 := b.columns[0].data, b.columns[0].itemSize
			p2, s2 := b.columns[1].data, b.columns[1].itemSize
			for j := 0; j < *b.len; j++ {
				if !yield(Head2[T1, T2]{Entity: (*b.entities)[j], V1: (*T1)(p1), V2: (*T2)(p2)}) { return }
				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)
			}
		}
	}
}

func (q *Query2[T1, T2]) Filter2(entities []Entity) iter.Seq[Head2[T1, T2]] {
	links := q.reg.archetypeRegistry.entityArchLinks
	return func(yield func(Head2[T1, T2]) bool) {
		var lastArch *Archetype; var cols [2]*column
		for _, e := range entities {
			link := links[e.Index()]; arch := link.arch
			if arch == nil || q.View.matches(arch.mask) { continue }
			if arch != lastArch { for i := 0; i < 2; i++ { cols[i] = arch.columns[q.compIDs[i]] }; lastArch = arch }
			idx := uintptr(link.row)
			if !yield(Head2[T1, T2]{Entity: e, V1: (*T1)(unsafe.Add(cols[0].data, idx*cols[0].itemSize)), V2: (*T2)(unsafe.Add(cols[1].data, idx*cols[1].itemSize))}) { return }
		}
	}
}

func (q *Query2[T1, T2]) PureAll2() iter.Seq[PHead2[T1, T2]] {
	return func(yield func(PHead2[T1, T2]) bool) {
		for i := range q.baked {
			b := &q.baked[i]
			p1, s1 := b.columns[0].data, b.columns[0].itemSize
			p2, s2 := b.columns[1].data, b.columns[1].itemSize
			for j := 0; j < *b.len; j++ {
				if !yield(PHead2[T1, T2]{V1: (*T1)(p1), V2: (*T2)(p2)}) { return }
				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)
			}
		}
	}
}

func (q *Query2[T1, T2]) PureFilter2(entities []Entity) iter.Seq[PHead2[T1, T2]] {
	links := q.reg.archetypeRegistry.entityArchLinks
	return func(yield func(PHead2[T1, T2]) bool) {
		var lastArch *Archetype; var cols [2]*column
		for _, e := range entities {
			link := links[e.Index()]; arch := link.arch
			if arch == nil || q.View.matches(arch.mask) { continue }
			if arch != lastArch { for i := 0; i < 2; i++ { cols[i] = arch.columns[q.compIDs[i]] }; lastArch = arch }
			idx := uintptr(link.row)
			if !yield(PHead2[T1, T2]{V1: (*T1)(unsafe.Add(cols[0].data, idx*cols[0].itemSize)), V2: (*T2)(unsafe.Add(cols[1].data, idx*cols[1].itemSize))}) { return }
		}
	}
}
