// Code generated by gen/queries; DO NOT EDIT.
package ecs
import (
	"iter"
	"unsafe"

	"github.com/kjkrol/goke/internal/core"
)

type Query5[T1, T2, T3, T4, T5 any] struct {
	*core.View
}

func newQuery5[T1, T2, T3, T4, T5 any](reg *core.Registry, options ...ViewOption) *Query5[T1, T2, T3, T4, T5] {
	viewBuilder := core.NewViewBuilder(reg)
	core.OnCompType[T1](viewBuilder)
	core.OnCompType[T2](viewBuilder)
	core.OnCompType[T3](viewBuilder)
	core.OnCompType[T4](viewBuilder)
	core.OnCompType[T5](viewBuilder)
	for _, opt := range options {
		opt(viewBuilder)
	}
	return &Query5[T1, T2, T3, T4, T5]{View: viewBuilder.Build()}
}

type Head5[T1, T2, T3 any] struct {
	Entity Entity
	V1 *T1
	V2 *T2
	V3 *T3
}
type Tail5[T4, T5 any] struct {
	V4 *T4
	V5 *T5
}
type PHead5[T1, T2, T3, T4 any] struct {
	V1 *T1
	V2 *T2
	V3 *T3
	V4 *T4
}
type PTail5[T5 any] struct {
	V5 *T5
}

func (q *Query5[T1, T2, T3, T4, T5]) All5() iter.Seq2[Head5[T1, T2, T3], Tail5[T4, T5]] {
	return func(yield func(Head5[T1, T2, T3], Tail5[T4, T5]) bool) {
		for i := range q.Baked {
			b := &q.Baked[i]
			p1, s1 := b.Columns[0].Data, b.Columns[0].ItemSize
			p2, s2 := b.Columns[1].Data, b.Columns[1].ItemSize
			p3, s3 := b.Columns[2].Data, b.Columns[2].ItemSize
			p4, s4 := b.Columns[3].Data, b.Columns[3].ItemSize
			p5, s5 := b.Columns[4].Data, b.Columns[4].ItemSize
			for j := 0; j < *b.Len; j++ {
				if !yield(Head5[T1, T2, T3]{Entity: (*b.Entities)[j], V1: (*T1)(p1), V2: (*T2)(p2), V3: (*T3)(p3)}, Tail5[T4, T5]{V4: (*T4)(p4), V5: (*T5)(p5)}) { return }
				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)
				p3 = unsafe.Add(p3, s3)
				p4 = unsafe.Add(p4, s4)
				p5 = unsafe.Add(p5, s5)
			}
		}
	}
}

func (q *Query5[T1, T2, T3, T4, T5]) Filter5(entities []Entity) iter.Seq2[Head5[T1, T2, T3], Tail5[T4, T5]] {
	links := q.Reg.ArchetypeRegistry.EntityArchLinks
	return func(yield func(Head5[T1, T2, T3], Tail5[T4, T5]) bool) {
		var lastArch *core.Archetype; var cols [5]*core.Column
		for _, e := range entities {
			link := links[e.Index()]; arch := link.Arch
			if arch == nil || q.View.Matches(arch.Mask) { continue }
			if arch != lastArch { for i := 0; i < 5; i++ { cols[i] = arch.Columns[q.CompIDs[i]] }; lastArch = arch }
			idx := uintptr(link.Row)
			if !yield(Head5[T1, T2, T3]{Entity: e, V1: (*T1)(unsafe.Add(cols[0].Data, idx*cols[0].ItemSize)), V2: (*T2)(unsafe.Add(cols[1].Data, idx*cols[1].ItemSize)), V3: (*T3)(unsafe.Add(cols[2].Data, idx*cols[2].ItemSize))}, Tail5[T4, T5]{V4: (*T4)(unsafe.Add(cols[3].Data, idx*cols[3].ItemSize)), V5: (*T5)(unsafe.Add(cols[4].Data, idx*cols[4].ItemSize))}) { return }
		}
	}
}

func (q *Query5[T1, T2, T3, T4, T5]) PureAll5() iter.Seq2[PHead5[T1, T2, T3, T4], PTail5[T5]] {
	return func(yield func(PHead5[T1, T2, T3, T4], PTail5[T5]) bool) {
		for i := range q.Baked {
			b := &q.Baked[i]
			p1, s1 := b.Columns[0].Data, b.Columns[0].ItemSize
			p2, s2 := b.Columns[1].Data, b.Columns[1].ItemSize
			p3, s3 := b.Columns[2].Data, b.Columns[2].ItemSize
			p4, s4 := b.Columns[3].Data, b.Columns[3].ItemSize
			p5, s5 := b.Columns[4].Data, b.Columns[4].ItemSize
			for j := 0; j < *b.Len; j++ {
				if !yield(PHead5[T1, T2, T3, T4]{V1: (*T1)(p1), V2: (*T2)(p2), V3: (*T3)(p3), V4: (*T4)(p4)}, PTail5[T5]{V5: (*T5)(p5)}) { return }
				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)
				p3 = unsafe.Add(p3, s3)
				p4 = unsafe.Add(p4, s4)
				p5 = unsafe.Add(p5, s5)
			}
		}
	}
}

func (q *Query5[T1, T2, T3, T4, T5]) PureFilter5(entities []Entity) iter.Seq2[PHead5[T1, T2, T3, T4], PTail5[T5]] {
	links := q.Reg.ArchetypeRegistry.EntityArchLinks
	return func(yield func(PHead5[T1, T2, T3, T4], PTail5[T5]) bool) {
		var lastArch *core.Archetype; var cols [5]*core.Column
		for _, e := range entities {
			link := links[e.Index()]; arch := link.Arch
			if arch == nil || q.View.Matches(arch.Mask) { continue }
			if arch != lastArch { for i := 0; i < 5; i++ { cols[i] = arch.Columns[q.CompIDs[i]] }; lastArch = arch }
			idx := uintptr(link.Row)
			if !yield(PHead5[T1, T2, T3, T4]{V1: (*T1)(unsafe.Add(cols[0].Data, idx*cols[0].ItemSize)), V2: (*T2)(unsafe.Add(cols[1].Data, idx*cols[1].ItemSize)), V3: (*T3)(unsafe.Add(cols[2].Data, idx*cols[2].ItemSize)), V4: (*T4)(unsafe.Add(cols[3].Data, idx*cols[3].ItemSize))}, PTail5[T5]{V5: (*T5)(unsafe.Add(cols[4].Data, idx*cols[4].ItemSize))}) { return }
		}
	}
}
