// Code generated by gen/views; DO NOT EDIT.
package ecs

import (
	"github.com/kjkrol/goke/internal/core"
	"iter"
	"unsafe"
)

type View4[T1, T2, T3, T4 any] struct {
	*core.View
}

func NewView4[T1, T2, T3, T4 any](eng *Engine, options ...ViewOption) *View4[T1, T2, T3, T4] {
	viewBuilder := core.NewViewBuilder(eng.registry)
	core.OnCompType[T1](viewBuilder)
	core.OnCompType[T2](viewBuilder)
	core.OnCompType[T3](viewBuilder)
	core.OnCompType[T4](viewBuilder)

	for _, opt := range options {
		opt(viewBuilder)
	}
	return &View4[T1, T2, T3, T4]{View: viewBuilder.Build()}
}

// --- Head/Tail ---

type Head4[T1, T2, T3 any] struct {
	Entity Entity
	V1     *T1
	V2     *T2
	V3     *T3
}

type Tail4[T4 any] struct {
	V4 *T4
}

type VHead4[T1, T2, T3, T4 any] struct {
	V1 *T1
	V2 *T2
	V3 *T3
	V4 *T4
}

// --- All / Filter ---

func (q *View4[T1, T2, T3, T4]) All() iter.Seq2[Head4[T1, T2, T3], Tail4[T4]] {
	return func(yield func(Head4[T1, T2, T3], Tail4[T4]) bool) {
		for i := range q.Baked {
			b := &q.Baked[i]
			p1, s1 := b.Columns[0].Data, b.Columns[0].ItemSize
			p2, s2 := b.Columns[1].Data, b.Columns[1].ItemSize
			p3, s3 := b.Columns[2].Data, b.Columns[2].ItemSize
			p4, s4 := b.Columns[3].Data, b.Columns[3].ItemSize

			for j := 0; j < *b.Len; j++ {
				head := Head4[T1, T2, T3]{
					Entity: (*b.Entities)[j], V1: (*T1)(p1), V2: (*T2)(p2), V3: (*T3)(p3),
				}

				tail := Tail4[T4]{V4: (*T4)(p4)}
				if !yield(head, tail) {
					return
				}

				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)
				p3 = unsafe.Add(p3, s3)
				p4 = unsafe.Add(p4, s4)

			}
		}
	}
}

func (q *View4[T1, T2, T3, T4]) Filter(selected []Entity) iter.Seq2[Head4[T1, T2, T3], Tail4[T4]] {
	links := q.Reg.ArchetypeRegistry.EntityLinkStore
	return func(yield func(Head4[T1, T2, T3], Tail4[T4]) bool) {
		var lastArch *core.Archetype
		var cols [4]*core.Column
		for _, e := range selected {
			link := links.Get(e.Index())
			arch := link.Arch
			if arch == nil || !q.View.Matches(arch.Mask) {
				continue
			}
			if arch != lastArch {
				for i := 0; i < 4; i++ {
					cols[i] = arch.Columns[q.CompIDs[i]]
				}
				lastArch = arch
			}
			idx := uintptr(link.Row)
			head := Head4[T1, T2, T3]{
				Entity: e, V1: (*T1)(unsafe.Add(cols[0].Data, idx*cols[0].ItemSize)), V2: (*T2)(unsafe.Add(cols[1].Data, idx*cols[1].ItemSize)), V3: (*T3)(unsafe.Add(cols[2].Data, idx*cols[2].ItemSize)),
			}

			tail := Tail4[T4]{V4: (*T4)(unsafe.Add(cols[3].Data, idx*cols[3].ItemSize))}
			if !yield(head, tail) {
				return
			}

		}
	}
}

// --- Values / FilterValues ---

func (q *View4[T1, T2, T3, T4]) Values() iter.Seq[VHead4[T1, T2, T3, T4]] {
	return func(yield func(VHead4[T1, T2, T3, T4]) bool) {
		for i := range q.Baked {
			b := &q.Baked[i]
			p1, s1 := b.Columns[0].Data, b.Columns[0].ItemSize
			p2, s2 := b.Columns[1].Data, b.Columns[1].ItemSize
			p3, s3 := b.Columns[2].Data, b.Columns[2].ItemSize
			p4, s4 := b.Columns[3].Data, b.Columns[3].ItemSize

			for j := 0; j < *b.Len; j++ {
				vhead := VHead4[T1, T2, T3, T4]{V1: (*T1)(p1), V2: (*T2)(p2), V3: (*T3)(p3), V4: (*T4)(p4)}

				if !yield(vhead) {
					return
				}

				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)
				p3 = unsafe.Add(p3, s3)
				p4 = unsafe.Add(p4, s4)

			}
		}
	}
}

func (q *View4[T1, T2, T3, T4]) FilterValues(selected []Entity) iter.Seq[VHead4[T1, T2, T3, T4]] {
	links := q.Reg.ArchetypeRegistry.EntityLinkStore
	return func(yield func(VHead4[T1, T2, T3, T4]) bool) {
		var lastArch *core.Archetype
		var cols [4]*core.Column
		for _, e := range selected {
			link := links.Get(e.Index())
			arch := link.Arch
			if arch == nil || !q.View.Matches(arch.Mask) {
				continue
			}
			if arch != lastArch {
				for i := 0; i < 4; i++ {
					cols[i] = arch.Columns[q.CompIDs[i]]
				}
				lastArch = arch
			}
			idx := uintptr(link.Row)
			vhead := VHead4[T1, T2, T3, T4]{V1: (*T1)(unsafe.Add(cols[0].Data, idx*cols[0].ItemSize)), V2: (*T2)(unsafe.Add(cols[1].Data, idx*cols[1].ItemSize)), V3: (*T3)(unsafe.Add(cols[2].Data, idx*cols[2].ItemSize)), V4: (*T4)(unsafe.Add(cols[3].Data, idx*cols[3].ItemSize))}

			if !yield(vhead) {
				return
			}

		}
	}
}
