// Code generated by gen/views; DO NOT EDIT.
package ecs

import (
	"github.com/kjkrol/goke/internal/core"
	"iter"
	"unsafe"
)

type View1[T1 any] struct {
	*core.View
}

func NewView1[T1 any](eng *Engine, options ...ViewOption) *View1[T1] {
	viewBuilder := core.NewViewBuilder(eng.registry)
	core.OnCompType[T1](viewBuilder)

	for _, opt := range options {
		opt(viewBuilder)
	}
	return &View1[T1]{View: viewBuilder.Build()}
}

// --- Head/Tail ---

type Head1[T1 any] struct {
	Entity Entity
	V1     *T1
}

type VHead1[T1 any] struct {
	V1 *T1
}

// --- All / Filter ---

func (q *View1[T1]) All() iter.Seq[Head1[T1]] {
	return func(yield func(Head1[T1]) bool) {
		for i := range q.Baked {
			b := &q.Baked[i]
			p1, s1 := b.Columns[0].Data, b.Columns[0].ItemSize

			for j := 0; j < *b.Len; j++ {
				head := Head1[T1]{
					Entity: (*b.Entities)[j], V1: (*T1)(p1),
				}

				if !yield(head) {
					return
				}

				p1 = unsafe.Add(p1, s1)

			}
		}
	}
}

func (q *View1[T1]) Filter(selected []Entity) iter.Seq[Head1[T1]] {
	links := q.Reg.ArchetypeRegistry.EntityLinkStore
	return func(yield func(Head1[T1]) bool) {
		var lastArch *core.Archetype
		var cols [1]*core.Column
		for _, e := range selected {
			link := links.Get(e.Index())
			arch := link.Arch
			if arch == nil || !q.View.Matches(arch.Mask) {
				continue
			}
			if arch != lastArch {
				for i := 0; i < 1; i++ {
					cols[i] = arch.Columns[q.CompIDs[i]]
				}
				lastArch = arch
			}
			idx := uintptr(link.Row)
			head := Head1[T1]{
				Entity: e, V1: (*T1)(unsafe.Add(cols[0].Data, idx*cols[0].ItemSize)),
			}

			if !yield(head) {
				return
			}

		}
	}
}

// --- Values / FilterValues ---

func (q *View1[T1]) Values() iter.Seq[VHead1[T1]] {
	return func(yield func(VHead1[T1]) bool) {
		for i := range q.Baked {
			b := &q.Baked[i]
			p1, s1 := b.Columns[0].Data, b.Columns[0].ItemSize

			for j := 0; j < *b.Len; j++ {
				vhead := VHead1[T1]{V1: (*T1)(p1)}

				if !yield(vhead) {
					return
				}

				p1 = unsafe.Add(p1, s1)

			}
		}
	}
}

func (q *View1[T1]) FilterValues(selected []Entity) iter.Seq[VHead1[T1]] {
	links := q.Reg.ArchetypeRegistry.EntityLinkStore
	return func(yield func(VHead1[T1]) bool) {
		var lastArch *core.Archetype
		var cols [1]*core.Column
		for _, e := range selected {
			link := links.Get(e.Index())
			arch := link.Arch
			if arch == nil || !q.View.Matches(arch.Mask) {
				continue
			}
			if arch != lastArch {
				for i := 0; i < 1; i++ {
					cols[i] = arch.Columns[q.CompIDs[i]]
				}
				lastArch = arch
			}
			idx := uintptr(link.Row)
			vhead := VHead1[T1]{V1: (*T1)(unsafe.Add(cols[0].Data, idx*cols[0].ItemSize))}

			if !yield(vhead) {
				return
			}

		}
	}
}
