// Code generated by gen/views; DO NOT EDIT.
package ecs

import (
	"github.com/kjkrol/goke/internal/core"
	"iter"
	"unsafe"
)

type View5[T1, T2, T3, T4, T5 any] struct {
	*core.View
}

func NewView5[T1, T2, T3, T4, T5 any](eng *Engine, options ...ViewOption) *View5[T1, T2, T3, T4, T5] {
	viewBuilder := core.NewViewBuilder(eng.registry)
	core.OnCompType[T1](viewBuilder)
	core.OnCompType[T2](viewBuilder)
	core.OnCompType[T3](viewBuilder)
	core.OnCompType[T4](viewBuilder)
	core.OnCompType[T5](viewBuilder)

	for _, opt := range options {
		opt(viewBuilder)
	}
	return &View5[T1, T2, T3, T4, T5]{View: viewBuilder.Build()}
}

// --- Head/Tail ---

type Head5[T1, T2, T3 any] struct {
	Entity Entity
	V1     *T1
	V2     *T2
	V3     *T3
}

type Tail5[T4, T5 any] struct {
	V4 *T4
	V5 *T5
}

type VHead5[T1, T2, T3, T4 any] struct {
	V1 *T1
	V2 *T2
	V3 *T3
	V4 *T4
}

type VTail5[T5 any] struct {
	V5 *T5
}

// --- All / Filter ---

func (q *View5[T1, T2, T3, T4, T5]) All() iter.Seq2[Head5[T1, T2, T3], Tail5[T4, T5]] {
	return func(yield func(Head5[T1, T2, T3], Tail5[T4, T5]) bool) {
		for i := range q.Baked {
			b := &q.Baked[i]
			p1, s1 := b.Columns[0].Data, b.Columns[0].ItemSize
			p2, s2 := b.Columns[1].Data, b.Columns[1].ItemSize
			p3, s3 := b.Columns[2].Data, b.Columns[2].ItemSize
			p4, s4 := b.Columns[3].Data, b.Columns[3].ItemSize
			p5, s5 := b.Columns[4].Data, b.Columns[4].ItemSize

			for j := 0; j < *b.Len; j++ {
				head := Head5[T1, T2, T3]{
					Entity: (*b.Entities)[j], V1: (*T1)(p1), V2: (*T2)(p2), V3: (*T3)(p3),
				}

				tail := Tail5[T4, T5]{V4: (*T4)(p4), V5: (*T5)(p5)}
				if !yield(head, tail) {
					return
				}

				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)
				p3 = unsafe.Add(p3, s3)
				p4 = unsafe.Add(p4, s4)
				p5 = unsafe.Add(p5, s5)

			}
		}
	}
}

func (q *View5[T1, T2, T3, T4, T5]) Filter(selected []Entity) iter.Seq2[Head5[T1, T2, T3], Tail5[T4, T5]] {
	links := q.Reg.ArchetypeRegistry.EntityLinkStore
	return func(yield func(Head5[T1, T2, T3], Tail5[T4, T5]) bool) {
		var lastArch *core.Archetype
		var cols [5]*core.Column
		for _, e := range selected {
			link := links.Get(e.Index())
			arch := link.Arch
			if arch == nil || !q.View.Matches(arch.Mask) {
				continue
			}
			if arch != lastArch {
				for i := 0; i < 5; i++ {
					cols[i] = arch.Columns[q.CompIDs[i]]
				}
				lastArch = arch
			}
			idx := uintptr(link.Row)
			head := Head5[T1, T2, T3]{
				Entity: e, V1: (*T1)(unsafe.Add(cols[0].Data, idx*cols[0].ItemSize)), V2: (*T2)(unsafe.Add(cols[1].Data, idx*cols[1].ItemSize)), V3: (*T3)(unsafe.Add(cols[2].Data, idx*cols[2].ItemSize)),
			}

			tail := Tail5[T4, T5]{V4: (*T4)(unsafe.Add(cols[3].Data, idx*cols[3].ItemSize)), V5: (*T5)(unsafe.Add(cols[4].Data, idx*cols[4].ItemSize))}
			if !yield(head, tail) {
				return
			}

		}
	}
}

// --- Values / FilterValues ---

func (q *View5[T1, T2, T3, T4, T5]) Values() iter.Seq2[VHead5[T1, T2, T3, T4], VTail5[T5]] {
	return func(yield func(VHead5[T1, T2, T3, T4], VTail5[T5]) bool) {
		for i := range q.Baked {
			b := &q.Baked[i]
			p1, s1 := b.Columns[0].Data, b.Columns[0].ItemSize
			p2, s2 := b.Columns[1].Data, b.Columns[1].ItemSize
			p3, s3 := b.Columns[2].Data, b.Columns[2].ItemSize
			p4, s4 := b.Columns[3].Data, b.Columns[3].ItemSize
			p5, s5 := b.Columns[4].Data, b.Columns[4].ItemSize

			for j := 0; j < *b.Len; j++ {
				vhead := VHead5[T1, T2, T3, T4]{V1: (*T1)(p1), V2: (*T2)(p2), V3: (*T3)(p3), V4: (*T4)(p4)}

				vtail := VTail5[T5]{V5: (*T5)(p5)}
				if !yield(vhead, vtail) {
					return
				}

				p1 = unsafe.Add(p1, s1)
				p2 = unsafe.Add(p2, s2)
				p3 = unsafe.Add(p3, s3)
				p4 = unsafe.Add(p4, s4)
				p5 = unsafe.Add(p5, s5)

			}
		}
	}
}

func (q *View5[T1, T2, T3, T4, T5]) FilterValues(selected []Entity) iter.Seq2[VHead5[T1, T2, T3, T4], VTail5[T5]] {
	links := q.Reg.ArchetypeRegistry.EntityLinkStore
	return func(yield func(VHead5[T1, T2, T3, T4], VTail5[T5]) bool) {
		var lastArch *core.Archetype
		var cols [5]*core.Column
		for _, e := range selected {
			link := links.Get(e.Index())
			arch := link.Arch
			if arch == nil || !q.View.Matches(arch.Mask) {
				continue
			}
			if arch != lastArch {
				for i := 0; i < 5; i++ {
					cols[i] = arch.Columns[q.CompIDs[i]]
				}
				lastArch = arch
			}
			idx := uintptr(link.Row)
			vhead := VHead5[T1, T2, T3, T4]{V1: (*T1)(unsafe.Add(cols[0].Data, idx*cols[0].ItemSize)), V2: (*T2)(unsafe.Add(cols[1].Data, idx*cols[1].ItemSize)), V3: (*T3)(unsafe.Add(cols[2].Data, idx*cols[2].ItemSize)), V4: (*T4)(unsafe.Add(cols[3].Data, idx*cols[3].ItemSize))}

			vtail := VTail5[T5]{V5: (*T5)(unsafe.Add(cols[4].Data, idx*cols[4].ItemSize))}
			if !yield(vhead, vtail) {
				return
			}

		}
	}
}
